### ISSUE TITLE
(Enchacement) Library or playlist should display the Liked Songs playlist

### ISSUE THREAD

**Issue by Barraguesh** [xou816/spot#100]
Liked song playlist is nowhere to be seen. I can see my liked full albums in the library but that's it. I mainly used liked songs so I was surprised to not to have the option.

**Comment by xou816** [comment]
Duplicate of #51 ;) but thank you for your interest! I agree this is needed

**Comment by Barraguesh** [comment]
Sorry I searched with "Liked songs" and didn't find anything...

**Comment by xou816** [comment]
No worries, I'll actually update the other issue to use your title, it's a bit clearer!
