### ISSUE TITLE
[Feature] Discord Rich Presence/Integeration

### ISSUE THREAD

**Issue by Essasetic** [xou816/spot#101]
Rich Presence - it would be nice for the song, metadata, thumbnail and the time to be displayed like the official Spotify client.
e.g.
![Screenshot from 2021-02-25 10-50-49](https://user-images.githubusercontent.com/34970796/109143679-34b47080-7758-11eb-96f1-17b4b50e78cb.png)

Integration - This would allow listen together sessions on discord (like on the official client). I'm pretty certain this is a massive stretch though and most likely impossible to implement. 
But one can dream :)

**Comment by xou816** [comment]
Yeah, sorry no clue how that would be implemented and really not a priority given spot is still missing quite a few basic features sorry ;)

**Comment by Douile** [comment]
@Essasetic is you want discord RPC while you using spot there are a few MPRIS rpc clients you can get. such as this one I found: https://github.com/RayzrDev/discord-rpc-mpris . Doesn't do thumbnails (Can't really do thumbnails from normal discord applications) but shows song and artist name.

**Comment by jannuary** [comment]
Don't quote me on that, but I think fixing #55 should also make Discord RPC work.
