### ISSUE TITLE
Back button doesn't change the selected track list

### ISSUE THREAD

**Issue by sloshyyy** [xou816/spot#103]
**Describe the bug**
When viewing an album, if you click the artist, and then look at one of their other pieces, and then use the back button to get back to the original album, it will instead show the track list from the album that was navigated to through the artist page.  If any of the bugged tracks are clicked, the program crashes.

**To Reproduce**
1. Go to any album
2. Click on the artist
3. Select another album in the artist's menu
4. Use the back button to return to the album in step 1
5. See error

**Expected behavior**
The correct track list is loaded for the relevant album.

**General information:**
 - Distribution: Ubuntu 20.04
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub, Also present on master
 - Version [e.g. 0.1.0]: 0.1.8
 - Device used [e. g. desktop, phone...]: Desktop, GNOME 3.36 X.Org

**Stack trace:**
Stack trace from when I tried to select one of the bugged songs
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
Gtk-Message: 23:39:41.229: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:39:41.230: Failed to load module "canberra-gtk-module"
home
album_1I8mUtgebG39rNBApC7clb
artist_6hG0VsXXlD10l60TqiIHIX
album_2coNG13rwtzL6AVPmzcoty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/app/list_store.rs:45:14
stack backtrace:
   0:     0x55c1d32a5cb0 - <unknown>
   1:     0x55c1d32c975c - <unknown>
   2:     0x55c1d329e892 - <unknown>
   3:     0x55c1d32a7f55 - <unknown>
   4:     0x55c1d32a7aaa - <unknown>
   5:     0x55c1d32a86f1 - <unknown>
   6:     0x55c1d32a8207 - <unknown>
   7:     0x55c1d32a616c - <unknown>
   8:     0x55c1d32a8199 - <unknown>
   9:     0x55c1d32c6f71 - <unknown>
  10:     0x55c1d32c6ebd - <unknown>
  11:     0x55c1d2b9145a - <unknown>
  12:     0x55c1d2b63864 - <unknown>
  13:     0x55c1d2b8fe5d - <unknown>
  14:     0x55c1d2ad21ae - <unknown>
  15:     0x55c1d2a9b84a - <unknown>
  16:     0x55c1d2b5cfaf - <unknown>
  17:     0x55c1d32793d3 - <unknown>
  18:     0x55c1d327acfa - <unknown>
  19:     0x7f2fbdd6d53b - g_main_context_dispatch
  20:     0x7f2fbdd6d7e8 - <unknown>
  21:     0x7f2fbdd6d8b3 - g_main_context_iteration
  22:     0x7f2fbdf9358d - g_application_run
  23:     0x55c1d2ab984e - <unknown>
  24:     0x55c1d2acb3a8 - <unknown>
  25:     0x7f2fbdd6e665 - g_main_context_invoke_full
  26:     0x55c1d2b17504 - <unknown>
  27:     0x55c1d2ac2903 - <unknown>
  28:     0x55c1d2a81839 - <unknown>
  29:     0x55c1d32a8b17 - <unknown>
  30:     0x55c1d2b17722 - main
  31:     0x7f2fbd9d4062 - __libc_start_main
  32:     0x55c1d2a5113e - <unknown>
  33:                0x0 - <unknown>

```

**Comment by xou816** [comment]
Hi! Thanks for the report, it was very easy to reproduce the issue, that was one nasty crash :/ I'll release a fix asap!
