### ISSUE TITLE
Long playlist titles mess up playlist display spacing

### ISSUE THREAD

**Issue by aochen-jli** [xou816/spot#112]
**Describe the bug**
Very long playlist titles mess up the playlist display's spacing. 

**To Reproduce**
1. Make a playlist with the maximum allowed characters on Spotify.
2. Go to the playlist view in spot

**Expected behavior**
Long titles should be truncated to preserve the column spacing.

**General information:**
 - Distribution: 
 - Installation method: Built from source
 - Version [e.g. 0.1.0]: 0.1.8
 - Device used [e. g. desktop, phone...]: Raspberry Pi, Manjaro

**Comment by xou816** [comment]
Hi! Would you mind sharing a screenshot or a playlist id? I'm not sure I see what you mean :/

**Comment by Douile** [comment]
I believe he is referring to when this happens (library UI columns extend).

![image of long album name](https://i.imgur.com/cyx8n3G.png)

**Comment by rafaelmardojai** [comment]
It seems to be fixed in `0.1.9`.

![Captura de pantalla de 2021-03-02 09-54-30](https://user-images.githubusercontent.com/6210397/109666580-4e313000-7b3d-11eb-824a-2ea4b3f3f8f7.png)

**Comment by Douile** [comment]
Still seems to be broken for album names

**Comment by xou816** [comment]
Same component in both cases; labels are probably not allowed to break at characters, only word boundaries! Should be an easy fix :)

**Comment by xou816** [comment]
should have been fixed, feel free to reopen if needed!
