### ISSUE TITLE
Gnome Builder fails to Build the Project at build-aux/cargo.sh

### ISSUE THREAD

**Issue by c-ortl** [xou816/spot#122]
**Describe the bug**
When i try to build the project, it always fails on this:
```
debug
/home/[user]/Projects/spot/build-aux/cargo.sh: line 24: cargo: command not found
FAILED: src/spot 
/bin/bash /home/[user]/Projects/spot/build-aux/cargo.sh /home/corti/Projects/spot /home/[user]/.cache/gnome-builder/projects/spot/builds/dev.alextren.Spot.json-flatpak-org.gnome.Platform-x86_64-3.38-master spot src/spot debug '' true
ninja: build stopped: subcommand failed.
```
**To Reproduce**
- clone this repository (master) in Builder
- install all missing dependencies via Builder
- build

**Expected behavior**
it Building the Project

**General information:**
 - Distribution: Ubuntu 20.10
 - Installation method [e. g. built from source, installed from Flathub...]: Gnome Builder
 - Version [e.g. 0.1.0]: 0.1.9
 - Device used [e. g. desktop, phone...]: desktop

I am still pretty new to this so I would really appreciate a detailed answer :).

**Comment by xou816** [comment]
No problem, let's have a look, I'm not sure the instructions on the README are up to date anyway!

Has the org.freedesktop.Sdk.Extension.rust-stable been installed? It should have been installed, you may check with `flatpak info org.freedesktop.Sdk.Extension.rust-stable` for instance

**Comment by c-ortl** [comment]
Yes it has, this is the output:
```
          ID: org.freedesktop.Sdk.Extension.rust-stable
         Ref: runtime/org.freedesktop.Sdk.Extension.rust-stable/x86_64/1.6
        Arch: x86_64
      Branch: 1.6
     Version: 1.44.1
     License: Apache-2.0 AND MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 482,0 MB

      Commit: f49dd2726fb76b65fb49303d15ef9da085f51c8db64a3e059cdcbfe419809b81
      Parent: 49f8b9a14ce502a8418af6513abbf4231aae08749da86ee6cc3330a217b258b7
     Subject: update armv7 module after the url was fixed (a44e4a5e)
        Date: 2020-07-01 08:10:08 +0000
 End-of-life: The Freedesktop 1.6 SDK is no longer supported and does not recei…
```

**Comment by xou816** [comment]
Looks like this is an older version, you might have to install the freedesktop runtime and this rust extension in version 20.08! I wonder if there's a way for me to specify this version in the manifest

**Comment by c-ortl** [comment]
Hm I don't know. Anyways,  I am now on Version 20.08 and I have a different error message (yay):
```
error: no matching package named `async-std` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `spot v0.1.9 (/home/[user]/Projects/spot)`
As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
FAILED: src/spot 
/bin/bash /home/[user]/Projects/spot/build-aux/cargo.sh /home/[user]/Projects/spot /home/[user]/.cache/gnome-builder/projects/spot/builds/dev.alextren.Spot.json-flatpak-org.gnome.Platform-x86_64-3.38-master spot src/spot debug '' true
ninja: build stopped: subcommand failed.
```
I have tried to find out what the `--offline` option is and where I can turn it off but I was not successful :(.

**Comment by xou816** [comment]
Ooops, the offline thing is on me! I'll have to create a separate manifest for development but in the meantime, remove the line that says `"-Doffline=true",` from config-opts

I'll also update the README to mention the freedesktop SDK version issue

(it enables the --offline switch cargo, which forces cargo to work with previously downloaded crates and prevents it from downloading them)

**Comment by c-ortl** [comment]
Nice, the build was successful now, but I had to explicitly specify `-Doffline=false` (just deleting it didn't do the trick)!
Thank you so much for your Help :+1: :)

**Comment by xou816** [comment]
Thanks, I updated the README!
