### ISSUE TITLE
Play time doesn't update

### ISSUE THREAD

**Issue by Douile** [xou816/spot#123]
**Describe the bug**
The play time doesn't update as the song plays and stays at 00:00.

**To Reproduce**
1. Go to playlist
2. Play a track
3. Wait, play time doesn't update

**Expected behavior**
Play time updates as track plays

**General information:**
 - Installation method [e. g. built from source, installed from Flathub...]: build
 - Version [e.g. 0.1.0]: fc299290416bfbeed3e02bf99fdc67331b27720f
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
No errors output

**Additional context**
It updates to the time you skip to if you skip.

**Comment by Douile** [comment]
That was fast, haha.

**Comment by Douile** [comment]
Fixed

**Comment by xou816** [comment]
Happened to be around and immediately felt ashamed :p Thanks for the heads up!
