### ISSUE TITLE
MPRIS play pause integration not working

### ISSUE THREAD

**Issue by exciteabletom** [xou816/spot#128]
First off, thank you so much for making this project! It's awesome to finally have good alternatives to the official client.

**Describe the bug**
Trying to play/pause using media keys, playerctl, or the KDE media widget does not have any effect. It works fine with all other music players.

It produces the error: `GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Not implemented`

**To Reproduce**
1. Run `playerctl -p Spot pause` or `playerctl -p Spot play`
2. See error: `Could not execute command: GDBus.Error:org.freedesktop.DBus.Error.NotSupported: Not implemented
`

**Expected behavior**
I expected the song state to change

**General information:**
 - Distribution: Manjaro
 - Installation method: Installed from AUR package `spot-client`
 - Version: 0.1.9-1
 - Device used: desktop

**Comment by xou816** [comment]
Hi! Thank you for the kind words and the report :)

I have been lazy and implemented only [PlayPause](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Method:PlayPause), which you can use in the meantime! I'll have a look at play and pause!

**Comment by exciteabletom** [comment]
Thanks so much! Working fine now with that latest commit.
