### ISSUE TITLE
can't log out after changing password

### ISSUE THREAD

**Issue by LennyPenny** [xou816/spot#129]
**Describe the bug**
I was logged in to spot when I changed my spotify password. 

**To Reproduce**
1. Log in to spot
2. Change password through spotify website
3. Restart spot (might be delayed, I only noticed this a full day after changing password)

**Expected behavior**
Auto logout or at least a log out button

![image](https://user-images.githubusercontent.com/4027243/110034708-0f68c900-7d3b-11eb-95db-2c53570be47e.png)

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run dev.alextren.Spot
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /run/build/spot/cargo/vendor/librespot-core-0.1.6/src/connection/mod.rs:121:21

```

Is there a way I can manually delete the login token? I didn't find anything in `~/.config/`

**Comment by xou816** [comment]
It looks like you're running an older version of the app (latest is 0.1.9). Newer versions have a logout button in the menu. Hope this helps!

**Comment by LennyPenny** [comment]
I am running `0.1.9` 
![image](https://user-images.githubusercontent.com/4027243/110038389-fadaff80-7d3f-11eb-8566-6f77a810e3c7.png)

**Comment by xou816** [comment]
No no I've just been too quick to answer without thinking! Sorry about that :) the password is stored in a keyring; that'd be seahorse aka GNOME Keyring in GNOME based distros usually. Look for something called spot credentials!

Since authentication fails, the app should definitely clear saved credentials!

**Comment by LennyPenny** [comment]
thx! leaving this open then

**Comment by LennyPenny** [comment]
I was gonna try and fix this myself and then I noticed you already worked on a relevant part of the solution upstream (https://github.com/librespot-org/librespot/pull/138) - sadly this didn't seem to make it into 0.1.6 :(

**Comment by xou816** [comment]
Yeah, we'll have to be patient :p 

There is however the issue of logging out, which [fails if the keyring is locked](https://github.com/xou816/spot/blob/master/src/app/components/user_menu/user_menu_model.rs#L24); this should be allowed to fail.

**Comment by nrsc** [comment]
Hello I had the same issue, see [issue#138](https://github.com/xou816/spot/issues/138). Do you also have spotify installed on your machine?
