### ISSUE TITLE
Packaging as Snap/Flatpak

### ISSUE THREAD

**Issue by alexanderadam** [xou816/spot#13]
Spot looks soo wonderful! Thank you so much for your work!

Would it be possible to [provide a Snap package](https://snapcraft.io/docs/rust-applications#side-nav-drawer) or Flatpak in the long term?

Thank you in advance.

**Comment by xou816** [comment]
Hi :) thank you very much for the kind words! 

Most of the work for a Flatpak is in place, I just need to wrap up a few things (icon, appstream). I'll look into it soon hopefully!

As for Snap, I have no experience with them, but I might look into if it isn't too complicated. Feel free to contribute a snap if you feel like it as well :)

**Comment by xou816** [comment]
Flatpak is available on [Flathub](https://flathub.org/apps/details/dev.alextren.Spot) :)

**Comment by q-wertz** [comment]
The snap seems to be unmaintained https://github.com/popey/spot-snap/issues/4#issuecomment-1012492054
