### ISSUE TITLE
[Feature Request] Use KWallet to store Login Credentials

### ISSUE THREAD

**Issue by KaratekHD** [xou816/spot#134]
A lot of applications can use KWallet, KDEs Password Manager (similar to Gnome Keyring), to store credentials. Would it be possible to use KWallet when running the application on a KDE Plasma Desktop?

There is also a documentation about how to use KWallet inside other applications: https://api.kde.org/frameworks-api/frameworks-apidocs/frameworks/kwallet/html/

**Comment by xou816** [comment]
Ah, it's a shame KWallet doesn't use libsecret :/ I am sorry, I won't be able to do that (there are only C++ (?) bindings I suppose), and I can't possibly support every secret management framework :/
