### ISSUE TITLE
Playback speed change?

### ISSUE THREAD

**Issue by Jeffrey04** [xou816/spot#136]
Just out of curiosity, is playback speed change possible (playback in certain bpm for practice etc.)

**Comment by exciteabletom** [comment]
I can't see anything like that in the [Spotify API](https://developer.spotify.com/documentation/web-api/reference/#category-player) So I would guess the answer is no.

**Comment by xou816** [comment]
Yup, another solution would be to buffer enough content, use a GStreamer backend and have a custom GStreamer pipeline etc... but that's definitely beyond my abilities! Marking this as wontfix for now
