### ISSUE TITLE
Add album year to the album list

### ISSUE THREAD

**Issue by raaffaaeell** [xou816/spot#137]
Hello there, I'm trying both your app and the ncspot these days and I just noticed that both dont show the year (or give us a way to sort the albums by release date). I think it'ld help a lot discovering music through the app. Or maybe create an option, if people feel it'll clutter the list (I doubt)

Cheers

**Comment by xou816** [comment]
That'd be great yeah :) on the albums details screen too!

**Comment by sei0o** [comment]
I'd like to work on this.

**Comment by xou816** [comment]
Great! :) I haven't given this proper thought but I think the year could fit in an extra label below the existing labels maybe? 

> **Album**
> Artist
> _year_

Either that or appended to the album title.

> **Album** (year)
> Artist

What do you think?

**Comment by jannuary** [comment]
I think a third label below the artist name with amount of songs, total length and year could work. That label could also be interactive - clicking on it would bring the existing details panel with copyright info.

**Comment by sei0o** [comment]
Some album/track titles comes with parentheses (e.g. `An Album (Somebody Remix)`) and extra parentheses might sound a bit verbose... Some styling (boldness, font size, etc) will do, but for now I am thinking of implementing the first option (a year label below an artist label). Maybe use the second option in compact modes (#162) ?

**Comment by jannuary** [comment]
Oh wait, my bad, I thought this was about the details view, not about the album view. In that case, just the year underneath the artist name, styled semitransparently, would work.
