### ISSUE TITLE
Account details missing and UI blank after password change

### ISSUE THREAD

**Issue by nrsc** [xou816/spot#138]
**Describe the bug**
Changed password for my spotify premium account and can no longer see any account details/option to modify anything, and no user data is being shown. Upon reinstall, no option to modify account details is presented. UI is blank. 

**To Reproduce**
1. Working version of 0.1.8
2. Change spotify password
3. Uncertain if updated to 0.1.9 before issue presented.
 

**behavior**
No option to update account details. Cached content present. After reinstall/purge, cached content gone. Presented only with blank UI w/ library/playlists/now playing on left panel.

**General information:**
 - Pop!_OS 20.04 LTS x86_64
 - Installed using Pop! shop
 -  0.1.8/9
 - desktop

**Additional context**
Need help to update my user information so I can continue to use the application. 

Thanks!

**Comment by xou816** [comment]
I'm sorry for your trouble :/ If you have a log out entry in the menu, could you try this, and if you don't, could you try wiping your old credentials from GNOME Keyring/seahorse?

**Comment by nrsc** [comment]
Hey I don't seem to have any credentials for spot in my my gnome keyring. How can I get spot talking to it?

**Comment by xou816** [comment]
Hi! Is it unlocked when Spot is launched? Do you get any error or warning from Spot?

**Comment by nrsc** [comment]
No warnings, data, messages or libraries. Is there a cache I can clear somewhere so it's as if the program has never been on my system before?

**Comment by xou816** [comment]
Absolutely: you can delete the ~/.var/app/dev.alextren.Spot directory (assuming you're using flatpak, don't know for snaps).

You should also check GNOME Keyring/seahore and remove "Spotify Credentials"

**Comment by nrsc** [comment]
Hello wanted to update. I also had Spotify installed on my machine, and found that I had to delete the spotify credentials from seahorse, and I was able to update my password.

**Comment by ondras12345** [comment]
I don't think the official Spotify client stores your credentials in the keyring.
I think you might have misidentified the "Spotify Credentials" as being used by the official client instead of Spot. It should have `spot_credentials: yes` in the Details field.

**Comment by xou816** [comment]
Indeed those are the ones! The naming could use some improvement I guess.
I'll update the readme to assist in finding the right credentials should other persons run into a similar issue.

**Comment by nrsc** [comment]
Thanks! Love the app nice and light weight. 

⁣Scott​
