### ISSUE TITLE
Possible free tier in a future?

### ISSUE THREAD

**Issue by Phosphorus-M** [xou816/spot#141]
I don't like much Spotify, but maybe with Spot in the future I will pay but I'm not convinced of Spotify, I like more Deezer. But this will be great if Spot supports free accounts. 

PD: OMG Great implementation it's very quickly more than the official client

**Comment by exciteabletom** [comment]
Unfortunately the Spotify API only supports premium accounts, so this is not possible

**Comment by xou816** [comment]
What Tom said :) see also https://github.com/librespot-org/librespot/issues/261#issuecomment-437448540
