### ISSUE TITLE
[l10n] Ambiguous source Strings and other suggestions

### ISSUE THREAD

**Issue by daPhipz** [xou816/spot#149]
I am very sorry that I am unable to propose a PR, but I can't code in Rust - a bit of Shell Scripting is all I am able to do xD
That's why I decided to contribute mostly translations to GNOME and other FOSS projects.

While working on the German translation for `spot`, I noticed that the following Strings could be interpreted wrongly:

- `Queue`: Is this the noun or does it describe the action of adding a song to the queue? For the latter, maybe use `Add to queue` instead
- `Queue selected`: Does this describe that the queue is selected or the action to add all selected songs to the queue? (same for `Dequeue selected`)

To avoid these pitfalls that could result in a faulty translation, you could add comments to the source files. When they include a specific keyword (`XXX`) set by you with the `--add-comments=XXX` flag of `xgettext`, they will appear in the `pot` file.
If you have further questions on the generation of `po/pot` files, do ask me!

I have some other String-related suggestions, too:

- Change `Dequeue` to `Remove from queue` or (if the string needs to be short) just `Remove` (It is "Remove" in the official Spotify Android app)
- Change `Dequeue selected` to `Remove selected from queue`
- Change `Connection refreshed` to `Connection restored`, assuming it means that the connection was lost and is now back. Judging from the French translation, this is the case. Is that true?

**Comment by xou816** [comment]
No worries, this is very helpful, this is the kind of thing for which I need feedback from translators!

I'll try adding some comments here and there :)

Good point about queuing/dequeuing, this will be clearer in English too!

**Comment by xou816** [comment]
Thank you for your suggestions, I've updated the pot file!

**Comment by daPhipz** [comment]
Nice, thank you very much!
