### ISSUE TITLE
[l10n] Add Translation instructions for Dummies

### ISSUE THREAD

**Issue by daPhipz** [xou816/spot#150]
I would appreciate it if the README instructions on how to translate spot into different languages were a bit more accessible. Translating software is a great way to contribute if your coding skills aren't that good, so it should be easy to do so in my opinion.

Personally, I would like to make sure that the German translation includes all translatable strings before submitting a PR - but running the commands gives me the following error:

```bash
$ ninja spot-pot -C target
ninja: Entering directory `target'
ninja: fatal: chdir to 'target' - No such file or directory
```

When I create the `target` directory, the error message changes:

```bash
$ ninja spot-pot -C target
ninja: Entering directory `target'
ninja: error: loading 'build.ninja': No such file or directory
```

What am I supposed to do here? Thanks in advance!

**Comment by exciteabletom** [comment]
Have you run `meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"`? AFAIK that should create the target directory with the build files it needs

**Comment by xou816** [comment]
Thanks Tom, indeed the project needs to be configured before. Might be worth improving the README indeed!

**Comment by daPhipz** [comment]
@exciteabletom Yes, I did;

```bash
$ meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"
The Meson build system
Version: 0.55.3
Source dir: /home/philipp/Programming/Translations/spot
Build dir: /home/philipp/Programming/Translations/spot/target
Build type: native build
Project name: spot
Project version: 0.1.10
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program glib-compile-schemas found: YES
Program appstream-util found: NO
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Found CMake: /usr/bin/cmake (3.16.3)
Run-time dependency libhandy-1 found: NO (tried pkgconfig and cmake)

src/meson.build:3:0: ERROR: Dependency "libhandy-1" not found, tried pkgconfig and cmake

A full log can be found at /home/philipp/Programming/Translations/spot/target/meson-logs/meson-log.txt
```

I can see that I am missing the dependency `libhandy-1`, but I am unable to find it in the Ubuntu repos via `apt install libhandy-1`.
All ninja commands mentioned in the README fail as follows:

```
ninja: Entering directory `target'
ninja: error: loading 'build.ninja': No such file or directory
```

Thank you for helping me out, the noob that I am! It is greatly appreciated.

**Comment by xou816** [comment]
Hmm, maybe meson is stuck because of the missing dependency and does not generate build.ninja... I might try adding a fallback to build libhandy from source (as a subproject) when it's not availble

But to get started, you don't need to use the commands mentioned in the README, it's mostly when new msgids need to be integrated or updated! Editing LINGUAS + using the .pot file as a template is enough. I'll try to write something in the README!

**Comment by daPhipz** [comment]
Thanks for the effort :)
Yes, getting meson/ninja to work is not really necessary for being able to contribute translations. It would be nice to build the application with the new translations in order to check if everything looks good, though...

**Comment by xou816** [comment]
I added a few lines to the README, hopefully that helps contributors!

But you're right about being able to test; I'll add the flatpak snapshot builds to the MRs as well I think.

**Comment by daPhipz** [comment]
Thank you very much, exactly what I had in mind!

Do ping me if there are new translatable strings, I'm happy to help!
