### ISSUE TITLE
Search icon is missing

### ISSUE THREAD

**Issue by garrett** [xou816/spot#155]
**Describe the bug**
The search icon is broken, at least in the flatpak of Spot from Flathub running on GNOME (Adwaita). I'm not sure if this is a bug in Spot or the way it was packaged.

**Screenshots**

![Screenshot from 2021-03-16 14-16-29](https://user-images.githubusercontent.com/10246/111317294-4fe21400-8664-11eb-8e30-00a3688856b3.png)

Here's a crop with 3× zoom to show the problem spot:

![Screenshot from 2021-03-16 14-16-29 - crop](https://user-images.githubusercontent.com/10246/111317292-4f497d80-8664-11eb-9266-74741702007b.png)

**General information:**
 - Distribution: Fedora 34 beta, Silverblue
 - Desktop: GNOME 40 with default Adwaita theme
 - Installation method: Flatpak from Flathub
 - Version: 0.1.10
 - Device used: Desktop

**Comment by xou816** [comment]
Thanks for the report! That's weird, I thought it was supposed to be a standard, system provided icon :/ but I was wrong, and I forgot I had a non default theme. I'll fix that ASAP!

**Comment by xou816** [comment]
Fixed in 0.1.11
