### ISSUE TITLE
Seekbar "knob" not always drawn above other UI elements

### ISSUE THREAD

**Issue by xou816** [xou816/spot#165]
![Capture d’écran du 2021-03-17 22-59-09](https://user-images.githubusercontent.com/6277494/111544353-3deb9880-876c-11eb-8f55-d764f7f75501.png)

No idea what is happening, I'll have to bisect because I think this is recent ;)

**Comment by xou816** [comment]
Looks like it's related to a Gtk update, I'll have to find a way to work around it!

**Comment by tabzlock** [comment]
Can confirm this is happening for me after updating to fedora 34 beta. I'm trying out some things to fix this and ill see if they work but Its unlikely I will be able to fix this issue so best of luck.

**Comment by tabzlock** [comment]
I couldn't figure out how to fix it but I found another issue with seek, if you keep scrolling the timestamp can go infinitely. also I don't know if you can fix it but currently scrubbing through the songs is very laggy.

**Comment by xou816** [comment]
Cool, thanks for investigating a bit on your end :) This seems to confirm it's a new behavior from Gtk.

Would you mind creating a dedicated issue for the scrolling issue?

As for the lag, could you be more specific? Is the UI unresponsive, or is it that the song takes a little while to catch up with the new position?

**Comment by tabzlock** [comment]
I am by no means a professional developer or anything I have onky really been doing gtk4 rust development as an off hobby so take my analysis as a grain of salt. But nothing really stuck out a huge amount to me. 

Ill have some time tommorow to do a proper issue report on the other issues related to the seek bar.

**Comment by xou816** [comment]
No worries, I am no Gtk pro either!

**Comment by Douile** [comment]
This is a tricky one, I'm experimenting with gtk::Overlay but not having much success: every time I fix the problem I create a new one. Couldn't seem to find any help for this online either.

**Comment by xou816** [comment]
Same here! :/ maybe we'll just have to change the design a bit (very tall seekbar so that the knob fits?)

I also need to dig more into the gtk doc -- pretty sure there are things that can help us here!

**Comment by Douile** [comment]
Making the seekbar taller does work, but it gets rid of the overlay effect :(. I'm pretty sure it is possible to get working with overlays but would need some kind of spacer (might be inefficient for rendering).

**Comment by Douile** [comment]
There is https://stackoverflow.com/questions/32085193/how-to-make-a-widget-in-the-front-of-ohter-widgets-in-gtk https://gtk-rs.org/docs/gdk/trait.WindowExt.html#tymethod.raise I'm going to see if that would work now

**Comment by Douile** [comment]
Nah that didn't work, think I was just raising the root window :)

**Comment by xou816** [comment]
Thanks for trying things! :)

https://developer.gnome.org/gtk3/stable/GtkWidget.html#GtkWidget--app-paintable looks promising too; looks like it could impact the drawing order (https://developer.gnome.org/gtk3/stable/chap-drawing-model.html) but that is not its primary intent.


(oh and as for the rest -- sorry, I am a bit busy atm, but I'm still working when I can on the long playlists thingy and improved selection; as always don't hesitate to reach out if there's something you want to work on or if I am blocking you in some way)

**Comment by xou816** [comment]
Similar report here: https://github.com/xou816/spot/issues/191

**Comment by xou816** [comment]
Fixed with Gtk4 for some reason :)

**Comment by xou816** [comment]
Fixed in 0.2.0
