### ISSUE TITLE
Text not translated

### ISSUE THREAD

**Issue by kleinHeiti** [xou816/spot#166]
If no track is selected in the "Library" tab, the text "No song playing" appears at the bottom of the window. This text can be translated and is also translated in the new version 0.1.11. (see screenshot).

![Bildschirmfoto vom 2021-03-18 07-40-20](https://user-images.githubusercontent.com/54942072/111585050-0d811a00-87bf-11eb-8ada-0652d29f3940.png)

If you now switch to the "Now playing" tab and click on the icon in the upper right corner (looks a bit like an eraser), the text "No song playing" appears without translation.

![Bildschirmfoto vom 2021-03-18 07-41-55](https://user-images.githubusercontent.com/54942072/111585064-14a82800-87bf-11eb-8ff2-45b3519b9efa.png)
It seems that this passage cannot be translated.

**Comment by xou816** [comment]
Good catch, forgot a gettext call! Thanks!

**Comment by xou816** [comment]
Fixed, will be in next version!
