### ISSUE TITLE
Controls shift with song name length

### ISSUE THREAD

**Issue by kleinHeiti** [xou816/spot#167]
The controls for "play", "forward" and "back" shift with the length of the title. This is only effective when the window is not in full screen or is pulled very small.

![Bildschirmfoto vom 2021-03-18 09-01-39-1](https://user-images.githubusercontent.com/54942072/111594115-f0524880-87ca-11eb-9398-80341dc81692.png)
![Bildschirmfoto vom 2021-03-18 09-02-00-1](https://user-images.githubusercontent.com/54942072/111594127-f47e6600-87ca-11eb-9607-3ce2fec0aff5.png)
If you just jump through an album and the forward button keeps jumping from one place to another, it feels strange.
A fixed range for the length of the song name could be created so that the length of the title does not affect the controls.

**Comment by xou816** [comment]
Indeed that's not great, thanks for the report!

**Comment by xou816** [comment]
Fixed, will be in next version! I removed the clamp alltogether
