### ISSUE TITLE
[Feature] Downloading Music

### ISSUE THREAD

**Issue by Zaedus** [xou816/spot#170]
I'm not even sure if this is remotely possible or allowed by Spotify TOS, but it would be absolutely amazing to be able to download music. My school blocks Spotify, and I'd love to use this client more since it has a lot of potential, and I love removing all the bloat of the official Spotify client.

Btw if it wasn't already obvious, I really love this project, and am always interested in seeing its progress.

**Comment by xou816** [comment]
Thanks for the kind words :)

I don't think librespot wants to support offline playback and song downloading (can't find the relevant issue atm), that would be too dangerous for the project -- that'd be asking for trouble with Spotify :/

**Comment by ispanos** [comment]
Hello. I just started having issues with the spotify flatpak and decided to try out Spot. IMHO you have created a better looking app than the official.

> offline playback and song downloading 

Just to make sure I understand, there is no way to cache songs for offline playback, without legal trouble?
