### ISSUE TITLE
Connection Restored after longer inactivity yields empty playlist

### ISSUE THREAD

**Issue by Nipsi** [xou816/spot#175]
**Describe the bug**
After not playing or doing anything for a longer period of time, selecting a playlist yields a blank page with a popover "Connection Restored (x)". The playlist only gets loaded after returning to the overview page and clicking on the playlist again.

**To Reproduce**
1. Idle for a while
2. Click on some playlist
3. Observe no playlist displayed and "Connection Restored" popover

**Expected behavior**
It would be great if the playlist gets automatically reloaded when dismissing the popover

**General information:**
 - Distribution: Pop!_OS 20.10
 - Installation method: flathub
 - Version: 0.1.11
---------
It's just a minor inconvenience, but I think improving this would make this already awesome app a bit better :)

**Comment by xou816** [comment]
Ahah, it annoys me too to be fair! I have yet to find a good way to handle this... but i'll work on it!

**Comment by xou816** [comment]
fixed in 0.1.13
