### ISSUE TITLE
No autoscrolling in "library"

### ISSUE THREAD

**Issue by kleinHeiti** [xou816/spot#178]
When an album is called up via the menu item "Library", a track list of the album is displayed.

In the current version of Spot, the track list in the "Now Playing" view continues to scroll when the bottom of the list is reached.

In the Library view, the track list remains stationary and does not scroll. Wouldn't it be better if it scrolled here too?

**Comment by kleinHeiti** [comment]
I have just seen that the playlist view does not scroll either...

**Comment by xou816** [comment]
Hi! Thanks for the report :)

I am not sure I understand. There's a scrollbar visible on your screenshot in your other issue for instance: https://github.com/xou816/spot/issues/179

Or perhaps you are referring to the autoscrolling behaviour? (ie when a song that plays isn't visible, the Now playing views automatically scrolls it into view).

**Comment by kleinHeiti** [comment]
sorry for not being precise.

I was indeed referring to the _autoscroll_ function

**Comment by xou816** [comment]
No worries! I was not sure whether that'd be okay to have this behaviour everywhere, but sure, this can be enabled :) if someone wants to have a look, it's a simple matter of implementing this for the relevant views: https://github.com/xou816/spot/blob/master/src/app/components/playlist/playlist.rs#L21

I'll have a look later otherwise!

**Comment by kleinHeiti** [comment]
I would love to help, but unfortunately I have no programming skills at all (the last time I programmed was in school with Turbopascal....  maybe ...  er... a few years ago.

But I can keep looking for errors. I'm reasonably good at it :o)

**Comment by xou816** [comment]
Ahah no worries, bug reports are very helpful!

**Comment by xou816** [comment]
Changed in 0.1.14 :)
