### ISSUE TITLE
No sidebar despite wide window

### ISSUE THREAD

**Issue by kleinHeiti** [xou816/spot#179]
I noticed that the sidebar ("Library, Playlists, Now Playing") is not displayed for an album. 
![Picture1](https://user-images.githubusercontent.com/54942072/112437748-8f38f080-8d47-11eb-9742-c8c3c29a2959.png)
For another album, the behaviour is as expected.
![Picture2](https://user-images.githubusercontent.com/54942072/112437766-95c76800-8d47-11eb-9c84-63057968927a.png)
I have the feeling that the album title has something to do with it (it is quite long in the example).

**Comment by xou816** [comment]
Hi, thanks for the report!

Indeed the title is probably requesting too much space! :/

**Comment by xou816** [comment]
Changed it a bit in 0.1.14, seems to be doing the trick so far!
