### ISSUE TITLE
Does not support alternative login methods

### ISSUE THREAD

**Issue by kdwk** [xou816/spot#19]
Does not support logging in through Facebook or Apple, etc.

**Comment by xou816** [comment]
Hi :)
Most of this project is made possible thanks to librespot, and librespot doesn't currently support social login. I don't have the skills or time to implement this myself either, I am sorry! Besides, there are many other features I'd like to work on before improving authentication.

**Comment by horvbalint** [comment]
@xou816 I just visited librespot's documentation and it does support facebook login now! If I try to implement it into Spot, is there a chance that it will be merged or would it be just wasted time? I am absolutely not sure if I can implement it as I am a JavaScript dev with some Rust and very little GTK experience, but would love to try.
