### ISSUE TITLE
UI issue with long playlists/queues

### ISSUE THREAD

**Issue by mikeyh30** [xou816/spot#191]
**Describe the bug**
Circle indicating position in song is underneath the darker playlist UI element.

**To Reproduce**
1a. Add a few albums to the queue.
1b. Alternatively, go to a long playlist.
2. Wait for time circle to move across until it is in line with the long queue/playlist.
3. See that the circle is obstructed, as in attached screenshot.

**Expected behavior**
I expect the circle element to be on top of other elements.

**Screenshots**
![Screenshot from 2021-04-13 13-39-48](https://user-images.githubusercontent.com/31144656/114553798-ef8fc380-9c5d-11eb-94fe-ebefa18769ed.png)

**General information:**
 - Distribution: Ubuntu 20.10
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.13
 - Device used [e. g. desktop, phone...]: Laptop

**Comment by xou816** [comment]
Hi, thanks for the report! This is the same issue as #165 but yours is more detailed, I'll close mine :D
