### ISSUE TITLE
[Feature] Gapless playback

### ISSUE THREAD

**Issue by Taeon** [xou816/spot#193]
Currently, if you're listening to a playlist or album with continuous audio -- for example, a live album or DJ mix set -- there is a very brief, but audible, gap between tracks. Spotify itself supports gapless playback -- is there any chance that Spot might support this in future?

Thanks for the great work, BTW.

**Comment by xou816** [comment]
Hi! :) This should be possible; librespot allows preloading tracks. Might be worth a look!
