### ISSUE TITLE
Now Playing page is displayed above the progress bar

### ISSUE THREAD

**Issue by laurinneff** [xou816/spot#194]
**Describe the bug**
The Now Playing page is displayed above the progress bar

**To Reproduce**
1. Play any song
2. Go to Now Playing
3. Move the progress bar past the sidebar
4. See how the part of the progress bar is covered

**Expected behavior**
The progress bar should be on top

**Screenshots**
![image](https://user-images.githubusercontent.com/29987831/115434957-9ef20a80-a209-11eb-83c9-ae1e5e8f8205.png)

**General information:**
 - Distribution: Arch
 - Installation method: AUR (spot-client package)
 - Version: 0.1.13
 - Device used: Laptop

**Comment by xou816** [comment]
Hey there, thanks for the report! This bug is already being tracked here: #165
