### ISSUE TITLE
Clicking track number doesn't trigger play

### ISSUE THREAD

**Issue by Taeon** [xou816/spot#196]
**Describe the bug**
In a track list, you can click anywhere on the track and it will play -- except the track number. 

**To Reproduce**
1. Go to any track listing
2. Click on the number to the left of any track that isn't currently playing
3. ...track does not play

**Expected behavior**
The track should play.

**General information:**
 - Distribution: Ubuntu 20.04
 - Version: 0.1.13
 - Device used: desktop

**Comment by 17steen** [comment]
It seems to have to do with the hidden checkbox on top of it.
       https://github.com/xou816/spot/blob/2252301bdec1bf65295af9d3a0a52ef31ca77148/src/app/components/playlist/song.rs#L76

**Comment by 17steen** [comment]
![image](https://user-images.githubusercontent.com/43650869/115964037-c8b97300-a522-11eb-9a37-8a6306a26b26.png)
if you remove the CSS, the checkbox is actually above the label, which may be why it intercepts the click(?)

**Comment by 17steen** [comment]
![output](https://user-images.githubusercontent.com/43650869/115966451-e6400a00-a52d-11eb-9999-c175866c1fa2.gif)
note that the checkbox also doesn't work in selection mode

**Comment by xou816** [comment]
Hi! Thanks for the report and for taking the time to dig into this issue! :)

Indeed, the checkbox is causing the issue.

Ideally, I'd like the checkbox to act purely as an indicator, and the let the events bubble up to the parent row. I tried a couple things but didn't actually get to do it properly :/ probably something I'm missing in the Gtk event model. 

An alternative would be to connect the checkbox to the same callback as the row -- but I'd rather avoid that if I can for simplicity/

**Comment by xou816** [comment]
Fixed in 0.2.0
