### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by modzilla99** [xou816/spot#204]
Hey there,

since I'm in love with your project I'd love to give back to you by donating. I would also contribute with translations, but since I'm only able to speak English and German someone's always quicker than me! :)

Oh and yes if I'm allowed to ask, I would love to see support for having a bigger album picture, like the original Spotify client does as well as being able to adjust the loudness right in the app, so that I don't need to use the settings app when I'm in a conference or whatever.

Thank you very much for this awesome project!

Best regards!
modzilla

**Comment by xou816** [comment]
Hi :) 

Well thanks for the kind words! It's very much appreciated :)

I think someone asked before, and well, I haven't changed my stance on it; I'm only semi-regularly working on the project, I would feel bad being paid for something I can't quite give dedicated time to.

Also this project isn't actually that much; it's made possible by a couple of other fantastic projects, which probably need more resources than this one! I couldn't find donation links for librespot, but you could have a look at projects such as [gtk-rs](https://opencollective.com/gtk-rs) or [GNOME](https://www.gnome.org/donate/) if you feel like giving some money :) But thanks!

As for your other points: feel free to open dedicated issues! Can't promise I'll work on them, but it's worth knowing what people would like from the app (I think there might be an issue already for volume control)

**Comment by olof-nord** [comment]
This project is just the best. Everytime I drop by there is always a nice reply and I genuinely feel you care for the community @xou816. Amazing work here

**Comment by modzilla99** [comment]
> Well thanks for the kind words! It's very much appreciated :)

You're very welcome!

> I think someone asked before, and well, I haven't changed my stance on it; I'm only semi-regularly working on the project, I would feel bad being paid for something I can't quite give dedicated time to.

It's your call!

> Also this project isn't actually that much; it's made possible by a couple of other fantastic projects, which probably need more resources than this one! I couldn't find donation links for librespot, but you could have a look at projects such as [gtk-rs](https://opencollective.com/gtk-rs) or [GNOME](https://www.gnome.org/donate/) if you feel like giving some money :) But thanks!

That's very true they as well deserve donations! Since I use gnome every day I should definately give them some donations!
