### ISSUE TITLE
Problems with MPRIS seek

### ISSUE THREAD

**Issue by Douile** [xou816/spot#205]
#188 bugs

Seeking backwards via MPRIS doesn't work. ("Could not parse position") this is because the offset of the seek, is cast to u32 instead of staying as i32.
^ Sorry about this can't believe I didn't think to test with negative seek

@xou816 reports seek not working (need to look into more)

Could potential try to report track id as a DBUS object to silence the warning about reporting as a string.

**Comment by Douile** [comment]
Documentation about the trackid
> The mpris:trackid attribute must always be present, and must be of D-Bus type "o". This contains a D-Bus path that uniquely identifies the track within the scope of the playlist. There may or may not be an actual D-Bus object at that path; this specification says nothing about what interfaces such an object may implement. 

https://specifications.freedesktop.org/mpris-spec/latest/Track_List_Interface.html#Mapping:Metadata_Map

**Comment by xou816** [comment]
Again, no worries, and thanks for the very quick fix, looking into it!

**Comment by Douile** [comment]
The seek is was fixed, when #206 was merged.
I'm closing this as I don't think reporting trackid as a String instead of DBUS object is an issue at this time.
