### ISSUE TITLE
[Feature] Lyrics using Musixmatch API (or other)

### ISSUE THREAD

**Issue by jtraulle** [xou816/spot#226]
Hello,

First of all, thanks for this clean and sleek UI. Really glad to be able to use a good looking GTK app :slightly\_smiling\_face: 

I would be great to be able to get the lyrics of the currently playing song (for example using the Musixmatch API)

*   [https://playground.musixmatch.com/](https://playground.musixmatch.com/)
*   https://developer.musixmatch.com/documentation/api-methods

**Comment by ondras12345** [comment]
Disclaimer: I'm just a random user.
You can use an application like `osdlyrics`. It finds out what is currently playing through MPRIS and displays synced lyrics.
In my opinion, the music player itself should not need to handle this.
However, you need to somehow get the `.lrc` files that contain not only the text, but also timing information. [python-musixmatch](https://github.com/hudsonbrendon/python-musixmatch#track-snippet-get-1) looks promising, maybe I'll try it.

**Comment by xou816** [comment]
Hi there! Thanks for the kind words :)

I'd agree with @ondras12345 I'd rather not have to implement this myself -- feels like it's beyond the scope of making a simple Spotify client!

But I find it very valuable to document these additional tools that play well with MPRIS and therefore spot -- might be worth adding it to the README. Similarly we should probably document tools that cover other use cases, such as scrobbling #85

**Comment by laurinneff** [comment]
Official Spotify (at least on Android) now has this, any chance for this to be reconsidered? Reading the code from [another project](https://github.com/raitonoberu/sptlrx/blob/master/spotify/spotify.go) which does have lyrics, this is the API call:

https://spclient.wg.spotify.com/color-lyrics/v2/track/{trackId}

**Comment by jannuary** [comment]
I feel it's best we stay as a music app first and foremost and I think there's definitely an opportunity for an app that uses Musixmatch or Spotify (which are pretty much the same thing) lyrics synced to whatever's playing on mpris independent of actually listening through Spotify.

**Comment by todoneunl** [comment]
I think this is a really great app! Only important thing missing compared to the official Spotify app are lyrics. 🤷🏻 Other options (like osdlyrics) doesn't seem to work for me (Ubuntu 23.04). 😢
