### ISSUE TITLE
Tie Ctrl-F shortcut to "Search" or "Find"

### ISSUE THREAD

**Issue by NoTuxNoBux** [xou816/spot#231]
(I removed the template since it's not a bug.)

It would be neat if the Ctrl-F keyboard shortcut could be bound to expanding and focusing the search field for quicker keyboard navigation.

**Comment by NoTuxNoBux** [comment]
Apologies, this is a duplicate of #32, I should have searched better!

**Comment by xou816** [comment]
Uh, forgot about that issue actually :)

I took a different approach, but it doesn't seem to be very discoverable! If you start typing anything, you'll enter search mode; shortcuts use modifier keys (Alt + N and Alt + P for instance)

**Comment by NoTuxNoBux** [comment]
Thanks for the response; that's certainly sufficient for me, too!

I was also thinking about discoverability, but then again Nautilus and other GNOME apps also use this behavior and don't seem to make it very discoverable. Maybe keeping the current behavior and still tying `Ctrl + F` to the search field would work? This is also what Nautilus seems to do.

**Comment by xou816** [comment]
Fair! I think you're right that both ways should be possible!

**Comment by dreua** [comment]
> If you start typing anything, you'll enter search mode;

That doesn't work for me (X11, Fedora 35, Flatpak). Ctrl + F would be a huge help in this case.

**Comment by xou816** [comment]
pushed somehting that should help on development!
