### ISSUE TITLE
Show album name in playlists and queue

### ISSUE THREAD

**Issue by NoTuxNoBux** [xou816/spot#232]
(I removed the template since it's not a bug.)

Currently just the artist name and track title are shown in playlists or your queue. It would be neat if the album name could also be shown somewhere.

My use case is that I often add whole albums to playlists or the queue as a backlog, and it's useful to know when an album has ended, especially if multiple albums were made by the same artist.

**Comment by xou816** [comment]
closing for now given the contribution from abegert :)
