### ISSUE TITLE
Cannot view more than 50 songs in an album

### ISSUE THREAD

**Issue by Prince781** [xou816/spot#240]
**Describe the bug**
Scrolling is limited to 50 songs in an album.

**To Reproduce**
1. Browse any album with more than 50 songs.
2. See that you can only scroll 50 songs.

**Expected behavior**
I should be able to see all the song sin the album.

**Screenshots**

**General information:**
 - Distribution: EndeavourOS Linux x86_64
 - Installation method [e. g. built from source, installed from Flathub...]: built from source (AUR)
 - Version [e.g. 0.1.0]: 0.1.14
 - Device used [e. g. desktop, phone...]: desktop

**Additional context**
I'm using a premium account.

**Comment by xou816** [comment]
I feel dumb, we handled this issue with playlists before but did not think of albums! Thanks for the report!

**Comment by Douile** [comment]
Lol, didnt think 50 song albums existed

**Comment by Prince781** [comment]
A number of Spotify albums for classical music have more than 50 songs, especially if it's an opera or a collection of a composer's works.
