### ISSUE TITLE
config.rs is modified with every build

### ISSUE THREAD

**Issue by perrin4869** [xou816/spot#267]
This is not a bug per-se, but a nitpick about the workflow.
I added spot to my [dotfiles](https://github.com/perrin4869/dotfiles/tree/master/deps) setup. However, running meson on it will cause `src/config.rs` to change with contents to my local env, and this results in changes to the git submodule and my own repo.
If you could add this as a future enhancement it would this use-case slightly better.

**Comment by perrin4869** [comment]
Actually it kinda looks like that file was mistakenly added to the repo :)

**Comment by xou816** [comment]
Hi! Thanks for the report! I agree with you, I actually tried removing it+git ignoring it in the past but more trouble ensued IIRC, rustfmt needed config.rs to exist I think (or was it something else)? Long story short, I did not want to dig into it as it was a fairly minor annoyance, but it's still anoying me every now and then, I should take the time :)

**Comment by bilelmoussaoui** [comment]
> rustfmt needed config.rs to exist I think (or was it something else)? 

That's probably true, you can just `touch src/config.rs` to slient rustfmt, or ignore it on main.rs directly :-)

**Comment by xou816** [comment]
Oh I see, it probably just recognizes the use statements in order to map out the files to analyse, but I don't actually need to have it compile? I'll try this out thanks! :)

**Comment by bilelmoussaoui** [comment]
Yes rustfmt doesn't try to build your project

**Comment by xou816** [comment]
Should be fixed, thanks! :)

**Comment by perrin4869** [comment]
This works perfect, thanks!!
