### ISSUE TITLE
Album info popup window breaks repositioning of the main window

### ISSUE THREAD

**Issue by ondras12345** [xou816/spot#273]
**Describe the bug**
It looks like there's something wrong with the positioning of the album info pop-up window (added in https://github.com/xou816/spot/pull/268).
When I open some album's info and try moving the main Spot window by dragging it's titlebar, the pop-up window jumps to the right edge of my rightmost monitor.
When I hold down `Super` while moving the main window, everything seems to work just fine.

**To Reproduce**
1. Open some album's info
2. Try to reposition Spot's main window by dragging it's titlebar

**Expected behavior**
Either it should not be possible to reposition the main window by dragging it's titlebar at all (as it is in case of the "About" pop-up), or repositioning of the main window should affect the position of the album info pop-up.

**Screenshots**
![Spot-album-info-move](https://user-images.githubusercontent.com/44524735/129889329-35f3335b-93c2-43da-8820-998962d4c1c2.gif)

**General information:**
 - Distribution: Ubuntu 20.04.2 LTS (GNOME 3.36.8)
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.16
 - Device used [e. g. desktop, phone...]: desktop

**Comment by xou816** [comment]
Thanks for the very detailed report! :) I think I fixed on the [Gtk4 branch](https://github.com/xou816/spot/tree/gtk4/main) when I ported the latest changes there, I could have a look and backport later

**Comment by xou816** [comment]
Should be fixed in 0.2.0

**Comment by ondras12345** [comment]
Yes, it is working correctly in 0.2.0. Thanks!
