### ISSUE TITLE
[Feature Request] Like option for the songs.

### ISSUE THREAD

**Issue by CleoMenezesJr** [xou816/spot#284]
![image](https://user-images.githubusercontent.com/54215258/130721106-c6515c6b-5985-4f69-89a3-d58473be70b0.png)

**Comment by kalikiana** [comment]
> Absolutely, and with Gtk4 I feel more confident in implementing large lists -- such as the liked songs list. Will have a look!

The _liked songs_, aka **saved tracks** work fine for me in the three digits - unfortunately they are never refreshed and there's no way to add any.

**Comment by xou816** [comment]
I have a WIP branch somewhere that I should push!

**Comment by szbergeron** [comment]
> I have a WIP branch somewhere that I should push!

What work do you think would be required to rebase that branch on current main?

**Comment by xou816** [comment]
Sorry forgot about that, will upload that in a minute!

I got somewhat stuck because I wanted to clean up stuff related to updating list models properly, but it can be done without it!

**Comment by xou816** [comment]
Here it is : https://github.com/xou816/spot/compare/like-tool
