### ISSUE TITLE
Uneven spacing between song number and title

### ISSUE THREAD

**Issue by jacksongoode** [xou816/spot#291]
Spacing should likely be fixed and accommodate up to 3 numbers (I doubt there will be anything that holds 999+ songs).

![image](https://user-images.githubusercontent.com/54308792/131164223-6c21e886-d099-484b-a5b4-fa5aee49d5dc.png)

**Comment by xou816** [comment]
Oh right! forgot about this; there was a proposed fix for that in #208 that never was finalized.

**Comment by xou816** [comment]
(closed as duplicate)
