### ISSUE TITLE
Spot doesn't login automatically and requires mail and password if your computer is set to auto-login 

### ISSUE THREAD

**Issue by idontlikecaesar** [xou816/spot#292]
Other apps have no problem with that. Maybe save the credentials in app instead of GNOME Keyring?

**Comment by xou816** [comment]
Duplicate of #274 

Long story short, I don't feel good about storing username/password in plain on the filesystem, so right now only GNOME Keyring is supported, but feedback is welcome! Hopefully we can find some way to store credentials somewhat safely.

**Comment by xou816** [comment]
Closing this one so discussion can be continued in #274
