### ISSUE TITLE
[Feature Request] Use extra mouse buttons for back and forward navigation.

### ISSUE THREAD

**Issue by tur1ngb0x** [xou816/spot#299]
**Description**
It would be nice to have a feature which detects "mouse4" and "mouse5" button events for "back" and "forward" navigation inside the app. This would result in faster navigation and less mouse movement.

**General information:**
 - Distribution: Ubuntu 20.04.3 LTS
 - Installation method: Flathub (User)
 - Version : 0.2.0
 - Device used: Laptop + External Mouse
 
**App Information**
 ```
$ flatpak info dev.alextren.Spot
Spot - Spotify Client for the GNOME desktop

          ID: dev.alextren.Spot
         Ref: app/dev.alextren.Spot/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 0.2.0
     License: MIT
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 19.4 MB
     Runtime: org.gnome.Platform/x86_64/40
         Sdk: org.gnome.Sdk/x86_64/40

      Commit: 92d23006e4589bb5edf8d72a473a72dc4807a0c3b77802de098a8a22f9d1580a
      Parent: 618ab1618c617cfd3ccf6edd4c8514492a4bcce1003b614be431b52824b917b9
     Subject: Add --device=dri so GTK4 can use the GPU (eb40e907)
        Date: 2021-08-27 12:50:46 +0000

 ```

**Comment by jannuary** [comment]
This got merged upstream: [leaflet: Support back/forward mouse buttons ](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/38), so we can have this for free now.

**Comment by jannuary** [comment]
Or at least it would be, but leaflet swiping seems broken currently: 
![Kooha-11-15-2021-11-27-45](https://user-images.githubusercontent.com/27908024/141722536-4fb3c533-d1f5-4f2c-9ae5-5c9d8814288b.gif)

**Comment by xou816** [comment]
Something wrong with https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/property.Leaflet.can-navigate-back.html maybe, not sure we've enabled it

**Comment by jannuary** [comment]
> Or at least it would be, but leaflet swiping seems broken currently: ![Kooha-11-15-2021-11-27-45](https://user-images.githubusercontent.com/27908024/141722536-4fb3c533-d1f5-4f2c-9ae5-5c9d8814288b.gif)

This is with can-navigate-back:true.

**Comment by xou816** [comment]
Oh of course nevermind, we can't do that! going back has to operate on the stack switcher not the leaflet

**Comment by jannuary** [comment]
I was pondering how to make swipes work, and was instructed that we'd need two nested leaflets - one with sidebar and "library" as children, and the other with the details screen as a child and `can-unfold=false`.
![](https://media.discordapp.net/attachments/790615150389493812/917973649867296878/Kooha-12-08-2021-09-51-27.gif)

**Comment by jannuary** [comment]
Trying to make the swipes work, but it would seem it would seem that would require to rework quite a bit of navigation routine:
![Kooha-01-06-2022-12-30-59](https://user-images.githubusercontent.com/27908024/148333382-ccd8db41-e452-4a89-8fbf-a58fd849c6c6.gif)
