### ISSUE TITLE
Unable to play podcasts.

### ISSUE THREAD

**Issue by CleoMenezes** [xou816/spot#300]
**Describe the bug**
Can't play podcasts.

**To Reproduce**

1.  Create/add a playlist with podcasts episodes.
2. Try to play it.

![Kooha-2021-09-04-23_33_31](https://user-images.githubusercontent.com/54215258/132114123-e5130460-7992-498d-86a1-bf99bb324ddf.gif)

**Comment by ondras12345** [comment]
Duplicate of https://github.com/xou816/spot/issues/95

**Comment by xou816** [comment]
Thank you ondras, really appreciate that you help me sort through issues and questions :)
