### ISSUE TITLE
Spot doesn't display content after login

### ISSUE THREAD

**Issue by jsparber** [xou816/spot#304]
**Describe the bug**
After login no songs or anything is loaded. I did try first to login without premium (which expectantly failed)  and then I enabled three months of premium trail.

**To Reproduce**
1. Login
2. Nothing is loaded

**Expected behavior**
I would expect to have access to the music library 

**Screenshots**
![image](https://user-images.githubusercontent.com/1911029/132223057-8cce6ea8-4e1c-449c-9385-85578911b78b.png)

**General information:**
 - Distribution: Fedora
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.2.0
 - Device used [e. g. desktop, phone...]: desktop

**Additional context**
Terminal output:

```
flatpak run dev.alextren.Spot

** (process:83306): WARNING **: 15:13:15.929: Error writing credentials to socket: Error sending message: Broken pipe

(process:2): Gtk-WARNING **: 15:13:15.930: Locale not supported by C library.
	Using the fallback 'C' locale.
bitrate: Bitrate160
using pulseaudio
```

**Comment by xou816** [comment]
Hi! Is this a new account that perhaps has no albums in the library? Does search work?

**Comment by jsparber** [comment]
> Hi! Is this a new account that perhaps has no albums in the library? Does search work?

Yes the search works, and my library is empty (now i added something). 

I think it would be good to have a text saying that the user needs to add stuff to the library and how to add them.

**Comment by jsparber** [comment]
i created an issue for the boarding experience https://github.com/xou816/spot/issues/305. Feel free to close this issue.

**Comment by xou816** [comment]
Perfect :) thanks!
