### ISSUE TITLE
Better summary

### ISSUE THREAD

**Issue by bertob** [xou816/spot#306]
The current summary "Spotify Client for the GNOME desktop" isn't great (capitalization, mentions target environment).

I'd suggest something like "Listen to music on Spotify"".

More general guidance here: https://gitlab.gnome.org/GNOME/Initiatives/-/wikis/App-Metadata

**Comment by xou816** [comment]
Just saw your blog post yesterday and thought I had quite a few of the don'ts to fix, thanks for the report I'll have a look! :)
