### ISSUE TITLE
Spotify keeps sending email every time Spot is launched

### ISSUE THREAD

**Issue by aldonogueira** [xou816/spot#307]
**Describe the bug**
The first time I logged into Spot using my spotify account I received an email telling me about it. OK. But then I launched Spot the next day and received another email. And again. And again...

**To Reproduce**
1. Log in to Spot using your premium account
2. You may receive an email from spotify alerting someone used your account
3. Close the application
4. Launch it again
5. BUG: Another email is sent

**Expected behavior**
Just one email is received

**General information:**
 - Distribution: Debian 11
 - Installation method: flathub
 - Version: 0.2.0

**Additional context**
The email looks like this:

> Subject: New login to Spotify
> New login to Spotify
> 
> We noticed you logged in from a new device. If this was you, there’s nothing for you to do right now. 
> 
> Location Brazil
> Time September 8, 2021 at 2:27:57 PM BRT
> ...

**Comment by xou816** [comment]
I agree it's annoying, but I have yet to find a simple solution. Please take the time to search [existing issues](https://github.com/xou816/spot/issues?q=new+login+email+) next time though :)

**Comment by aldonogueira** [comment]
You are right. Sorry. I looked at the open bugs list, but I somehow missed this one.

**Comment by xou816** [comment]
No worries, it happens :) if anything duplicate reports help identify issues that matter to people!
