### ISSUE TITLE
Can't build: Dependency "libadwaita-1" not found

### ISSUE THREAD

**Issue by uninhm** [xou816/spot#308]
![image](https://user-images.githubusercontent.com/62044675/132960482-77c70050-0cc7-4cab-86c6-0a370442c594.png)
As you can see in the image, I have libadwaita installed.

**Comment by jtojnar** [comment]
What distro is that? Do you also have the dev package installed?

**Comment by uninhm** [comment]
You are right, I missed the dev pkg

**Comment by uninhm** [comment]
> error: no matching package named `async-std` found

Now I get this

**Comment by xou816** [comment]
Have you used -Doffline=false during the configure step? I think you have but just to be sure
