### ISSUE TITLE
poor font rendering

### ISSUE THREAD

**Issue by caetano-m** [xou816/spot#309]
Some artefacts are visible in some screens:
![image](https://user-images.githubusercontent.com/71804353/132967026-0759d790-6122-4057-a55b-f458b5aa3ff3.png)

**General information:**
 - Distribution: Fedora 34
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.2.0
 - Device used [e. g. desktop, phone...]: Desktop

Also thank you for your work, this app is great!

**Comment by xou816** [comment]
Hi! Thank you for the kind words :)
There are a couple reported issues/differences with font rendering in Gtk4 at the moment I believe! But I'm not sure this one has been reported

**Comment by xou816** [comment]
Might be worth checking if it happens with and without hardware acceleration, I think I encountered the issue with hardware acceleration (AMD card) on one of my PCs

**Comment by caetano-m** [comment]
Hello, thanks for the answer :)
I use some other GTK4 apps, they exhibit other font problems but don't have the artefacts, they are usually blurry. The problems with GTK4 usually go away when I change the font scaling. 
I have an Intel UHD GPU, and I use wayland. I don't know how disable hardware acceleration, but if there is some sort of guide I could follow, I can check it!

**Comment by jannuary** [comment]
@caetano-m could you try building the branch in #346 and see if the issue persists there for you?

**Comment by xou816** [comment]
closing since this is an upstream issue
