### ISSUE TITLE
New Frieday Msuic playlist does not open

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [xou816/spot#311]
**Describe the bug**
each time i try to open playlist i get error message 

**To Reproduce**
1. open spot
2. click on playlists
3. go to new friday music playlist

**Expected behavior**
the playlist shows inside the app

**Screenshots**
![image](https://user-images.githubusercontent.com/28893833/133778686-7fb6a096-0df5-4b76-a263-663e0695e78f.png)

**General information:**
 - Distribution: Arch linux
 - Installation method [e. g. built from source, installed from Flathub...]: AUR
 - Version [e.g. 0.1.0]: 0.2.0
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
```
[src/api/cached_client.rs:204] e = Error("data did not match any variant of untagged enum FailibleTrackItem", line: 1976, column: 5)
Error: ParseError(Error("data did not match any variant of untagged enum FailibleTrackItem", line: 1976, column: 5))
```
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
```

**Additional context**

**Comment by xou816** [comment]
Hi! Thanks for the report! Would you be able to identify the relevant playlist cache file in .cache/spot/net and share it? Or is there a way to copy that playlist so it can be shared publicly maybe? Thanks!

(I need to improve logging :( )

**Comment by EsmailELBoBDev2** [comment]
the playlist is public made by spotify https://open.spotify.com/playlist/37i9dQZF1DX4JAvHpjipBk

**Comment by EsmailELBoBDev2** [comment]
[playlist_37i9dQZF1DX4JAvHpjipBk.pdf](https://github.com/xou816/spot/files/7189773/playlist_37i9dQZF1DX4JAvHpjipBk.pdf)
(rename file back to `.json` thanks to github upload limit....)

**Comment by EsmailELBoBDev2** [comment]
Also i have noticed that when i changed my profile login data, and got back to spot so i can logout and login. the logout button disappears and the app panic (just say wrong credentials) and no way to rest it so i can login back.

so make spot save data in a file even if it's random, just to let spot knows when i deleted them so i can re-login or something

**Comment by ondras12345** [comment]
See https://github.com/xou816/spot/issues/129
Delete "Spotify Credentials" in Seahorse.

**Comment by xou816** [comment]
Forgot about #129 😮 
Thanks for the JSON I'll have a closer look tomorrow!

**Comment by EsmailELBoBDev2** [comment]
@ondras12345 i do not have seahorse... 
![image](https://user-images.githubusercontent.com/28893833/133929142-af444a67-9b69-47d2-a5eb-6d502f02d54c.png)

@xou816 Your welcome :)

**Comment by ondras12345** [comment]
Try `secret-tool search --all spot_credentials yes`. See https://wiki.archlinux.org/title/GNOME/Keyring
If you find a secret named "Spotify Credentials", clear it. See `man secret-tool`.

**Comment by EsmailELBoBDev2** [comment]
oh, new thing learned today... 
I cleared it thanks for the tip (for future me, the command is `secret-tool clear spot_credentials yes`)
