### ISSUE TITLE
[Flatpak] Translations not working

### ISSUE THREAD

**Issue by wtpckl** [xou816/spot#312]
**Describe the bug**
When using the flatpak package, translations do not work

**To Reproduce**
1. Install the flatpak package with ```flatpak install flathub dev.alextren.Spot```
2. Launch the application using ```LANG=nl_NL.UTF-8 flatpak run dev.alextren.Spot``` (Any locale will work, since GLib falls back to the ```C``` locale)
3. See that the application is not translated

**Expected behavior**
The application is translated properly to the chosen locale.

**Screenshots**
![Screenshot from 2021-09-17 14-05-13](https://user-images.githubusercontent.com/19992900/133780005-41568f5e-4bad-4bf5-bdb1-c769fec7ccfd.png)

**General information:**
 - Distribution: Arch Linux (kernel: `Linux 5.14.2-arch1-2`)
 - Installation method: Flatpak (Flathub)
 - Version: Spot 0.2.0
 - Device used: Laptop

**Stack trace:**
Without locale change:
```sh
$ flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot

(process:2): Gtk-WARNING **: 14:14:00.895: Locale not supported by C library.
	Using the fallback 'C' locale.
bitrate: Bitrate160
using pulseaudio
```

With locale change:
```sh
$ LANG=nl_NL.UTF-8 flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot

(process:2): Gtk-WARNING **: 14:08:12.932: Locale not supported by C library.
	Using the fallback 'C' locale.
bitrate: Bitrate160
using pulseaudio
```

**Additional context**
When using the [AUR package](https://aur.archlinux.org/packages/spot-client/) the locale switching does work. See the below screenshot.
![Screenshot from 2021-09-17 14-10-39](https://user-images.githubusercontent.com/19992900/133780599-ba6f33b7-eedc-4678-921e-40d75c9faa63.png)

**Comment by ondras12345** [comment]
`LANGUAGE=cs_CZ flatpak run dev.alextren.Spot` works for me.

**Comment by wtpckl** [comment]
After testing on an Ubuntu VM and an Arch Linux VM and it working fine, it seems something is broken on my setup. Sorry for bothering you with this.

**Comment by xou816** [comment]
No worries @wtpckl! I need to find it but I remember sometimes flatpak needs to be configured to support other languages!

**Comment by xou816** [comment]
Ah I think that's the one: https://github.com/xou816/spot/pull/207#issuecomment-834294907

**Comment by wtpckl** [comment]
Thanks, `flatpak update --subpath=nl dev.alextren.Spot.Locale` fixed my problem. (I don't know if the gnome platform locale did anything, but I also updated that to be sure)

I'm running a weird setup with `LANG=en_US.UTF-8`, but some things like `LC_CURRENCY=nl_BE.UTF-8` to format stuff in a way I'm more familiar with. I wanted to test Spot in Dutch to help with translation, but I guess translations don't get downloaded automatically. (I'm running the flathub version just to get some context for translations, not to actually test them)

**Comment by xou816** [comment]
Glad it worked :) 

Right, translations don't get added automatically, there are a few things to do manually after you export the po file from POEditor. I can start a branch later if you need help with testing your contribution!
