### ISSUE TITLE
Get rid of the left navigation panel

### ISSUE THREAD

**Issue by juxuanu** [xou816/spot#325]
I've been trying to create a PR for this but I am still not comfortable with Rust and I failed miserably.

My idea is:
- Move "Library" and "Playlists" as tabs (what Gnome Software uses, ([take a look](https://149366088.v2.pressablecdn.com/wp-content/uploads/2021/08/GNOME-41-features-gnome-software.jpg)). 
- Make the "Now playing" view come from clicking on the current song.

**Comment by xou816** [comment]
Hi!

I'd advise against starting to work on large changes like this without discussing them first. I am not personally favorable to removing the sidebar, especially if we want to do stuff such as #287 :) eventually there'll be many more things here, and tabs wouldn't fit especially on mobile devices.

As for point 2: this is already implemented! Is it not discoverable? Might be worth opening an issue if the purpose of that button is not clear :/

**Comment by juxuanu** [comment]
I didn't see that issue.

What's the plan, then? If there is a design implementation decided, it'd be nice to know :)

Do you have any chat channel to discuss this stuff? A Matrix room maybe?

**Comment by xou816** [comment]
Sorry, I wasn't very clear. No design implementation is set in stone, and suggestions for change are welcome, but coming up with a large PR directly is risky -- it's within my rights not to accept it, or to request heavy changes to it, in which case it's not fun for either party. The decided design implementation is the current one unless a discussion leads to reconsidering it ;) 

(no Matrix room, I think Github is fine for now)

Back to the issue at hand: what is the motivation behind switching to tabs?
