### ISSUE TITLE
Failed to add UI from resource

### ISSUE THREAD

**Issue by g0rdonL** [xou816/spot#334]
**Describe the bug**
Spot doesnt launch after installation

**To Reproduce**
1. Install `spot-client` from aur
2. run `spot` in the terminal

**Expected behavior**
Spot client to launch

**General information:**
 - Distribution: Arch Linux x86_64 5.14.7-arch1-1
 - Installation method [e. g. built from source, installed from Flathub...]: AUR
 - Version [e.g. 0.1.0]: 0.2.0-1
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
(process:322239): Adwaita-WARNING **: 00:20:11.102: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(process:322239): Gtk-ERROR **: 00:20:11.111: failed to add UI from resource /dev/alextren/Spot/window.ui: .:98:48 Invalid property: AdwLeaflet.interpolate-size
fish: Job 1, 'spot' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by xou816** [comment]
Indeed, I could reproduce the issue, the latest version of libadwaita broke a few things it seems :/ I'll push a fix ASAP! Thank you for the report.

**Comment by xou816** [comment]
Thank you both :)
