### ISSUE TITLE
configure AP port

### ISSUE THREAD

**Issue by sei0o** [xou816/spot#337]
I live in a college dormitory where the network is heavily restricted. In other words, the firewall only accepts outgoing packets on port 80 and 443 while some Spotify access points use port 4070. For now, it seems Spot does not provide way to tell librespot which port is available so I cannot use Spot from my dormitory. 

This is what I see on login:
![image](https://user-images.githubusercontent.com/5410901/136655564-e36912ca-3984-4bfb-ac21-b8876950ae23.png)

librespot's `SessionConfig` has `ap_port` which allows us to designate which port to use (this is also the case for proxies). The `librespot` command uses this: `$ librespot -v -u someusername -p somepassword -n foobar --ap-port 443`. I wish Spot had this kind of configuration and suppose adding options in `gsettings` works. What do you think? I would love to make a PR if nobody is working on it.

**Comment by xou816** [comment]
This sounds perfectly reasonable :) you're welcome to submit a PR for this!
