### ISSUE TITLE
Increase size of search field

### ISSUE THREAD

**Issue by lightonflux** [xou816/spot#34]
The search field is very short. Many artist names or album titles are longer than the fields.

Example: 

If you are searching for "Lightspeed Champion" it is already too long. The text field should be wider. 

Search box compared to other apps:
1: spot
2: lollypop
3: nautilus

![Bildschirmfoto von 2021-01-25 16-57-49](https://user-images.githubusercontent.com/1377943/105730310-7e7a2300-5f2e-11eb-8747-a4f1e6e0eb2a.png)

**Comment by lightonflux** [comment]
Quick and dirty mockup: 

![](https://user-images.githubusercontent.com/1377943/105753027-5697b900-5f48-11eb-9061-e5562605b720.png)

Please note that there should be a max-width, so the filter button is not half a meter away (think large 4k screen) nor should it have a fixed size. Think phone like the pinephone.

**Comment by xou816** [comment]
Fixed in 0.1.4
