### ISSUE TITLE
Use standard list styling

### ISSUE THREAD

**Issue by jannuary** [xou816/spot#348]
Lists use this weird borderless style:
![image](https://user-images.githubusercontent.com/27908024/138382442-d5ac80b9-0acd-4a37-9e1c-7e99b149523b.png)
It would be better to use standard ~~.content~~ .boxed-list style class on these.

**Comment by jannuary** [comment]
> It would be better to use standard .content style class on these.

Of course, it's not that simple :(
![image](https://user-images.githubusercontent.com/27908024/138383594-3d33e4b6-4f64-49ef-b055-5ce039b88487.png)

**Comment by jannuary** [comment]
Getting somewhere for the album details: 
![image](https://user-images.githubusercontent.com/27908024/139530141-3d427ba9-3296-4862-833c-9f292ce5e1b3.png)
It's slightly broken though, probably due to it being a ListView and not a ListBox:
![image](https://user-images.githubusercontent.com/27908024/139530236-32ea38c8-5ddb-4bbd-af1b-8331cc96b488.png)

**Comment by jannuary** [comment]
.content is now explicitly unsupported for ListViews: [Misc. Boxed List Tweaks ](https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/321)

**Comment by xou816** [comment]
Oh :( too bad this is not supported. I hope an alternative will be provided in the future for ListViews :/

**Comment by xou816** [comment]
Maybe there's a way to emulate that style with [`set_show_separators`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.ListView.html#method.set_show_separators)

**Comment by xou816** [comment]
My own attempts did not amount to much, I think it might be better to wait a little until adwaita stabilizes

**Comment by jannuary** [comment]
This kinda almost works with show-separators and .card style (which is blocked by #358)
![image](https://user-images.githubusercontent.com/27908024/140681580-adbabe32-31cf-408c-bbf7-68fa9b6765d9.png)

**Comment by BrainBlasted** [comment]
In this case, I think listbox is the proper widget. Generally we also don't have scrolling within cards unless it's something like a textview.

**Comment by xou816** [comment]
These used to be listboxes, but we have to manage potentially very large lists -- not so much with albums, granted, but playlists for instance!
