### ISSUE TITLE
Improve Selection Mode

### ISSUE THREAD

**Issue by jannuary** [xou816/spot#354]
Selection mode has several issues:

- It is available everywhere, not just where it applies
- The widgets in the headerbar are kept as is, which is unexpected and leads to the user being able to leave the current screen without also cancelling selection mode
- The icons are off brand and confusing, it's not intuitive what ☑, - or + does here:
![image](https://user-images.githubusercontent.com/27908024/139424872-443199e6-c680-4420-a6fa-78a8ac94d5f1.png)
- The rows in queue aren't draggable, instead opting for awkward ˅/˄ buttons; playlists aren't reordeable at all (though i suppose it's a different issue)

Here's a mockup of my redesign proposal for the selection mode, based off Allan Day's Photos redesign:
![Selmode](https://user-images.githubusercontent.com/27908024/140286338-b0cb0f87-72ed-4aca-9d9e-5c26d6a3e40a.png)

**Comment by xou816** [comment]
Some of it is intentional -- like being able to search while a selection is active, so that you don't have to reenter selection mode again. Maybe there's a way this could be clearer! The selection mode being canceled is from a poor implementation of navigation, there's some work to do here as well. Ah well!

Maybe I should just drop this idea of being able to keep a selection active while browsing, but this is something that's always bothered me in most music players when building a new playlist for instance.

--

Something I'm wondering about: I really like the look of the action bar there, do you think it should cover the controls though?

**Comment by jannuary** [comment]
It does seem pretty niche to have selection mode on while browsing, so I don't think it's really worth it. 

> Something I'm wondering about: I really like the look of the action bar there, do you think it should cover the controls though?

I think it makes sense to not show playback controls while selecting - that's what Music does, for example.

**Comment by jannuary** [comment]
> I think it makes sense to not show playback controls while selecting - that's what Music does, for example.

Spotify too:
![Screenshot_20211031-230817_Spotify.png](https://user-images.githubusercontent.com/27908024/139592390-e88d912c-cefb-4a19-915c-1e7674efb330.png)

**Comment by xou816** [comment]
The mockups are really gorgeous, I'll try to get started on the selection tools part soon enough!

**Comment by xou816** [comment]
![image](https://user-images.githubusercontent.com/6277494/141382951-b6b5051f-c805-40c2-a118-7057b01293b0.png)

started working on this! I might actually work on the headerbars as I tackle this since I'll need to change them anyway :)

**Comment by xou816** [comment]
split headerbars are coming along! for now they work the same for all screens but we can eventually have a different one where needed!

![image](https://user-images.githubusercontent.com/6277494/141662000-553a7270-f0c5-468f-8580-29d6d32ce165.png)

![image](https://user-images.githubusercontent.com/6277494/141662006-d4545295-f166-49dc-b71a-28160ccde310.png)

search is uh all kinds of broken for now but that's okay!

**Comment by jannuary** [comment]
> search is uh all kinds of broken for now but that's okay!

If you mean that you can't use backspace, that's an upstream bug: [Keyboard input is broken (#4443)](https://gitlab.gnome.org/GNOME/gtk/-/issues/4443)
