### ISSUE TITLE
Some GTK themes are unsupported

### ISSUE THREAD

**Issue by pjautuvas** [xou816/spot#368]
Themes like Orchis and Adwaita Maia (Manjaro's variant of Adwaita) are not supported and Spot switches to the default light theme, which is not ideal at night.

**Comment by xou816** [comment]
Hi! Are you using the flatpak version? Are these themes installed with flatpak as well?

**Comment by pjautuvas** [comment]
Hi! I was using the snap version which had issues. Seems like AUR and Flatpak are perfectly fine.

**Comment by xou816** [comment]
Np, closing this for now then :)
