### ISSUE TITLE
Icons not showing up in the app

### ISSUE THREAD

**Issue by shahiljain** [xou816/spot#369]
OS: Pop OS 21,04
Gnome Version: 3.38.5
The Icons in the bottom row are missing.
![image](https://user-images.githubusercontent.com/75173792/141676096-a00a09c2-b737-4d4e-9e15-4dca400e131b.png)

**Comment by xRMG412** [comment]
I'm in the same environment and can't reproduce the issue.
Just switched to Pop OS recently :)

![image](https://user-images.githubusercontent.com/19354877/141883963-da35b617-1b0a-497e-bf10-38c75e2c7656.png)

**Comment by shahiljain** [comment]
I think the issue occurred because of a custom icon pack.
I changed the "Inherit =" in the index file of the theme (I added Pop to the list) for a different issue and it seemed to resolve this too.

**Comment by xou816** [comment]
Closing then if you don´t mind :)
