### ISSUE TITLE
Titlebar buttons are shown twice

### ISSUE THREAD

**Issue by alissonlauffer** [xou816/spot#381]
**Describe the bug**
While using titlebar buttons in the left side, they are shown twice. With a quick `git bisect` I've discovered that the issue has been introduced in https://github.com/xou816/spot/commit/2752dfa330e7263ecf81ea94c47bf21896db9a19.

**To Reproduce**
1. Open Tweaks app
2. Go to 'Window Titlebars'
3. Set titlebar buttons placement to left

**Expected behavior**
Titlebar buttons should be shown only once.

**Screenshots**
![image](https://user-images.githubusercontent.com/29029632/142970729-92d04557-44f8-4c7a-8631-a316dd1d290c.png)

**General information:**
 - Distribution: Arch Linux
 - Installation method: built from source
 - Version: latest git commit
 - Device used: desktop

**Comment by jannuary** [comment]
`show-start-title-buttons` is set to true on the right hand header, should be an easy fix though

**Comment by xou816** [comment]
this one is trickier than I thought: with the "mobile" layout, there is no easy way to toggle the visibility of the controls on the right hand header (we'd have to keep a reference to the leaflet I think, will try to think of something else)

**Comment by yavko** [comment]
![image](https://user-images.githubusercontent.com/15178513/149579167-62c0d185-9186-48f4-840b-e7fbf4226183.png)

Happens with new update for me aswell

**Comment by xou816** [comment]
I can't wrap my mind around it and I don't see how I can fix that honestly, I'd have to know somehow whether the use chose left or right window buttons and that's something I'd rather have libadwaita or gtk handle

**Comment by yavko** [comment]
> nestly, I'd have to know somehow whether t

Isn't libadwaita already handling that tho?

**Comment by xou816** [comment]
kind of, but there's no easy way to tell it my two headerbars (split layout) should act as one

it's tricky because on desktop, with right aligned buttons, the right most headerbar should show the controls, whereas with left aligned buttons, the left most headerbar should show them

so actually even at the toolkit level there's no way to do that without introducing some kind of headerbar group concept or something

I wish I could just not support moving controls from the right position

**Comment by xou816** [comment]
I'll have a look at notejot though

**Comment by AdrianVovk** [comment]
libadwaita can handle this for you. Check the example on [this page](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.HeaderBar.html)

**Comment by xou816** [comment]
I was about to say "that's exactly what we do" but actually... not exactly. I guess I was too stubborn to see what we were missing!

Not to say that it's an easy fix -- still requires passing along the reference to the leaflet to all "child" headerbars -- but I could have a look, time allowing

**Comment by xou816** [comment]
should finally be fixed, sorry this took so long... been less motivated lately!

I'll push a new version to flathub soon!

**Comment by alissonlauffer** [comment]
> should finally be fixed

Yep, indeed the issue has been fixed. Thank you!
