### ISSUE TITLE
Manjaro package manager compiles unrelated dependencies and crashes when I try to build Spot

### ISSUE THREAD

**Issue by bragefuglseth** [xou816/spot#404]
**Describe the bug**
When I try to build Spot from AUR on Manjaro Gnome edition, the package manager starts compiling lots of unrelated dependencies, before it crashes. It works fine with the Flatpak version.

**To Reproduce**
1. Go Add/Remove software on Manjaro. I use Gnome Edition, but the problem might be with Manjaro or Arch in general.
2. Go to Preferences > Third-party > AUR and enable it.
3. Search for 'spicetify-cli' and choose 'AUR'. It should pop up now.
4. Click 'build'.
5. Confirm the transaction, and tap the little arrow in the bottom right corner to view the installation process.

**Expected behavior**
Spot gets built from AUR and installed without any problems or unnecessary extra dependencies.

**General information:**
 - Distribution: Manjaro Gnome Edition
 - Installation method: Through AUR
 - Device used: Laptop

**Additional context**
This might not be an issue on Spot's end, but all other packages I have installed from AUR have gone effortlessly.

**Comment by jannuary** [comment]
We do not maintain the AUR. Leave an issue in [its repo](https://gitlab.com/dpeukert/pkgbuilds).

**Comment by xou816** [comment]
Also you mention spicetify-cli, whereas the aur package is spot-client I think!

We would need build logs to know what's happening as well :)

**Comment by bragefuglseth** [comment]
Ahh, my bad! I meant Spot, but was trying out Spicetify as well, so I accitentally mixed them up. 🤪 I'll check if the issue is still prevalent and ask in the right place. Thanks!
