### ISSUE TITLE
Doesn't save in keyring

### ISSUE THREAD

**Issue by yavko** [xou816/spot#415]
**Describe the bug**
Whenever i log into spotify it doesnt save the key to the keyring even though i have seahorse and like everything i need, im using the flathub version btw

**To Reproduce**
1. Login
2. Look at seahorse
3. Nothing there

**Expected behavior**
For the key to be saved and not have to login everytime

**Screenshots**
![image](https://user-images.githubusercontent.com/15178513/147530432-9e014495-4ed4-41d4-b252-682dfc122417.png)
this shows ever time

**General information:**
 - Distribution: Manjaro
 - Installation method [e. g. built from source, installed from Flathub...]: flathub
 - Version [e.g. 0.1.0]: 0.2.2
 - Device used [e. g. desktop, phone...]: desktop

**Additional context**
Didnt hapen on aur version just too lazy to compile everytime there is an update also didnt work well with gtk theme.

**Comment by xou816** [comment]
Hi! It could be a permission issue. Could you check that the flatpak version of spot is allowed to use the session bus org.freedesktop.secrets? You can use flatseal or the command line for that: `flatpak info -M dev.alextren.Spot`

**Comment by yavko** [comment]
Apparently it wasn't?
![image](https://user-images.githubusercontent.com/15178513/147610882-f22a6a5a-9322-41c0-88f1-ab45069e8587.png)

**Comment by yavko** [comment]
No it does
![image](https://user-images.githubusercontent.com/15178513/147610912-35e329fb-e1ba-4838-8c12-1d495b4c6bd3.png)

**Comment by yavko** [comment]
> Hi! It could be a permission issue. Could you check that the flatpak version of spot is allowed to use the session bus org.freedesktop.secrets? You can use flatseal or the command line for that: `flatpak info -M dev.alextren.Spot`
> 
> Could you also confirm that the keyring is unlocked when you start spot?

How do i check if its updated? I've used keyring like once.

**Comment by xou816** [comment]
when you start the keyring/Seahorse, it will show in the sidebar if it is locked or unlocked for instance: 
![image](https://user-images.githubusercontent.com/6277494/147881802-8a45a0bc-eb77-465f-be4c-0a2a6c17ca64.png)

**Comment by yavko** [comment]
> when you start the keyring/Seahorse, it will show in the sidebar if it is locked or unlocked for instance: ![image](https://user-images.githubusercontent.com/6277494/147881802-8a45a0bc-eb77-465f-be4c-0a2a6c17ca64.png)

I have noticed that like 10% of the time it works but the other 90% of the time it doesnt
works this time tho
![image](https://user-images.githubusercontent.com/15178513/147890854-cb0fd09b-a70d-4549-bdc4-5a00dee3a61e.png)

**Comment by yavko** [comment]
Seems to be fixed
