### ISSUE TITLE
Why do some podcasts play and others not?

### ISSUE THREAD

**Issue by CleoMenezes** [xou816/spot#417]
![image](https://user-images.githubusercontent.com/54215258/147827723-c26814da-ce83-4aa5-8032-b5cb4e27baf8.png)

I searched for a song and came across a podcast. I clicked to check, even because it was the first time I saw a podcast listed (and as an album).
Now I wonder why some are listed and can be listened to, and others not.

**Comment by jannuary** [comment]
This specific thing is a [song](https://open.spotify.com/track/16dqK4vYXigPdB5KJYuXkh), apparently 🤷
