### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by xou816** [xou816/spot#420]
Hi! Just wanted to wish you all a happy new year :) I've been seeing a lot of returning users contributing fantastic features and feedback. I'll name just a few but I am forgetting others, thanks a lot @jannuary @abegert @Diegovsky @sei0o  @Douile @TotalDarkness-NRF  I'll try (can't promise!) to keep up to pace with you people :) And if there's anything I can help you with to make your work as contributors easier (more visibility? documentation? dedicated communication channel? a proper roadmap?), please do tell me!

**Comment by Diegovsky** [comment]
Happy new years everybody :tada::tada::tada:

It's been fantastic contributing to this project so far and I really appreciate the review process :D

Ragarding making it easier for contributors: One thing that got me while writing my most recent PR is understanding how Events, Actions and Commands interact with each other. I think a github Wiki page documenting how events are handled and how they're propagated would be really nice :)

**Comment by xou816** [comment]
Sounds absolutely reasonable, I'll do that!

**Comment by xou816** [comment]
I started working on [some doc here ](https://github.com/xou816/spot/blob/documentation/doc/doc.pdf) -- I'm sure there are better ways to generate technical documentation for rust projects but those are the tools I enjoy using. Hopefully the figures here will help!

**Comment by Diegovsky** [comment]
I took some time to read the docs and it's pretty solid! I also liked Facebook's Flux architecture talk you linked - it's great material and it helps a lot; I belive this is a good start with the docs :)
