### ISSUE TITLE
Add support for phone screen sizes

### ISSUE THREAD

**Issue by jaredgoodman03** [xou816/spot#43]
I tried this on my Pinephone, and it works pretty well in landscape mode. I'm not sure if this is a big priority, but it would be really nice to use it in vertical mode like the normal Spotify app as well. Currently, the right half of the app is cut off. If the left sidebar was made collapsible it could work.

**Comment by alistair23** [comment]
https://gitlab.gnome.org/GNOME/libhandy/ is used to do this and it has Rust bindings. Fractal and NewsFlash use libhandy to support this.

**Comment by xou816** [comment]
Hi! I definitely want to give libhandy a try, I have no clue how good the rust bindings are however! As for the priority... I've got a lot to do, so we'll see :p

**Comment by xou816** [comment]
OK, I've been poking around with it, it's going better than I expected! I just need to track down which of my widgets ask for too much space :p
![Capture d’écran du 2021-02-02 19-58-03](https://user-images.githubusercontent.com/6277494/106648789-04cae080-6591-11eb-88e9-d696d4770e57.png)

@jaredgoodman03 I don't know much about the pinephone in practice, what's the expected width of a window there?

**Comment by jaredgoodman03** [comment]
It's a 5.95 inch diagonal with a 1440x720 resolution. Let me know if you want me to test it on there.
Thanks! This is really cool.

**Comment by xou816** [comment]
Thanks, I'll give you a heads up when I have something usable, I might upload a build here! Real world experience with the phone is definitely valuable :)

**Comment by xou816** [comment]
A new version is up on flathub! It is... suboptimal in terms of navigation (need to spend sometime thinking that) but it should be better already for mobile usage, if you want to give it a try @jaredgoodman03 :)

**Comment by jaredgoodman03** [comment]
Just tried it out! Definitely is cut off at parts, but now it's really usable. This is so cool, thanks!

**Comment by xou816** [comment]
Happy to have helped :) if you notice anything that breaks badly on mobile don't hesitate to open dedicated issues (with screenshots if possible)
