### ISSUE TITLE
Use later libadwaita

### ISSUE THREAD

**Issue by jannuary** [xou816/spot#430]
We've released 0.3.0 with alpha6, but that subtly breaks some styles compared to main/1.0:
For examples, album cover borders use nonexistant style:
![image](https://user-images.githubusercontent.com/27908024/149455942-5e39f251-bb4b-4b2f-b237-31f8fd720f9f.png)
Everything with .card also uses borders and not shadows, which feels weird next to shaded song list

**Comment by xou816** [comment]
Right, sorry, should have given you a heads up! I wanted to make a release against the most recent stable runtime (41) and that required downgrading to an older version of libadwaita. If that's ok with you, we'll leave it as it is on master until we get 42, but on development I'll look into moving to the latest stable libadwaita!

**Comment by jannuary** [comment]
Can we bundle libadwaita 1.0's deps?

See [Secrets](https://github.com/flathub/org.gnome.World.Secrets/blob/master/org.gnome.World.Secrets.json), for example

**Comment by xou816** [comment]
Oh I see, they are building a more up to date Gtk as well. Hmm, why not, but if it's not that big an issue we might as well just wait for 42 while we iron things out on nightly. We won't even have to build libadwaita by then!
