### ISSUE TITLE
Font not displaying properly.

### ISSUE THREAD

**Issue by Art-2** [xou816/spot#441]
**Describe the bug**
Letters are cut off at the top of artist names in the playlist.
![Captura de pantalla_2022-01-16_13-57-13](https://user-images.githubusercontent.com/12375357/149675836-2dbe0e9f-a57b-4bf6-ad49-d918b1cd1680.png)

**General information:**
 - Distribution: Xubuntu 20.04
 - Installation method: installed from Flathub
 - Version: 0.3.0
 - Device used: Desktop

**Additional context**
The font I am using is: Liberation Sans Regular 9

**Comment by xou816** [comment]
Hi! Have you observed this issue in any other Gtk4/libadwaita apps? This is probably something upstream, we're not doing anything out of the ordinary here, just showing a label

**Comment by jessestricker** [comment]
> Hi! Have you observed this issue in any other Gtk4/libadwaita apps?

Yes, in the time since I commented on this issue I've actually seen this also in other places, like the GNOME Settings.

I kind of forgot about this issue, or else I would have mentioned this earlier, sorry. 
So it seems like my comment is not connected to the original issue description by @Art-2.
