### ISSUE TITLE
Spot doesn't pick up GTK theme on Arch, Cinnamon

### ISSUE THREAD

**Issue by OhaDerErste** [xou816/spot#445]
I installed spot using the AUR and set my theme to Dracula using: 
gsettings set org.cinnamon.desktop.interface gtk-theme 'Dracula'
My Spot interface hasn't changed

**Comment by jannuary** [comment]
Not a bug 💖

libadwaita, and, by extension adwaita stylesheet, is a hard dependency for a reason - we depend on many of its widgets and build our custom styles off it.

**Comment by jannuary** [comment]
No.

**Comment by OhaDerErste** [comment]
:(

**Comment by Diegovsky** [comment]
You will be able to use the new [recoloring API](https://blogs.gnome.org/alexm/2021/12/31/libadwaita-1-0/) sometime in the future.

Unfortunately, Spot will be using the default Adwaita theme until it launches.

**Comment by OhaDerErste** [comment]
thaks

**Comment by szbergeron** [comment]
@OhaDerErste you can still specify a theme using the `GTK_THEME` env var afaik, but if your theme isn't gtk4 compatible or doesn't align with libadwaita in the ways that the spot devs expect it will likely have visual glitches

**Comment by OhaDerErste** [comment]
Could you explain to me how to do that?
(Linux Noob)

**Comment by szbergeron** [comment]
You run your application using `GTK_THEME=<your theme's name/variant> my_application_name` or you put the part before the application name into either your ~/.profile or /etc/environment if you want it to apply system wide

**Comment by OhaDerErste** [comment]
![image](https://user-images.githubusercontent.com/77100649/150603840-713a92ff-4cf4-4e67-80b1-62ecb07bffb8.png)
THX

**Comment by Diegovsky** [comment]
except for the bugs, it looks kinda nice

**Comment by OhaDerErste** [comment]
I didn't find any bugs

**Comment by Diegovsky** [comment]
Oh those blue squares were censoring? I thought they were bugs lol

Looking good mate :+1:
