### ISSUE TITLE
Window controls are being displayed twice with non-standard Mutter configuration

### ISSUE THREAD

**Issue by dklementowski** [xou816/spot#454]
I'm not sure if the issue is related to Spot itself or rather Libadwaita/Mutter/anything else on the GNOME side.
My Spot window looks like this:
![obraz](https://user-images.githubusercontent.com/96258917/150987408-60818037-a4f2-46e3-96b7-61694fe4d9d2.png)
Close and minimize buttons are displayed twice. This is due to my configuration - I move those buttons to the left side (because I like it like that). I cannot remember how exactly I changed that, because it was long ago, but for sure it was somewhere in DConf.

BTW I really like the new layout, it looks slick!

**Comment by xou816** [comment]
closing as duplicate, thanks!
