### ISSUE TITLE
Feature request: also support Deezer?

### ISSUE THREAD

**Issue by marek-lach** [xou816/spot#476]
**Describe the feature request**
Since this is a native GTK app, responsive on mobile devices, it would be useful if it also started supporting some other streaming services apart from Spotify itself also, and [Deezer has good Rust support for accessing its API](https://github.com/tsirysndr/deezer-rs), (with some [documentation](https://docs.rs/deezer/latest/deezer/) too) so it'd be a good candidate...

**Comment by xou816** [comment]
No, definitely won't do this, sorry, I'd rather focus on supporting one service well (and there's still a lot of work to be done with Spotify!)
