### ISSUE TITLE
Long playlist jumps back when scrolling quickly

### ISSUE THREAD

**Issue by ondras12345** [xou816/spot#479]
**Describe the bug**
When scrolling through a rather long playlist (319 songs), it sometimes happens that e.g. when scrolling up, the scrollbar jumps back to the bottom after a certain song (probably API page boundary). You can get past it by scrolling slowly.

**To Reproduce**
1. Open a long playlist (say >200 songs)
2. Grab the scrollbar and quickly move it all the way to the bottom. Wait for all pages to load and then release it.
3. Start scrolling up by quickly turning the scroll wheel.
4. See the scroll bar jump back down when you surpass a certain point.

**Expected behavior**
Scrolling in large playlists should work. If the page is not available, it should stop and wait instead of jumping back (probably another page boundary).

**Screenshots**
Please note that this GIF only ends after I move my mouse. (The described error is quite hard to distinguish from a repeating GIF. Watch the song playing at the bottom.)
![Spot-playlist-jumping](https://user-images.githubusercontent.com/44524735/155875710-5d0a7572-15c6-4a8d-84a9-dacb2ddce3d6.gif)

**General information:**
 - Distribution: Ubuntu 20.04.4
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.3.1
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
```
No rust errors, just this:
```
(spot:2): Gtk-WARNING **: 17:30:50.808: GtkListView failed to scroll to given position. Ignoring...

(spot:2): Gtk-WARNING **: 17:30:50.810: GtkListView failed to scroll to given position. Ignoring...

(spot:2): Gtk-WARNING **: 17:30:50.890: GtkListView failed to scroll to given position. Ignoring...

(spot:2): Gtk-WARNING **: 17:30:50.890: GtkListView failed to scroll to given position. Ignoring...

...
```

**Additional context**

**Comment by xou816** [comment]
Hi! This is a gtk bug which I cant do much about right now :/

**Comment by xou816** [comment]
closing as wontifx
