### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [xou816/spot#481]
The current icon isn't really in line with the HIG, would you be interested in help with a new one?

Here's a first attempt, but I'd be happy to try something else if you have ideas/suggestions.

![image](https://user-images.githubusercontent.com/1908896/157866025-bf5de39c-3cd0-4b41-acc4-0f8282d5e153.png)

**Comment by xou816** [comment]
Besides HIG, this is a vast improvement over the current icon I came up with! thank you for this.

I like the design you came up with, I don't have much to say, looks really good to me!

**Comment by bertob** [comment]
Cool, happy to hear that! I'll add a symbolic and open an MR.

**Comment by Barraguesh** [comment]
This is pretty cool! I would say it's only lacking the Spotify black waves inside the green part.

**Comment by jannuary** [comment]
Prolly should be closed :p
