### ISSUE TITLE
Windows, Mac version?

### ISSUE THREAD

**Issue by MessiasLima** [xou816/spot#490]
is there any possibility to release a mac/windows version?

**Comment by xou816** [comment]
No, no plans to support other OSes, I´d recommend looking at psst for an alternative!

**Comment by laurinneff** [comment]
Assuming that Spot doesn't do anything Linux-specific (MPRIS doesn't count, as D-Bus works on other OSes) it should be relatively easy to build it yourself though. Check out [MSYS2](https://www.msys2.org/) if you use Windows, it provides many common Linux packages for Win, including GTK4 and libadwaita. Media keys on other OSes will require OS-specific code changes though.
