### ISSUE TITLE
Spot flatpak crashes

### ISSUE THREAD

**Issue by jakubiszon26** [xou816/spot#506]
**Describe the bug**
Spot crashes soon after launch

**To Reproduce**
1. Go to terminal
2. run ```RUST_BACKTRACE=full flatpak run dev.alextren.Spot```
3. See the crash

**Screenshots**
![image](https://user-images.githubusercontent.com/61655602/160662857-0cd83194-a5f8-49ce-9aec-823446df7549.png)

**General information:**
 - Distribution: ```Fedora 36 Beta```
 - Installation method [e. g. built from source, installed from Flathub...]: ```Flathub```
 - Version [e.g. 0.1.0]: ```newest from flatpak```
 - Device used [e. g. desktop, phone...]: ```matebook 13 2020 laptop```

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```

[jakub@fedora ~]$ flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot

(process:2): Adwaita-CRITICAL **: 18:44:15.945: adw_leaflet_set_visible_child: assertion 'contains_child' failed
thread 'main' panicked at 'Argument count has to match number of format directives ({})', src/app/components/labels.rs:23:5
stack backtrace:
   0:     0x5605615d9ddc - <unknown>
   1:     0x5605616024ac - <unknown>
   2:     0x5605615d1a93 - <unknown>
   3:     0x5605615dc752 - <unknown>
   4:     0x5605615dc335 - <unknown>
   5:     0x5605615dcda3 - <unknown>
   6:     0x5605615dcac0 - <unknown>
   7:     0x5605615da284 - <unknown>
   8:     0x5605615dc7f9 - <unknown>
   9:     0x560560b80a61 - <unknown>
  10:     0x5605615ffbb1 - <unknown>
  11:     0x5605615ffb5b - <unknown>
  12:     0x560560b80956 - <unknown>
  13:     0x560560c2e727 - <unknown>
  14:     0x560560ea0122 - <unknown>
  15:     0x560560d37fb7 - <unknown>
  16:     0x560560cb22da - <unknown>
  17:     0x560560df6454 - <unknown>
  18:     0x5605615b42ef - <unknown>
  19:     0x5605615b501a - <unknown>
  20:     0x7f85771abceb - g_main_context_dispatch
  21:     0x7f85771ac1f8 - <unknown>
  22:     0x7f85771ac2c4 - g_main_context_iteration
  23:     0x7f85773e9c0d - g_application_run
  24:     0x560560c1872e - <unknown>
  25:     0x560560baf99e - <unknown>
  26:     0x560560c93b74 - <unknown>
  27:     0x560560eebbd3 - <unknown>
  28:     0x560560f10589 - <unknown>
  29:     0x5605615d9490 - <unknown>
  30:     0x560560c966b2 - main
  31:     0x7f8576e10b90 - __libc_start_main
  32:     0x560560b8122e - <unknown>
  33:                0x0 - <unknown>
```

**Comment by xou816** [comment]
Hi! Thanks for the report. Looks like there's an issue with an improperly formatted translation :/ which language are you using?

**Comment by ondras12345** [comment]
Probably this:
https://github.com/xou816/spot/blob/89646adc24f4857055b53e61167ac3788a589c93/po/pl.po#L33-L35

**Comment by xou816** [comment]
Good catch @ondras12345 , that would be the one :/ I'll patch that later today!

**Comment by xou816** [comment]
looks like its been fixed a while ago, not sure. closing but feel free to reopen!
