### ISSUE TITLE
Bail out! assertion failed: (item != NULL)

### ISSUE THREAD

**Issue by ondras12345** [xou816/spot#509]
**Describe the bug**
Spot crashes after a song from a playlist finishes playing.

**To Reproduce**
1. Play music from playlist (mine has over 300 songs, might be related to API pagination)
2. Wait for Spot to crash. Unfortunately, this happens very rarely.

**Expected behavior**
No crash.

**General information:**
 - Distribution: Ubuntu 20.04.4 LTS
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.3.3
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
...
Gtk:ERROR:../gtk/gtklistitemmanager.c:524:gtk_list_item_manager_ensure_items: assertion failed: (item != NULL)
Bail out! Gtk:ERROR:../gtk/gtklistitemmanager.c:524:gtk_list_item_manager_ensure_items: assertion failed: (item != NULL)
```

**Additional context**
I see in my notes that this first happened to me on 2022-03-31 with Spot 0.3.2, and then today (2022-04-10) with Spot 0.3.3. This makes the crash quite rare and possibly hard to debug.

**Comment by Diegovsky** [comment]
This is a very old version of spot. As a daily user, hasn't occoured to be so I'm closing
