### ISSUE TITLE
Library should allow browsing Liked Songs

### ISSUE THREAD

**Issue by LukeHuckman** [xou816/spot#51]
Having the ability to like songs and have access to the liked songs list would be really convenient since I personally use that feature a lot.

**Comment by xou816** [comment]
It is not a top priority for me atm (I'll clarify with a roadmap later) but I'll keep the issue open, it shouldn't be all that hard to implement :)

**Comment by satya164** [comment]
Just chiming in for this feature. I exclusively use my "Liked songs" list to play music (only with few other playlists), so without it I am unable to use Spot to play my music. It'd be pretty cool to have it since I really like the idea of a native lightweight spotify client.

**Comment by xou816** [comment]
So I looked a bit into it -- should be doable for the most part, except checking that a song is already liked or not -- this might require individual requests (when opening the contextual menu perhaps?) for every song :/

**Comment by abonander** [comment]
Would love this feature, yeah. I pretty much exclusively listen to music by putting Liked Songs on shuffle.

**Comment by sei0o** [comment]
> this might require individual requests (when opening the contextual menu perhaps?) for every song :/

`/me/tracks/contains` endpoint checks if a track is liked (hearted) by the current user, and accepts many track IDs in a single request. When a playlist is opened, the official web client sends something like this:

```
https://api.spotify.com/v1/me/tracks/contains?ids=04vGT4j9W8RWBRmIgHJsIL,05Jt5VDLzONX0wNK7v6B1U,0E2A3EhNsvWYWVqSaqisep,0lw3knZRdxe0G1cNwygFpE,0d6f1v0p8EHAfBpK7hb4Sa, ...
```

Then the response is something like below, which means `04vG...` is not hearted but `05Jt...` is hearted.

```
[ false, true, false, true, ... ]
```

However, I have no idea whether librespot supports this.

**Comment by kalikiana** [comment]
As mentioned in https://github.com/xou816/spot/issues/284#issuecomment-990397045_ browsing **Saved tracks** works fine for me. I'm guessing it was implemened at some point? So I can see the songs fine, except they don't refresh.

I'd be interested in maybe fixing the refresh. Would somebody have pointers where to start?

**Comment by TheCultLeader666** [comment]
What about the "Saved Tracks" tab in the sidebar? That seems to show liked songs.

**Comment by xou816** [comment]
I probably forgot to close the issue. Thanks for the heads up :)

As for the refresh: right now the screen is never refreshed/the request to fetch liked songs is never sent again because the screen is never recreated. Maybe we could refresh when navigating to it, but I don't think it's really needed. We should however refresh when we add the ability to like songs from within the app! I've got an old draft of this somewhere that I need to push, I'll let you know if you're interested in having a look :)

**Comment by xou816** [comment]
(closing this one for now :) )
