### ISSUE TITLE
New Login from Bulgaria

### ISSUE THREAD

**Issue by thebiblelover7** [xou816/spot#510]
I keep on getting an email notification that there is a new login from Bulgaria whenever I use the spot app. This hasn't happened before, and I've changed my password already, but since I use spot, I keep on getting these notifications. 

Is there a service that is used so that you can login that is hosted in Bulgaria? Is it just me that is getting random logins? Any help would be much appreciated!

**Comment by ondras12345** [comment]
Spot triggers a new login e-mail every time it needs to get a new short-lived token. https://github.com/xou816/spot/issues/374 https://github.com/xou816/spot/issues/163
It authenticates directly against the Spotify infrastructure.
If your e-mail say the login is originating from Bulgaria, then Spotify probably thinks that your public IP belongs to Bulgaria. Are you using a VPN? That could be the cause for incorrect geolocation. (Assuming that you aren't located in Bulgaria.)

**Comment by thebiblelover7** [comment]
No, I am not using a VPN, but maybe my ISP is doing something with that. At least I know it's not an intruder ;)

**Comment by xou816** [comment]
Hi! I'll work on @Louis9902 's solution eventually, this should solve the receiving way too many emails part. As for the location, that's definitely out of our hands :)

**Comment by thebiblelover7** [comment]
@xou816 Great! Actually, I encountered this problem in multiple places (the Bulgaria issue). Maybe my ISP has some weird connections with Bulgaria
