### ISSUE TITLE
[Question] How to compile manually on Ubuntu 22.04?

### ISSUE THREAD

**Issue by PJ-Singh-001** [xou816/spot#513]
Would someone kindly list the detailed steps to build Spot manually on Ubuntu 22.04?

Questions:

1. How to install Rust (not as a snap or flatpak)?
2. What are the specific additional libraries I need?

    I believe Ubuntu 22.04 already comes with GTK4 and `libadwaita`.

    I have also installed:

        sudo apt install git ninja-build meson

When I execute:

    meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"

I get the following error in the log:

    src/meson.build:3.0: ERROR: Pkg-config binary for machine 1 not found. Giving up.

**Comment by PJ-Singh-001** [comment]
1. Install prerequisite development packages.

        sudo apt-add-repository universe
        sudo apt install git pkg-config libadwaita-1-dev cmake libssl-dev libasound2-dev libpulse-dev libxml2-utils ninja-build meson rust-all

 2. Download, compile and install Spot.

        cd ~/Downloads
        git clone https://github.com/xou816/spot.git
        cd spot
        meson target -Dbuildtype=release -Doffline=false --prefix="$HOME/.local"
        sudo ninja install -C target

 3. Optionally, remove the prerequisite development packages.

        sudo apt autoremove git pkg-config libadwaita-1-dev cmake libssl-dev libasound2-dev libpulse-dev libxml2-utils ninja-build meson rust-all

**Comment by xou816** [comment]
thanks for your help @PJ-Singh-001 :)
