### ISSUE TITLE
Crashes on Wayland

### ISSUE THREAD

**Issue by PJ-Singh-001** [xou816/spot#514]
**Describe the bug**

Spot will not start on Wayland.

**To Reproduce**
1. Build and install Spot using [these steps](https://github.com/xou816/spot/issues/513)
2. Log into a Wayland session
3. Click on the Spot application launcher
4. Spot does not start

**Expected behavior**

Spot window should appear.

**Screenshots**

N/A

**General information:**

 - Distribution: Ubuntu 22.04 with Wayland + Nvidia
 - Installation method: built from source
 - Version: 0.3.3
 - Device used: Laptop

**Stack trace:**

The error in the logs is

    WL: error in client communication (pid 5536)

**Additional context**

I am able to get Spot to run if I execute it using:

    GDK_BACKEND=x11 spot

**Comment by PJ-Singh-001** [comment]
This may be an issue with GTK and Wayland...

https://gitlab.gnome.org/GNOME/gtk/-/issues/4881

...so, I don't know if something can be done in Spot, or we have to wait for a fix to Wayland or GTK?

**Comment by xou816** [comment]
Hi! Definitely upstream, and probably related to nvidia too (no issues for me on Wayland + AMD card)

**Comment by PJ-Singh-001** [comment]
Yes. It seems this is an issue with NVDIA and Wayland...

- See [gnome-extensions-app crashes on Wayland](https://gitlab.gnome.org/GNOME/gtk/-/issues/4881).
- See [[BUG] Ver 1.1.8-1 breaks some GTK3/4 apps (Gnome ToDo, Gnome Maps, Cheese) - On Hybrid Graphics configurations](https://github.com/NVIDIA/egl-wayland/issues/41).

**Comment by PJ-Singh-001** [comment]
The work-around is posted [here](https://github.com/NVIDIA/egl-wayland/issues/41#issuecomment-930599652).

Using the environment variable `__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json` seems to solve the problem for most apps.

Here's a set of commands you can use:

    cat /etc/environment
    echo "__EGL_VENDOR_LIBRARY_FILENAMES=/usr/share/glvnd/egl_vendor.d/50_mesa.json" | sudo tee --append cat /etc/environment
    cat /etc/environment

Then, log out and log back in to reload the environment variables.

**Comment by PJ-Singh-001** [comment]
(I'll let you decide if you want to close this issue, or keep it open for tracking purposes).

**Comment by xou816** [comment]
I'll close it for now, might add a note in the README but seeing as this affects much more than one app...
also hopefully things are better now for hybrid graphics users :crossed_fingers:
