### ISSUE TITLE
Feature request: option to follow system theme

### ISSUE THREAD

**Issue by pesader** [xou816/spot#515]
Hi! Would it be possible to add a "Follow system theme" option to the settings? It could change the gsettings `prefers-dark-theme` to `false`, as you mentioned [here](https://github.com/xou816/spot/issues/187#issuecomment-816530939).

I got that Spot [stays dark intentionally](https://github.com/xou816/spot/issues/209#issuecomment-860180537), but I'd love to have light/dark consistency especially now that Dark Mode is officially a thing on GNOME 42. Take a look, I think it makes Spot feel even more "at home" on GNOME:
| Light | Dark |
| ----------- | ----------- |
| ![image](https://user-images.githubusercontent.com/65264536/166163960-f7ba6f13-eb3e-4fae-8998-16e9c410e9d9.png) |![image](https://user-images.githubusercontent.com/65264536/166163964-5ab649d2-fcd9-4926-895f-876bed3826e9.png) |

Thanks a lot for developing Spot!!

**Comment by Diegovsky** [comment]
I was about to comment you can toggle that on Preferences but it did not work for me lol

**Comment by iGadget** [comment]
> I was about to comment you can toggle that on Preferences but it did not work for me lol

Same here on Pop!_OS 22.04 / Flatpak 0.3.3. I'm guessing this a bug?

**Comment by Diegovsky** [comment]
Must be. If I have the time I'll open a pull request. It might take a while so if you know rust, feel free to open a pull request

**Comment by xou816** [comment]
fixed by #548
