### ISSUE TITLE
The playlist is short

### ISSUE THREAD

**Issue by DeadMozay** [xou816/spot#52]
Only 100 tracks are displayed in the playlist and can be listened to, the rest are unavailable

**Comment by ivan-tretyak** [comment]
Yes. I can confirmed this bug.

**Comment by xou816** [comment]
Oh, there's probably pagination for playlists and I missed it. I'll look into it! Thank you for the report.

**Comment by Douile** [comment]
https://developer.spotify.com/console/get-playlist-tracks/ supports pagination through responding with `.next` being `null` or the next URL you should request. But it could be done the same way you have implemented `get_saved_playlists`. I could give it a try if you have no objections.

**Comment by xou816** [comment]
Sure! :o tell me if you need details about the current implementation!

**Comment by Douile** [comment]
Actually it can't be implemented the same, should've done more thinking :). The entire playlist should be downloaded when it is opened otherwise when playing the playlist only some of the songs will be played unless the user scrolls down to load the extra ones. if ygm.

**Comment by Douile** [comment]
I'm thinking of changing `SpotifyApiClient::get_playlist` to accept the `offset` and `limit` parameters as well (like `get_saved_playlists`). Then adding another function `get_full_playlist` that calls `get_playlist` until it has the full playlist (either in `SpotifyApiClient` or `PlaylistModel`). I will wait to here your opinion (@xou816) before I implement though.

**Comment by xou816** [comment]
Very long playlists could lead to problems with this approach, but otherwise I am fine with this! I have no better idea :(

**Comment by Douile** [comment]
@xou816 have been a bit lost in dispatcher code :smile:. Do you think I should keep the one event that loads the entire playlist (handle pagination before dispatching) or switch to a paginated dispatcher and just trigger it many times when the playlist is switched to (handle pagination each dispatch)?

**Comment by xou816** [comment]
Ahah, I understand :D I think one event is fine; events are mostly intended to notify the UI that an update is needed, but if we fetch the whole playlist at once, then a single event is enough!

**Comment by Douile** [comment]
Sound, that is what I am trying to implement. I also just now realized that you didn't miss pagination, there is a separate endpoint `/api/v1/playlist/{id}/tracks` that allows pagination whereas `/api/v1/playlist/{id}` returns the first 100 tracks and the playlist details. I am working on implementing this as a separate API request and removing tracks from `PlaylistDetails` (can also prevent it getting sent in the response of the api request using `fields` search param) but this is probably going to take a long time as I imagine it will break a lot of the player code.

**Comment by xou816** [comment]
Oh nice catch, totally missed that from  the documentation!

I am not sure I understand the part about removing something from PlaylistDetails to be fair^^ but yeah, there are already a couple of public methods on the spotify client that actually aggregate multiple requests, so something similar should be possible :) 

If you want some more reviews along the way, feel free to @ mention me on PRs on your own forked repo! 

I am having second thoughts about loading the full playlist still :/ could there be reaaaally long playlists? I suppose so! I see the official client queues a fixed number of tracks, and as tracks are dequeued, more are loaded and appended. But this requires a proper queue implementation :D what do you think?

In any case, I think the paginated endpoint can at least be implemented!

**Comment by Douile** [comment]
Yeah aggregating actually seems like a better idea, then we don't have to deal with multiple objects.
I'm definitely not capable of doing a proper queue implementation but it is a very cool idea, if someone is able to do it. 
I was also thinking of maybe limiting pagination to the first 500-1000 songs, who's gonna want more than that in a playlist.

**Comment by xou816** [comment]
I had something [like this ](https://github.com/xou816/spot/commit/96e1e22e93ed57caa2ea7b9cde7b468dc5c04b43) in mind for the queue, we could expand from there, support queuing/dequeuing, which could make it simpler to load the playlist progressively!

**Comment by Douile** [comment]
@xou816 finally got a working implementation, what do you think of https://github.com/Douile/spot/commit/00a7dbbc4e5595a5aa68bca5b79c288ca416ea57 

https://github.com/Douile/spot/blob/00a7dbbc4e5595a5aa68bca5b79c288ca416ea57/src/app/backend/api.rs#L504-L560

https://github.com/Douile/spot/blob/00a7dbbc4e5595a5aa68bca5b79c288ca416ea57/src/app/backend/api.rs#L280-L309

https://github.com/Douile/spot/blob/00a7dbbc4e5595a5aa68bca5b79c288ca416ea57/src/app/backend/api_models.rs#L217-L226
