### ISSUE TITLE
Adaptive layout doesn't show player controls

### ISSUE THREAD

**Issue by caetano-m** [xou816/spot#520]
**Describe the bug**
When resizing the window to the smallest layout, it hides the player and shows only the user's playlists. To switch, pause, resume music etc the user has to resize the window again so it shows the music playing.

**To Reproduce**
1. Play any music
2. Resize horizontally the window, until it has only one content column
3. Fail to see controls of the currently playing music

**Expected behavior**
A miniplayer should be visible

**Videos**

https://user-images.githubusercontent.com/71804353/166981325-207097ff-cd76-4eb2-b57e-ba7aca64b0df.mp4

**General information:**
 - Distribution: Fedora 34
 - Installation method: Flatpak from Flathub
 - Version: 0.3.3

**Comment by xou816** [comment]
sorry missed your issue, I'll move discussion over to #521 if you don't mind!
