### ISSUE TITLE
"Bail out! Gsk:ERROR" when running through gdb

### ISSUE THREAD

**Issue by duncan-bayne** [xou816/spot#537]
**Describe the bug**
When trying to run `spot` through `gdb` to debug https://github.com/xou816/spot/issues/118, `spot` crashes while selecting a playlist.

**To Reproduce**
1. Run using `gdb spot` then `r`.
2. Click on `All Playlists`.
3. See error:
```
Gsk:ERROR:../../../gsk/gl/gskglcommandqueue.c:1276:gsk_gl_command_queue_create_render_target: assertion failed (glCheckFramebufferStatus (GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE): (0x00008cd6 == 0x00008cd5)
Bail out! Gsk:ERROR:../../../gsk/gl/gskglcommandqueue.c:1276:gsk_gl_command_queue_create_render_target: assertion failed (glCheckFramebufferStatus (GL_FRAMEBUFFER) == GL_FRAMEBUFFER_COMPLETE): (0x00008cd6 == 0x00008cd5)

Thread 1 "spot" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Expected behavior**
I expect the list of all playlists to be displayed, so I can pick some music and hopefully reproduce the "muting" issue.

Amusingly, if I run the app directly, rather than through a debugger, it doesn't display this behaviour, and I can reproduce #118.

**General information:**
 - Distribution: Mobian GNU/Linux 
 - Installation method [e. g. built from source, installed from Flathub...]: built from source
 - Version [e.g. 0.1.0]:  0.3.3-dev
 - Device used [e. g. desktop, phone...]: PinePhone

**Comment by xou816** [comment]
thanks for the report! yeah I'm really not skilled enough to tackle this kind of issue. it most likely has to do with gtk/gsomething rather than spot anyway :/ I'll close that for now if you don't mind
