### ISSUE TITLE
Playback no longer possible - librespot update necessary

### ISSUE THREAD

**Issue by janbrummer** [xou816/spot#541]
**Describe the bug**
Playback is no longer possible

**To Reproduce**
1. Start playback2. 

**Expected behavior**
Music is playing

**Additional context**
Two gateways have "problems" with channels, therefore they have been disabled. Update to librespot 0.4.2 is necessary.

**Comment by laurinneff** [comment]
Workaround until this is solved:

1. Open https://apresolve.spotify.com
2. Look up the IP address of the first entry that is **not** ap-gew4 or ap-gue1. Some tools to try:
  - `resolvectl query [hostname]`
  - `nslookup [hostname]`
  - `dig [hostname]`
  - https://dns.google
3. Add an entry to your /etc/hosts file:
   ```
   [ip address] ap-gew4.spotify.com ap-gue1.spotify.com
   ```

You can remove the entry again when this issue is closed or when Spotify fixes their infrastructure.

**Comment by xou816** [comment]
Hi! do you know if this issue is still present in development branch? we've updated librespot

**Comment by balacij** [comment]
With spot 0.4.0 (which I think has the updated librespot 0.4.2), I had the same issue. For me, the fix involved only overriding `ap-gew4.spotify.com` with the ip from `ap-gew1.spotify.com` (at time of writing: 104.199.65.124).

**Comment by janbrummer** [comment]
It is no longer needed, my PR to update librespot 0.4.2 did the necessary lifting. That's the reason why they have released 0.4.2.

**Comment by janbrummer** [comment]
https://github.com/librespot-org/librespot/releases/tag/v0.4.2

**Comment by balacij** [comment]
From what I understand, it's [not actually a perfect fix](https://github.com/librespot-org/librespot/issues/972#issuecomment-1057944994), which is I guess why I am still observing it and needed the `/etc/hosts` fix. But, I'm installing from NixOS which might not be using the same 0.4.0 Spot, so I'm not sure (I didn't check out the package derivation)! I definitely needed the `/etc/hosts` fix for it to work.

**Comment by Diegovsky** [comment]
I'll be closing this as it is mainly a problem with librespot, as [put by one of their devs](https://github.com/librespot-org/librespot/issues/972#issuecomment-1057944994)
