### ISSUE TITLE
AUR-package fails to build

### ISSUE THREAD

**Issue by chebureki** [xou816/spot#542]
**Describe the bug**
https://aur.archlinux.org/spot-client.git
and
https://aur.archlinux.org/spot-client-git.git
fail to build

**To Reproduce**
```console
yay -S spot-client
```
or 
**Expected behavior**
to build

**General information:**
 - Distribution: Arch
 - Installation method : AUR

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
ninja: Entering directory `/var/tmp/pamac-build-cheb/spot-client/src/build'
ninja: no work to do.
1/3 Validate schema file              OK              0.01s
2/3 Validate appstream appdata        FAIL            0.19s   killed by signal 11 SIGSEGV
> MALLOC_PERTURB_=222 /usr/bin/appstream-util validate-relax /var/tmp/pamac-build-cheb/spot-client/src/spot-0.3.2/data/dev.alextren.Spot.appdata.xml
> 
> 3/3 Unit tests                        OK             16.16s
> 
> Ok:                 2   
> Expected Fail:      0   
> Fail:               1   
> Unexpected Pass:    0   
> Skipped:            0   
> Timeout:            0   
```

**Additional context**
This may just be a bug in appstream, it's a Segfault afterall, I will dig into it later on

**Comment by sssemil** [comment]
Looks like a test is failing:
```
==================================== 2/3 =====================================
test:         Validate appstream appdata
start time:   01:10:28
duration:     0.25s
result:       killed by signal 11 SIGSEGV
command:      MALLOC_PERTURB_=164 /usr/bin/appstream-util validate-relax /home/emil/.cache/yay/spot-client-git/src/spot-client-git/data/dev.alextren.Spot.appdata.xml
----------------------------------- stdout -----------------------------------
/home/emil/.cache/yay/spot-client-git/src/spot-client-git/data/dev.alextren.Spot.appdata.xml:
----------------------------------- stderr -----------------------------------

(appstream-util:85802): GLib-GIO-CRITICAL **: 03:10:28.608: g_proxy_resolver_lookup: assertion 'G_IS_PROXY_RESOLVER (resolver)' failed
```

**Comment by chebureki** [comment]
Manually compiling works just fine, weird.

**Comment by chebureki** [comment]
A temporary solution would be to remove `check()` from `PKGBUILD`

**Comment by chebureki** [comment]
okay so, running `meson test` also doesn't work ... digging in

**Comment by chebureki** [comment]
`/usr/bin/appstream-util validate-relax /home/cheb/dev/spot/data/dev.alextren.Spot.appdata.xml`
results in a segfault 😭

**Comment by sssemil** [comment]
This issue happened when I tried installing touche today. Def appstream-util bug.

**Comment by sssemil** [comment]
So, here is the solution, just use the latest version of [appstream-glib](https://github.com/hughsie/appstream-glib). I used the official [PKGBUILD](https://github.com/archlinux/svntogit-packages/tree/packages/appstream-glib/trunk) for the arch package, but replaced the commit hash with the latest one. Here's my PKGBUILD file - https://esnx.xyz/scripts/appstream-glib-PKGBUILD (save in a folder, run `makepkg -i`). There's also an [AUR package for the latest git version](https://aur.archlinux.org/packages/appstream-glib-git), but I haven't tested it myself.

**Comment by ximion** [comment]
Would actually make sense to switch this tool to using `appstreamcli` for validation instead: `appstreamcli validate --strict /path/to/metainfo.xml`
The `appstream-util` utility is essentially deprecated and doesn't have support for any new features or validation.

**Comment by NathanC** [comment]
@sssemil Tried your fix (and `appsteam-glib-git`, neither worked for me, still for the malloc errors. Any other ideas for a quick fix? 

I posted comments in the spot AUR packages so the maintainers know about the issue.

**Comment by samsapti** [comment]
The package builds successfully now (at least `spot-client-git`). @xou816 can this be closed?

**Comment by xou816** [comment]
I guess yeah! I'm still curious what the exact cause was or if we should do something  else to prevent it, but yeah
