### ISSUE TITLE
Theme change does not work 

### ISSUE THREAD

**Issue by iGadget** [xou816/spot#544]
**Describe the bug**
When changing the Theme under Preferences, the theme stays the same.

**To Reproduce**
1. Go to 'Preferences -> Appearance'
2. Click on 'Theme'
3. Change Theme to a different one than currently in use
4. Theme does not change.

**Expected behavior**
Theme should change from Light to Dark or vice-versa.

**General information:**
 - Distribution: Pop!_OS 22.04 (light theme)
 - Installation method: Flathub
 - Version [e.g. 0.1.0]: 0.3.3.
 - Device used [e. g. desktop, phone...]: Desktop

**Additional context**
Apparently already known by @Diegovsky as per https://github.com/xou816/spot/issues/515#issuecomment-1118436691

**Comment by Diegovsky** [comment]
I'm 99% sure it is fixed in an upcoming version. Keep tuned :)

**Comment by xou816** [comment]
yes, i'll close this for now to clear up issues as this should be part of the next version! feel free to reopen if the issue persists!
