### ISSUE TITLE
[Feature Request] Follow device "theme"

### ISSUE THREAD

**Issue by busterbeam** [xou816/spot#553]
I have night theme switcher extension... It would be cool if the theme switched with my OS theme

**Comment by Diegovsky** [comment]
I'm not familiar with that extension. Using gnome 43.2 on my machine, I can switch dark/light mode and it changes Spot's color.

**Comment by busterbeam** [comment]
Alright, I should clarify, theme switching isn't a problem when done "manually".  I'm asking if the app could query for what theme your desktop is using and follow that.  My "night theme switcher extension" doesn't actually need to communicate to you app, it toggles the theme settings in GNOME to change the system them from light to dark, and from dark to light, based on time of day.  My spot is 0.3.3 and my GNOME is 3.38.5

**Comment by Diegovsky** [comment]
> GNOME is 3.38.5

Probably does not support the new global dark theme announcement API or something yet. Your gnome version is very old. I'll see what I can do but keep in mind we're about to get gnome 43 now.

**Comment by Diegovsky** [comment]
Also, did you select the `system` theme?
![image](https://user-images.githubusercontent.com/46163903/220127335-e2bffc6c-8226-4737-8a01-4eb73f7fefdc.png)

**Comment by busterbeam** [comment]
Nope, on it being "old" as all other applications do follow "system", and yes the appearance drop down, only has "light" or "dark".  no "system"

**Comment by Diegovsky** [comment]
I see. it has been fixed in the latest version. Could you update it?

**Comment by jacobmealey** [comment]
Hello, I'm using the same plugin with gnome 43 and it works fine for me with the what the most recent push on `development`

**Comment by bragefuglseth** [comment]
I think we can close this issue now.

**Comment by Diegovsky** [comment]
I'm closing this since it is said to be working. If anyone noticed any bug, feel free to re-open :)
