### ISSUE TITLE
Amazing project!

### ISSUE THREAD

**Issue by drsounds** [xou816/spot#56]
Amazing!
I waited for this to happen in over 10 years now!

This is like Spotify was 2009 before it become bloated and now you brought it back! I really hate the > 2015 html5 bloated CEF client!

Thanks for building this 'time machine' I've tried to do for a decade!

**Comment by xou816** [comment]
Thank you for the kind words :) don't overestimate the project though, it's missing quite a few important features and it will never match the official client! I am glad you enjoy it nonetheless! I'll close the issue if you don't mind, I have a lot of issues to keep track of already ;)
