### ISSUE TITLE
Spot has a max windows size

### ISSUE THREAD

**Issue by pavelskipenes** [xou816/spot#566]
**Describe the bug**
Window will not resize larger than a max fixed size

**To Reproduce**
1. open app
2. use a 3440x1440 screen with 100% resolution scale and drag the windows to fill larger portion of the screen. Or optionally use a tiling window manager and notice gaps in spots location.

**Expected behavior**
window would not resize itself

[Screencast from 2022-11-20 18-35-27.webm](https://user-images.githubusercontent.com/38912521/202917084-2296e264-13d6-4f26-925c-c9b1fa6a75df.webm)

might be related to #424

**Comment by xou816** [comment]
Hi! this is indeed very strange. Couple things you can try:
- does it happen on a smaller screen with the same setup?
- are you able to test different environments? x11 vs wayland/another DE?

**Comment by samsapti** [comment]
I'm using kinda the same setup. Spot installed via `spot-client-git` from AUR on Artix Linux, running Sway and launching Spot directly in Wayland. On my 3440x1440p monitor with 1x scaling, I'm not having above mentioned issue, Spot behaves as expected.

**Comment by Diegovsky** [comment]
Closing this due to conflicting reports. Feel free to open again if the problem persists in the newest version.
