### ISSUE TITLE
Add longer seekbar when layout allows

### ISSUE THREAD

**Issue by szbergeron** [xou816/spot#57]
When the window is large the seekbar doesn't expand to fill, which for super long tracks makes seeking difficult.

![image](https://user-images.githubusercontent.com/7364398/108232922-4327da00-7111-11eb-8031-3b46094e17ed.png)

It would be nice to have the seekbar expand to fill the available horizontal space for this.

**Comment by xou816** [comment]
That's a good point, and should be an easy fix! Thanks for the feedback :)

**Comment by nickx720** [comment]
Would it be possible for me to pick up this ticket?
