### ISSUE TITLE
[Feature Request] Pipewire backend

### ISSUE THREAD

**Issue by VxlerieUwU** [xou816/spot#578]
title explains everything, librespot has a pipewire backend, using it on pipewire systems could maybe reduce some latency

**Comment by Diegovsky** [comment]
It seems librespot does not have a pipewire backend according to @XGZepto. Closing this issue, but feel free to open an issue in their repo :)

**Comment by darkdragon-001** [comment]
I created an issue in librespot-org/librespot#1121.
