### ISSUE TITLE
sync/add local files

### ISSUE THREAD

**Issue by infdev-fil** [xou816/spot#580]
I'm not a gnome developer, so I wouldn't estimate the amount of work it would take, but the ability to synchronize local files would be very useful. Spot is very nice to use and not being constrained to the spotify catalog would make it THE music player.

Thank you for taking the time to read this issue, I have some basic rust if you take the time to work on it I would be happy to participate

**Comment by xou816** [comment]
hi! sorry, this is a bit out of scope for the project :)
