### ISSUE TITLE
No playlists from Spotify search

### ISSUE THREAD

**Issue by crismblog** [xou816/spot#59]
I have a few lists created in Spotify and it doesn't see them all. The message that appears is: An error occured. Check logs for details!
![Captură de ecran de la 2021-02-17 19-01-35](https://user-images.githubusercontent.com/26747226/108239573-b7cf3880-7152-11eb-8911-47f2e0c2ad6c.png)

**Comment by bnainar** [comment]
Which distro? Looks beautiful

**Comment by crismblog** [comment]
I installed the application in Fedora 33 GNOME
Thanks

**Comment by xou816** [comment]
Hi! Could you share some more details? What were you trying to do? Also, could you run spot from the command line as follows:
`flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot`

Thanks!

**Comment by crismblog** [comment]
I installed the program from the GUI and everything goes smoothly except for a single list that has 84 songs. I have another list of 100 songs and it is seen without any problem.

The operating system is Fedora 33 installed on a desktop.

`[cristian@fedora ~]$ flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
home
playlist_5i4lAHHKmpMk1AVat8fEq4
Expired: net/playlist_5i4lAHHKmpMk1AVat8fEq4.json
Error: ParseError(Error("invalid type: null, expected struct TrackItem", line: 7966, column: 20))
[cristian@fedora ~]$`

**Comment by xou816** [comment]
Oh, that's interesting! Do you have greyed out/unavailable tracks in this playlist? (as seen from another client)

It could be related to this in the doc:

> Information about the tracks of the playlist. Note, a track object **may be null. This can happen if a track is no longer available**

**Comment by crismblog** [comment]
I looked at the sea and the songs seem fine.

**Comment by xou816** [comment]
Is the playlist public? Could it be shared?

**Comment by crismblog** [comment]
Yes, the playlist is public. The playlist is: https://open.spotify.com/playlist/5i4lAHHKmpMk1AVat8fEq4?si=8b683ddd524f4d8e

**Comment by xou816** [comment]
Thank you very much, it was indeed a track that is no longer available! It'll be fixed in the next version

**Comment by crismblog** [comment]
I'm glad I was able to help. Thanks
