### ISSUE TITLE
Add a separate "currently playing" view on devices with small widths

### ISSUE THREAD

**Issue by pojntfx** [xou816/spot#60]
## Overview

As discussed in https://github.com/xou816/spot/issues/50#issuecomment-780785206, it might be a good idea to implement a seperate view for better mobile support. This view would show details of the currently playing song, thus enabling scrubbing, skipping songs and so on. Adding mobile support would probably make this the premier Spotify app/music player on mobile Linux devices, such as the PinePhone or Librem 5.

## Current State

As of 2020-02-17, the UI is usable on mobile, but lacks proper song controls:

<img src="https://user-images.githubusercontent.com/28832235/108254592-8018be80-715b-11eb-9e61-987a0a0d3e1d.png" width="200">

## Proposed Changes

[iOS Spotify](https://user-images.githubusercontent.com/28832235/108260050-21a30e80-7162-11eb-8f38-33e514811773.png) implements this as follows:

<img src="https://user-images.githubusercontent.com/28832235/108254732-b0f8f380-715b-11eb-8904-79ba7a6c574c.png" width="200">

<img src="https://user-images.githubusercontent.com/28832235/108254737-b22a2080-715b-11eb-8f59-cb0c607bfcec.png" width="200">

[Lollypop](https://wiki.gnome.org/Apps/Lollypop) does it in a similar fashion, hiding the current song view on desktop but showing it on mobile:

![Screenshot from 2021-02-17 20-49-32](https://user-images.githubusercontent.com/28832235/108259894-eef91600-7161-11eb-9a17-a345d77f21c3.png)

<img src="https://user-images.githubusercontent.com/28832235/108259986-0cc67b00-7162-11eb-85d7-d1195bc65d35.png" width="200">

<img src="https://user-images.githubusercontent.com/28832235/108260050-21a30e80-7162-11eb-8f38-33e514811773.png" width="200">

Following the approach taken by the two former implementations would also mean that new users feel right at home, as the UX would be quite close to the other Spotify clients.

**Comment by xou816** [comment]
closing as this does not seem relevant anymore
