### ISSUE TITLE
[Feature request] Use gstreamer backend

### ISSUE THREAD

**Issue by darkdragon-001** [xou816/spot#600]
Switch to gstreamer backend instead of librespot's low-level backends. This is simpler and supports pipewire out of the box https://github.com/librespot-org/librespot/issues/1121#issuecomment-1436062347.

**Comment by xou816** [comment]
Just a reminder that pipewire has done all the hard work -- I don't have pulseaudio anymore on my system but pipewire replaces it just fine and the pulseaudio backend just works (not an expert, not sure how this works exactly but it seems to)

I am not sure what the benefits of implementing our own gstreamer player would be but sure, it's worth exploring I guess

In the meantime here's a branch with the gstreamer backend piping to pipewire: https://github.com/xou816/spot/tree/600-feature-request-use-gstreamer-backend

I'm curious to have some feedback -- for me the sound is really choppy, but again I'm no expert, I don't know if my install is messed up in some subtle way or if the gstreamer pipeline (`! audioconvert dithering=none ! audioresample ! pipewiresink`) needs further adjustment.

**Comment by darkdragon-001** [comment]
Thanks! How can I test it?

**Comment by xou816** [comment]
You can get a flatpak build here : https://github.com/xou816/spot/actions/runs/4262734945/jobs/7418592559

**Comment by darkdragon-001** [comment]
> You can get a flatpak build here : https://github.com/xou816/spot/actions/runs/4262734945/jobs/7418592559

How can I get it from there?

**Comment by xou816** [comment]
sorry, you'd have to click "summary" from that link, but here this one's more direct : https://github.com/xou816/spot/actions/runs/4262734945 -> a flatpak is at the bottom :)

**Comment by darkdragon-001** [comment]
The backend fails with the following error for me (Ubuntu 22.10):

```
Error from Some("/GstPipeline:pipeline0/GstBin:bin0/GstPipeWireSink:pipewiresink0"): Failed to connect (Some("../src/gst/gstpipewiresink.c(836): gst_pipewire_sink_open (): /GstPipeline:pipeline0/GstBin:bin0/GstPipeWireSink:pipewiresink0"))
thread '<unnamed>' panicked at 'unable to set the pipeline to the `Ready` state: StateChangeError', /run/build/spot/cargo/vendor/librespot-playback-0.4.2/src/audio_backend/gstreamer.rs:126:14
```

**Comment by xou816** [comment]
my bad, it's probably a permission issue with the flatpak! dont know how to fix it yet, I'll comment back later

EDIT: I think this should do the trick: `flatpak run --branch=master --filesystem=xdg-run/pipewire-0 dev.alextren.Spot`

**Comment by darkdragon-001** [comment]
I will try it. Thanks.

Btw.: I can't test it on my Pinephone with aarch64 as the pipeline is only building x86_64.

**Comment by darkdragon-001** [comment]
With your trick it worked :) And both interfaces sound pretty much the same for me. So I think it would be nice to have that option.

**Comment by xou816** [comment]
Nice thanks for testing! I'll polish the pr a little later then
