### ISSUE TITLE
Consider porting UI to Blueprint

### ISSUE THREAD

**Issue by alissonlauffer** [xou816/spot#606]
Blueprint (https://jwestman.pages.gitlab.gnome.org/blueprint-compiler/) greatly improves the readability of `.ui` by reducing the verbosity of the syntax, as well as having better integration with IDEs.

I've done a port of almost all `.ui` files here https://github.com/alissonlauffer/spot/compare/3e620b21344ad4908ed10239ce9bd0d70dee3e96...976fd2d79853bbc12e32b099424c9ea9e4e6b400 if you want to see the diff, but I didn't open a PR because I wanted to know your opinion, and we need to coordinate this task since it would make all PRs that touch `.ui` files conflict.

**Comment by xou816** [comment]
Oh I'm definitely interested in switching to blueprint, its even possible to inline some of the definitions in the rust code with the latest gtk-rs. the PR is most welcome :) CI will help us identify what's possibly missing (I suspect we'll have to add the blueprint-compiler to the flatpak manifest)

if we merge this I'll do my best to help those with open PRs. I will try and think about the best strategy for this (worst case scenrio it's always possible to mix ui files and bp ones)
