### ISSUE TITLE
Login page redesign

### ISSUE THREAD

**Issue by bragefuglseth** [xou816/spot#614]
As discussed in #611, the current login screen of Spot is a little empty and unpolished. There are some new Adwaita widgets we can utilize to make it look more welcoming and professional.

## Initial mockup
![mockup](https://user-images.githubusercontent.com/91388039/221360474-6b35dc6c-1622-4b28-be1e-9d2951f7299a.png)

## Relevant widgets

- [`AdwStatusPage`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.StatusPage.html)
- [`AdwEntryRow`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.EntryRow.html)
- [`AdwPasswordEntryRow`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.PasswordEntryRow.html)
- [`AdwToast`](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.Toast.html)

**Comment by jannuary** [comment]
Let's not use the toast here. Even on the mockup, it covers the UI elements, and also can be missed easily, which is not great for something like that which requires user input.

**Comment by bragefuglseth** [comment]
That’s kinda the point of a toast, though. It can cover UI elements since it’s temporary. We can set it to show for a pretty long duration, or even require the user to dismiss it manually. The input fields also turn red, so I think it’s pretty understandable what has happened. We could consider an alternative, but it seems pretty logical to use a toast in situations like these.

**Comment by jannuary** [comment]
No, the point of a toast is to provide immediate feedback, not error handling.

Per GNOME HIG, 
> Toasts are transient and are therefore best suited to communicating individual events, as opposed to ongoing states. The latter are better served by [info bars](https://developer.gnome.org/hig/patterns/feedback/info-bars.html).

**Comment by bragefuglseth** [comment]
An info bar wouldn't fit here either, as the wrong credentials being entered isn't a persistent state. We could have some text appear on the page, though. Maybe in red beneath the fields?

**Comment by jannuary** [comment]
> Maybe in red beneath the fields?

I was thinking something along these lines, afaik Spotify does that too.

**Comment by bragefuglseth** [comment]
There's already a lot of red here, so I made the label gray instead.

![spot-login-mockup](https://user-images.githubusercontent.com/91388039/221417866-ca4e79ac-4313-4475-9b41-45c4dee00273.png)
