### ISSUE TITLE
Reconsider in-app dark/light mode preference

### ISSUE THREAD

**Issue by bragefuglseth** [xou816/spot#618]
Spot has a preference that lets you choose between dark mode / light mode / follow system. [GNOME's app styling guidelines](https://developer.gnome.org/hig/guidelines/ui-styling.html) say this:

> Most apps should use the standard light UI style by default. However, apps can alternatively choose to use the dark style by default instead. This is primarily recommended for apps which display rich visual content like images or video.
>
> [...]
>
> Per-app style preferences are primarily useful for text editing apps, or apps which users use for long periods of time. In these cases, the style preference can be useful as a way of controlling visual contrast and brightness.

I think we should reconsider if Spot needs this preference. It doesn't do any *harm*, but [every preference has a cost](https://ometer.com/preferences.html), and consequently every preference should have a purpose, a clear reason to exist. I don't see many reasons why a user would want Spot's color scheme to deviate from the rest of their system.

One possible reason a user would want this preference, is because the album art stands more out in dark mode. Even if we consider this enough to warrant a preference, we don't really need an "Always Light" preference. I suggest that we at least simplify this to a toggle for "Always Dark":

![dark-preference](https://user-images.githubusercontent.com/91388039/221385126-d9d1ebe6-723c-48fe-8add-cf1621fa95df.png)

**Comment by XGZepto** [comment]
I think maybe spot could adapt something like this.

![image](https://user-images.githubusercontent.com/38270878/221421291-d295506c-a260-48df-ab69-a60c6f0acfe2.png)

**Comment by bragefuglseth** [comment]
Yes, but what purpose would it serve?

**Comment by xou816** [comment]
Personal opinion on this: what we have at the moment is... fine?

Judging by the large amount of theme-related issues in the past, it's an option people care about, it's easy enough to support the three options, and there are more complex options in the settings anyway. I'd leave it as it is and maybe just change the default to follow the system theme so it's not too jarring the first time you use the app.

**Comment by xou816** [comment]
I'll close this one for now unless there's a good reason to change this if that's fine with you all!
