### ISSUE TITLE
Donation Link! :D

### ISSUE THREAD

**Issue by baconicsynergy** [xou816/spot#62]
I would love to pay you for your software once I am able to switch away from the official Spotify app

**Comment by xou816** [comment]
Hi! :) Thank you for even thinking about doing this! I am not looking for donations right now, but that's very generous of you. If you feel like donating money, you could support one of the many, many projects that make this one possible, such as [gtk-rs](https://opencollective.com/gtk-rs), [gnome](https://www.gnome.org/support-gnome/donate/) or others I'm forgetting!
