### ISSUE TITLE
Provide a pulseaudio playing stream name

### ISSUE THREAD

**Issue by Lyokovic** [xou816/spot#621]
**Describe the bug**
Spot does not provides, or provides an empty name for its playing stream on pulseaudio.

**To Reproduce**
1. Play a song
2. List pulseaudio/pipewire playing stream (with pavucontrol, or wpctl status)
3. The spot stream does not have a name

**Expected behavior**
Provide a meaningful stream name, like "spot".

**General information:**
 - Distribution: archlinux
 - Installation method: AUR
 - Version: 0.4.0

**Comment by XGZepto** [comment]
This should be another one line fix.

![image](https://user-images.githubusercontent.com/38270878/221983490-f960f681-b45e-4046-a836-f52520939279.png)

Depends on the extent of this feature request, we can also provide title, artists, etc, to [PulseAudio](https://freedesktop.org/software/pulseaudio/doxygen/proplist_8h.html#a6aa1ad2d42304ca4bd159935bce2070b).

**Comment by xou816** [comment]
no idea how this works tbh so I'm glad if someone's able to help! :)

**Comment by XGZepto** [comment]
> no idea how this works tbh so I'm glad if someone's able to help! :)

Name could be provided by setting a env var, see the screenshot above. This could be merged to close this issue.

**Comment by xou816** [comment]
Cool, feel free to open a PR I'll have a look! :)

**Comment by Lyokovic** [comment]
Thanks! That was fast!
