### ISSUE TITLE
Minor label changes for the new login screen

### ISSUE THREAD

**Issue by bragefuglseth** [xou816/spot#625]
*Note: This is a low-priority issue, but excellent for newcomers!*

The new login screen is coming together nicely! :tada:

![new-login](https://user-images.githubusercontent.com/6277494/221621201-9debed04-5c10-4e7b-9cc1-20edd600d8b8.png)

I have a few things on the label/string side that I think could be changed:

- The "Login with your Spotify Account" label beneath the title could be justified to the center, to match the rest of the text on the page. I think this just requires adding `justify: center;` to the label in the login blueprint file, but my building skills aren't quite there yet, so I'm not able to test it.

- "Login" should be "Log in". I had to search that up. "Login" is a noun/adjective ("the login window"), "log in" is a verb ("I tried to log in"). Also, "to use Spot" could be changed to "to use the app", so we avoid the slightly awkward repetition of the app name from the "Welcome to Spot" label. Or we could just drop the "to use x" part altogether, as it's kinda implied from the fact that you're trying to log in. This is my suggestion for the label:
    > Log in with your Spotify account. A Spotify Premium subscription is required to use the app.

- I don’t have an easy-to-remember Spotify username, as it was automatically generated when we created our family subscription, but I’m able to log in with my email in the username field. We should specify that that’s possible as well. We can do this by changing the "Username" label to "Username or Email". Another web search reveals that both "E-mail" and "Email" are acceptable writing methods, but Email is the most common one. The most important thing is that it's Header Capitalized in accordance with the HIG :grin: 

I'm going to stop annoying you with my design nitpicking for now, cheers :sweat_smile:

**Comment by xou816** [comment]
> I'm going to stop annoying you with my design nitpicking for now, cheers sweat_smile

I don't mind it no worries :)
