### ISSUE TITLE
Spot does not start

### ISSUE THREAD

**Issue by pkosel** [xou816/spot#631]
**Describe the bug**
Spot does not start.

**General information:**
 - Distribution: NixOS
 - Installation method [e. g. built from source, installed from Flathub...]: Installed from nixpkgs
 - Version [e.g. 0.1.0]: 0.3.3
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
(process:23635): Adwaita-WARNING **: 21:56:09.256: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
thread 'main' panicked at 'assertion failed: !self.ptr.is_null()', /build/spot-0.3.3-vendor.tar.gz/gtk4/src/subclass/widget.rs:1310:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jmc-figueira** [comment]
I can confirm I have the same issue, also on NixOS (unstable), with spot version 0.3.3

**Comment by xou816** [comment]
Hi!
Could you try running with RUST_BACKTRACE=full to get more details? Is there the same issue with 0.4.0?
It's most likely an issue with the version of Gtk not matching the one needed for spot. What version of Gtk do you have?
Also, it's probably a good idea to involve the package maintainer as well, I'm not familiar with NixOS.

**Comment by pkosel** [comment]
I thinks it's GTK 4.8.2. See [spot](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/applications/audio/spot/default.nix#L56) and [gtk4](https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/libraries/gtk/4.x.nix#L66) in the nixpkgs repo. I installed version 0.4.0 locally and can confirm that it is working without any issues. So, it seems to be an issue with the nix package. There's already an open [PR](https://github.com/NixOS/nixpkgs/pull/218129) to bump the version to 0.4.0 which should resolve this issue. Closing.

**Comment by justdie386** [comment]
I seem to be having such an issue on gnome x11 with fedora i installed gtk4 and gtk4-devel and it still says the same

with the rust_backatrace=full i get this
```(process:2): Gdk-WARNING **: 11:17:59.010: No such backend: *
thread 'main' panicked at 'Failed to initialize GTK', src/main.rs:92:36
stack backtrace:
   0:     0x55f1d49ffb3a - <unknown>
   1:     0x55f1d4a2817e - <unknown>
   2:     0x55f1d49fbe05 - <unknown>
   3:     0x55f1d49ff905 - <unknown>
   4:     0x55f1d4a011df - <unknown>
   5:     0x55f1d4a00f1b - <unknown>
   6:     0x55f1d4a01788 - <unknown>
   7:     0x55f1d4286b0a - <unknown>
   8:     0x55f1d4285b06 - <unknown>
   9:     0x55f1d3ed260a - <unknown>
  10:     0x55f1d430fd01 - <unknown>
  11:     0x55f1d4285b73 - <unknown>
  12:     0x55f1d408ab59 - <unknown>
  13:     0x55f1d49f346c - <unknown>
  14:     0x55f1d43111d5 - main
  15:     0x7f359fc2958a - <unknown>
  16:     0x7f359fc2964b - __libc_start_main
  17:     0x55f1d3f2a495 - <unknown>
  18:                0x0 - <unknown>
```
