### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by smups** [xou816/spot#646]
**Describe the bug**
Some Icons are missing in the UI.

**To Reproduce**
Steps to reproduce the behaviour:
1. Fresh install of spot from flatpak
2. Open app -> icons are missing

**Expected behavior**
Icons should be there.

**Screenshots**
Skip buttons missing:
![afbeelding](https://user-images.githubusercontent.com/56522208/231714052-e7559fd8-780c-4109-a03b-3a29255f10e6.png)

Saved tracks icon missing:
![afbeelding](https://user-images.githubusercontent.com/56522208/231714163-8c0187c6-8c4c-48aa-96ba-ad408c97ecb7.png)

Playlists icon missing:
![afbeelding](https://user-images.githubusercontent.com/56522208/231714269-7f5ff16f-de2a-4c64-ac60-1075c620be00.png)

Idk what this is supposed to be but it is missing:
![afbeelding](https://user-images.githubusercontent.com/56522208/231715062-4680ca2c-76d4-45a1-85a3-4ae37d8ef63a.png)

**General information:**
 - Distribution: Fedora 38 (beta), GNOME 44
 - Installation method: Installed from flathub
 - Version: 0.4.0
 - Device used: Framework Laptop 11th gen

**Comment by xou816** [comment]
Given that even the minimize icon is mssing in the last picture, I suspect something is broken with your install (which I believe is customized, even the fonts don't look like the defaults). Do you have similar issues with other Gtk/libadwaita apps installed as flatpaks?

**Comment by smups** [comment]
> Do you have similar issues with other Gtk/libadwaita apps installed as flatpaks?

Nope. I have most stuff installed as flatpaks on my laptop, don't have issues with other gtk apps.

> even the fonts don't look like the defaults

I changed the default system font in GNOME tweaks. I don't use any shell extensions though.

> which I believe is customized

I just typed `flatpak install spot` in the terminal, I haven't messed with anything else.

Just to be sure, I installed spot from the `app/dev.alextren.Spot/x86_64/stable` option in the lil menu that flatpak gives when you type `flatpak install spot`, that's the right one, right?

I tried re-installing spot, but the issue persists.

**Comment by xou816** [comment]
Thanks for the details! You do have the right version, but since those icons are provided by the system I still suspect the issue lies somewhere else than in spot.

Could you check which exact version of the GNOME runtime you have installed via flatpak? 

Could you try running https://flathub.org/apps/details/org.gnome.design.IconLibrary for instance as well?

**Comment by smups** [comment]
> Could you check which exact version of the GNOME runtime you have installed via flatpak?

I ran `flatpak search org.gnome.Platform` which came up with three results:
![afbeelding](https://user-images.githubusercontent.com/56522208/232718505-469477d6-a685-4ca5-9461-ef95ac1c7e28.png)

> Could you try running https://flathub.org/apps/details/org.gnome.design.IconLibrary for instance as well?

I found two icons that don't work 👀 
- `video-decode-symbolic` (that question mark thingy from before)
- `goa-account-symbolic` (blank)
![afbeelding](https://user-images.githubusercontent.com/56522208/232719214-7c27f896-0045-4e0c-89d4-42ed1e92d134.png)
![afbeelding](https://user-images.githubusercontent.com/56522208/232719799-9f632fa0-e9e4-41ae-878a-73975e9ff55c.png)

**Comment by smups** [comment]
Thanks for the help btw!

**Comment by xou816** [comment]
No worries, hopefully we'll get to the bottom of it! :)

Can you try `flatpak remove org.gnome.Platform/x86_64/43`? Don't proceed, it's just to confirm that it warns you that spot depends on it. Also, I'd be interested in seeing what other apps you have running on top of the same GNOME platform, maybe that'll help.

(sample output for me: )
```
flatpak remove org.gnome.Platform/x86_64/43
Info: applications using the runtime org.gnome.Platform branch 43:
   ... dev.alextren.Spot, ... org.gnome.design.AppIconPreview, org.gnome.design.IconLibrary
```

So these things might help with the investigation. In the meantime, you can try some of these things as well:
- installing a dev build, for instance the artifact here : https://github.com/xou816/spot/actions/runs/4724842020 ;
- having a different flathub remote setup; if you have a user-level flathub remote (see `flatpak remotes`), you could try adding a system flathub remote and install spot there, and conversely if you have a system flathub remote, you could try and setup a flathub user remote. Having a clean install could help us spot (ah!) an issue.

**Comment by smups** [comment]
I ran (without proceeding) that command and got:
![afbeelding](https://user-images.githubusercontent.com/56522208/234045767-0b589b1a-e388-4eaf-9336-31724eb176c4.png)
Interestingly, the icon test app uses GNOME 44 on my install:
![afbeelding](https://user-images.githubusercontent.com/56522208/234045875-6fda8991-e350-4759-86c5-b5aa6e2443aa.png)
When I try to manually install that artefact by running flatpak install I get an error:
![afbeelding](https://user-images.githubusercontent.com/56522208/234047658-fc99f0f3-8c4b-4def-a32c-f5bf2a946bac.png)
> having a different flathub remote setup; if you have a user-level flathub remote (see flatpak remotes), you could try adding a system flathub remote and install spot there, and conversely if you have a system flathub remote, you could try and setup a flathub user remote. Having a clean install could help us spot (ah!) an issue.

I don't know what this means, sorry! I think I'm still using Fedora's default setup for remotes (I updated from F35 through F38 on this machine, idk if that matters)
![afbeelding](https://user-images.githubusercontent.com/56522208/234048219-e8488df9-8417-41a5-a463-87a753123213.png)

**Comment by xou816** [comment]
> I ran (without proceeding) that command and got: ![afbeelding](https://user-images.githubusercontent.com/56522208/234045767-0b589b1a-e388-4eaf-9336-31724eb176c4.png)

Okay, can you run some of the applications in that first list? I'm interested in seeing if any of these have similar icon issues!

> When I try to manually install that artefact by running flatpak install I get an error: ![afbeelding](https://user-images.githubusercontent.com/56522208/234047658-fc99f0f3-8c4b-4def-a32c-f5bf2a946bac.png)

Oh right, might need to add the GNOME nightly repo I guess (if you don't mind trying): 
`flatpak remote-add --if-not-exists gnome-nightly https://nightly.gnome.org/gnome-nightly.flatpakrepo`

> I don't know what this means, sorry! I think I'm still using Fedora's default setup for remotes (I updated from F35 through F38 on this machine, idk if that matters) ![afbeelding](https://user-images.githubusercontent.com/56522208/234048219-e8488df9-8417-41a5-a463-87a753123213.png)

Right, my bad! So it looks like you have a system level install, but you can also have a per-user install that does not require elevated privileges. Again I'm grasping at straws here but maybe you can setup a user remote so we start with a clean slate:

`flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo` (note the --user flag)

and then you can install Spot again

`flatpak install --user flathub dev.alextren.Spot`

**Comment by jannuary** [comment]
This is a common bug on GTK4 when one uses icon sets that do not have these specific icons and do not inherit from adwaita-icon-theme.

There's not much Spot can do here, outside of bundling the system icons.

**Comment by smups** [comment]
Thanks that did it! I had completely forgotten that changing the app icon theme also changes all the other icons.

Thanks again for the help.

**Comment by xou816** [comment]
> This is a common bug on GTK4 when one uses icon sets that do not have these specific icons and do not inherit from adwaita-icon-theme.
> 
> There's not much Spot can do here, outside of bundling the system icons.

forgot to answer but thanks for chiming in and being spot on (ah!) with the answer. didn´t realize there was a custom icon theme at play here!!
