### ISSUE TITLE
Spot hides when closed, no tray icon in top bar

### ISSUE THREAD

**Issue by perroboc** [xou816/spot#647]
**Describe the bug**
The app doesn't have a tray / top bar icon. Closing the app hides it from the dock, but since it doesn't have an icon in the bar, the only way to bring it to the front is by opening again. 

**To Reproduce**
1. Run the app
2. Play a song
3. Close spot
4. No tray icon

**Expected behavior**
I expect a tray icon to be there, so I can see what's playing, change tracks, or open Spot again.

**General information:**
 - Distribution: Pop!_OS 22.04 LTS
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.4.0
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
```

**Additional context**

**Comment by bragefuglseth** [comment]
Spot uses MPRIS to show what's playing and enable playback control. You should be able to see it in the notifications panel.

**Comment by XGZepto** [comment]
the standard behaviour after gnome 43 should be self-report as background app?

**Comment by ZtereoHYPE** [comment]
![image](https://user-images.githubusercontent.com/57519662/236254961-cb58b0e3-5291-4a8c-8073-693a5d1e76c9.png)
spot does indeed appear in the background apps in gnome 44

**Comment by Caliel666** [comment]
can this be reopened? in some other setups it does not appear in the tray bar and besides, would be really nice to have a option in the preferences to choose if you want it to run in the background or not, also ask the user when they close for the first time, it's really annoying not being able to control that

**Comment by bragefuglseth** [comment]
Those other setups should be updated to take advantage of the new freedesktop standards. It’s fully possible for them to replicate a behavior similar to an old tray icon with Spot if they use the xdg-background portal to add entries to the tray. I believe that’s a better long-term solution than trying to make Spot support the current, flawed tray icon method.

**Comment by benjamin051000** [comment]
This may be out of scope, but there's no tray icon on KDE either.
