### ISSUE TITLE
Build failure?

### ISSUE THREAD

**Issue by Barbarossa93** [xou816/spot#66]
**Describe the bug**
Following the manual build instructions in the README, it seems like everything ran fine. However, I get this message at the end:
```
[1/2] Generating spot_gresource with a custom command
```
It seems like there's suppose to be a second step that never happens? When I go directly to `spot/target/src` and issue `./spot` I get the following error message:
```
thread 'main' panicked at 'Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/home/barbarossa/.local/share/spot/spot.gresource”: open() failed: No such file or directory" }', src/main.rs:55:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Install dependencies
run meson and then ninja commands
try to run the spot executable

**Expected behavior**
Running the spot executable should have everything running fine

**Screenshots**

**General information:**
 - Distribution: Arch Linux
 - Installation method [e. g. built from source, installed from Flathub...]: Source
 - Version [e.g. 0.1.0]: 0.1.7 (git)
 - Device used [e. g. desktop, phone...]: desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
thread 'main' panicked at 'Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/home/barbarossa/.local/share/spot/spot.gresource”: open() failed: No such file or directory" }', src/main.rs:55:10
stack backtrace:
   0:     0x558c5e7096b0 - std::backtrace_rs::backtrace::libunwind::trace::hc8b42b9686bc0d07
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x558c5e7096b0 - std::backtrace_rs::backtrace::trace_unsynchronized::h839b1b3e096c7094
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558c5e7096b0 - std::sys_common::backtrace::_print_fmt::h9f36d7c0c192ca75
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558c5e7096b0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::haad7d3f8925bad2e
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x558c5e72d2bc - core::fmt::write::h7239b2f9a99358fb
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/fmt/mod.rs:1078:17
   5:     0x558c5e702055 - std::io::Write::write_fmt::hf8c959f904cf1571
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/io/mod.rs:1517:15
   6:     0x558c5e70b955 - std::sys_common::backtrace::_print::h2c2d9abbb61e574c
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x558c5e70b955 - std::sys_common::backtrace::print::h1362a4690ddc5737
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x558c5e70b955 - std::panicking::default_hook::{{closure}}::h250793a7822001b5
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:208:50
   9:     0x558c5e70b4aa - std::panicking::default_hook::h888581adc5c27c77
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:225:9
  10:     0x558c5e70c0f1 - std::panicking::rust_panic_with_hook::h77f2fa3bf09efb3b
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:591:17
  11:     0x558c5e70bc37 - std::panicking::begin_panic_handler::{{closure}}::h3cafa059e2851c7f
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:497:13
  12:     0x558c5e709b6c - std::sys_common::backtrace::__rust_end_short_backtrace::h46c04e54576d0893
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x558c5e70bb99 - rust_begin_unwind
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:493:5
  14:     0x558c5e72aa11 - core::panicking::panic_fmt::hb1f208d1d41afb98
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/panicking.rs:92:14
  15:     0x558c5e72a833 - core::option::expect_none_failed::h5d536c1ceba4b362
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/option.rs:1268:5
  16:     0x558c5d2e1ea0 - core::result::Result<T,E>::expect::h99b4e43ee2788aaf
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/result.rs:933:23
  17:     0x558c5d23a723 - spot::setup_gtk::h6f1c5b8f6b5c75ad
                               at /home/barbarossa/spot/src/main.rs:54:15
  18:     0x558c5d23a30c - spot::main::h151af790995fc8bb
                               at /home/barbarossa/spot/src/main.rs:19:5
  19:     0x558c5d21cf6b - core::ops::function::FnOnce::call_once::hd74b7030723ffbc4
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/ops/function.rs:227:5
  20:     0x558c5d382dde - std::sys_common::backtrace::__rust_begin_short_backtrace::h4067052d650c56ea
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x558c5d33fe11 - std::rt::lang_start::{{closure}}::h736c908f18ab0bbb
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/rt.rs:66:18
  22:     0x558c5e70c517 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h5a27e92186d531b9
                               at /build/rust/src/rustc-1.50.0-src/library/core/src/ops/function.rs:259:13
  23:     0x558c5e70c517 - std::panicking::try::do_call::h8d3a36b2860fc4e2
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:379:40
  24:     0x558c5e70c517 - std::panicking::try::hefdcf6df93f20790
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panicking.rs:343:19
  25:     0x558c5e70c517 - std::panic::catch_unwind::h36ddc1c42bb74870
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/panic.rs:396:14
  26:     0x558c5e70c517 - std::rt::lang_start_internal::ha6cc4bb09c664b1a
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/rt.rs:51:25
  27:     0x558c5d33fde7 - std::rt::lang_start::h1a064a3b694e24e5
                               at /build/rust/src/rustc-1.50.0-src/library/std/src/rt.rs:65:5
  28:     0x558c5d23a97a - main
  29:     0x7f4be5b97b25 - __libc_start_main
  30:     0x558c5d1d30be - _start
  31:                0x0 - <unknown>
```

**Additional context**
Can this only be used for Gnome? I'm trying to build/run it on Qtile

**Comment by Barbarossa93** [comment]
Turns out I just had to copy the gresource file over to .local/share/spot/

My bad!

**Comment by xou816** [comment]
Hi @Barbarossa93 , no worries! Looks like a bug to me still! Ninja should do that step for you. For instance, my build log looks like this by the end:

```
    Finished dev [unoptimized + debuginfo] target(s) in 31.34s
[1/2] Installing files.
Installing subdir <home>/Dev/spot/data/hicolor to <home>/.local/share/icons/hicolor
Installing <home>/Dev/spot/data/hicolor/scalable/apps/dev.alextren.Spot.svg to <home>/.local/share/icons/hicolor/scalable/apps
Installing <home>/Dev/spot/data/hicolor/128x128/apps/dev.alextren.Spot.png to <home>/.local/share/icons/hicolor/128x128/apps
Installing <home>/Dev/spot/data/hicolor/64x64/apps/dev.alextren.Spot.png to <home>/.local/share/icons/hicolor/64x64/apps
Installing src/spot.gresource to <home>/.local/share/spot
Installing src/spot to <home>/.local/bin
This file does not have an rpath.
This file does not have a runpath.
Installing <home>/Dev/spot/data/dev.alextren.Spot.desktop to <home>/.local/share/applications
Installing <home>/Dev/spot/data/dev.alextren.Spot.appdata.xml to <home>/.local/share/appdata
Installing <home>/Dev/spot/data/dev.alextren.Spot.gschema.xml to <home>/.local/share/glib-2.0/schemas
Running custom install script '<home>/Dev/spot/build-aux/meson/postinstall.py'
Updating icon cache...
Updating desktop database...
Compiling GSettings schemas...
```

Which installation prefix did you use? Could there be a permission issue that prevents installing the files?

**Comment by Barbarossa93** [comment]
I just used the default `$HOME/.local` as given in the README. Looking at your build log, it looks to me like your script calls for `$HOME/Dev/spot/...` Shouldn't it just be calling within the spot directory that I cloned? So it should look more like `$HOME/spot/...`, but even better, `./data/...`

**Comment by xou816** [comment]
Yes, this Dev/spot thingy is where the repo is cloned, so everything is in order here! And you can see that spot.gresource is being copied to .local/share/spot, which is expected but apparently not happening for you. Could you share relevant part of your build logs?

**Comment by olback** [comment]
> Turns out I just had to copy the gresource file over to .local/share/spot/
> 
> My bad!

Instead of keeping track of a gresources file, include it in the spot binary itself like this:
```rust
let glib_resource_bytes = glib::Bytes::from_static(include_bytes!("path/to/resource/spot.gresource"));
let resources = gio::Resource::new_from_data(&glib_resource_bytes).expect("Failed to load resources");
gio::resources_register(&resources);
```

**Comment by xou816** [comment]
I guess both approaches have their perks, I'd rather hear more from @Barbarossa93 first before changing this!

**Comment by Barbarossa93** [comment]
> Yes, this Dev/spot thingy is where the repo is cloned, so everything is in order here! 

Woops! My bad.
> Could you share relevant part of your build logs?

So I ended up removing my manual installation (which was incomplete anyway) and just installed from the AUR instead. [Here's](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=spot-client) the PKGBUILD for how it was built. This worked flawlessly. So maybe update the README to follow similar instructions? In any case, I do agree with @olback, I think the fewer files strewn across the system the better

**Comment by xou816** [comment]
I am on Arch as well, didn't know someone had contributed a PKGBUILD, this is really cool! Thank you @dpeukert I guess, I should add this to the README!

Well, the PKGBUILD does pretty much as instructed, it is not doing a manual copy of the resource file either, I have no clue what went wrong with your install, sorry :/ meson is supposed to handle everything for you. I am closing this now unless you want to install it manually again!

**Comment by mattlennon3** [comment]
Hi, I'm getting the same error as OP, I have ran the build instructions in the readme which succeed... But how do I actually run my build version of spot? I try `cargo run`, or just `./target/src/spot` and get the same:
> thread 'main' panicked at 'Could not load resources: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/home/matt/.local/share/spot/spot.gresource”: open() failed: No such file or directory" }', src/main.rs:66:10

Should I be adding the pkgbuild to the root directory and running it? I'd like to be able to have this running locally so I can help contribute or just learn more about rust. Thanks :)

**Comment by xou816** [comment]
Hi! Would you mind sharing more details? Exact build commands you used, and log ouput (with any sensitive information removed)

**Comment by mattlennon3** [comment]
Hey, yeah sure, I just did a fresh clone then ran the below:
`meson target -Dbuildtype=debug -Doffline=false --prefix="$HOME/.local"`
`ninja -C target`
The last 2 lines of the ninja output are:
> Finished dev [unoptimized + debuginfo] target(s) in 1m 53s
> [1/2] Generating spot_gresource with a custom command

It seems to have built successfully, but there's no more than that, should there be a [2/2]? 

Then after, I don't really know what to run to launch Spot. Is it just `./target/src/spot`? If I do that, I get the gresource error posted above. Cheers

**Comment by xou816** [comment]
Oh! I'm dumb, just realized what's wrong; it should be ninja install -C target, otherwise the install step (that installs the gresource file among other things) wouldn't be installed. I'll update the README! This is probably what was happening to @Barbarossa93 as well.

**Comment by mattlennon3** [comment]
Thanks @xou816! That has resolved the issue for me :) 

It might be worth mentioning `$HOME/.local/bin/` has to be in your path. I think it's done by default on Ubuntu etc but not arch.

**Comment by xou816** [comment]
Closing this for now, hoping the new instructions are clearer! (and correct too :D )
