### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ghost** [xou816/spot#666]
The application does not let me login, at first I though this was a strange issue totally at random, i tried with everything and I just saw that whenever I tried running it with "flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot" it says: "Spotify API error: No token". Is this currently being solved or is it a thing that I need to fix.

**Comment by Nandru86** [comment]
October 12 and it gave me the same error upon start:

![imagen](https://github.com/xou816/spot/assets/23064809/bf83cf24-c85c-401a-a9e2-a37796c982af)

**Comment by le0flo** [comment]
damn

**Comment by Diegovsky** [comment]
Hey there! I'm looking into it right now. Also, is this still happening?

On an unrelated note: Very fitting for the issue number.

**Comment by Diegovsky** [comment]
By the way: the error does print in my console, but it does not prevent me from logging in.

**Comment by lostipod** [comment]
Getting the same thing here on Debian testing on GNOME with current flatpak v0.4.0.

**Comment by Diegovsky** [comment]
Could be fixed in the new version. If I were to guess, `librespot`'s token is expired. It's kinda on Spotify.

However, a new version is to be released on flathub which is running just fine on my machine. I'll be closing this spooky issue for now, but do reopen it if did not solve your problem!
