### ISSUE TITLE
Broken icons on Xubuntu Lunar

### ISSUE THREAD

**Issue by ghost** [xou816/spot#674]
Already tried using different icon themes, but it stay broken.

![Captura de tela_2023-08-03_07-56-00](https://github.com/xou816/spot/assets/128207718/0a03f230-6b7d-48d0-af40-620dd024aff4)

**Comment by Diegovsky** [comment]
Interesting. Is this installed using flatpak ?

**Comment by ghost** [comment]
> Interesting. Is this installed using flatpak ?

Yes.

**Comment by Diegovsky** [comment]
Ok, thanks for your report. This is definetely unexpected. 

If someone wants to take a look at this, I would recommend spinning up a xubutu VM and installing spot via flatpak.

For now, I'm kinda busy with college, but I will take a look at it once possible.

**Comment by ghost** [comment]
Found out that you just need to use FlatSeal to give it access to the icons folder in your system.
I don't even use Spotify anymore btw, just found it out solving the same problem for another application.
