### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by deusnovus** [xou816/spot#676]
I apologize for the arbitrary question, I just noticed there hasn't been any activity on Github for 2 months and there are a lot of PR waiting to be merged, so I was wondering if this project has been abandoned.

Despite being in its infancy and missing a lot of core features I unfortunately end up using the official app for, I use it daily because of how well the libadwaita design blends with the rest of my GNOME environment, so I hope to see Spot becoming a fully-fledged experience in the future.

**Comment by dontlookherepls** [comment]
🤷‍♀️

**Comment by Diegovsky** [comment]
No. Speaking for myself only: I'm busy with college related stuff and haven't been able to interact here much. Please, take a look at #591 for more information.

Thank you for taking interest in Spot :)
