### ISSUE TITLE
Cover buttons shouldn't take up entire width

### ISSUE THREAD

**Issue by hwittenborn** [xou816/spot#678]
This is a bit of a personal choice thing, but I was thinking it's what was intended.

Cover buttons currently take up the entire available vertical width:

![image](https://github.com/xou816/spot/assets/74838472/5512b41e-6bf0-49cf-a777-c77c7699fbfd)

Using the GTK debugger, it appears that setting `valign` to `GTK_ALIGN_START` fixes the issue:

![image](https://github.com/xou816/spot/assets/74838472/7316fcf2-9ef3-490d-ab77-90619086b8b5)

I can open a PR for this if needed (it looks like all that would need changed is `valign` being set at https://github.com/xou816/spot/blob/cbd3140263e07e31cb5a742d77e850106073b410/src/app/components/album/album.blp#L5-L7), but I thought I'd get it discussed here first.

**Comment by hwittenborn** [comment]
Nevermind, it looks like https://github.com/xou816/spot/pull/677 fixes the issue just fine.

**Comment by Diegovsky** [comment]
Not a personal preference, it looks objectively better with the fix applied!
