### ISSUE TITLE
Running on kde desktops.

### ISSUE THREAD

**Issue by basta** [xou816/spot#68]
Hi. 
I know this may be out of scope, but how difficult would be running this on kde desktop? 
If I install the flatpak it has tons of gnome dependencies, which I understand and I would be willing to install, just unsure if it will break my system. 

(Running KDE Fedora)
Thanks

**Comment by xou816** [comment]
Hi!
I don't think it would break your system, at least I can't see why it would. It depends on the Gnome SDK, but this shouldn't lead to any conflict :)

**Comment by basta** [comment]
I can confirm that it works. 
The flatpak install had nearly a GB of dependencies, but I doubt you can do anything about that.
And it's missing an icon.

Minor inconveniences for using this awesome app.
Thanks

**Comment by xou816** [comment]
Cool! Glad this worked :) the upside is you won't feel bad about installing other gtk-based apps now :)
