### ISSUE TITLE
[PACKAGING] Add Repology to README

### ISSUE THREAD

**Issue by konstantintutsch** [xou816/spot#680]
Hi,

I'd recommend to add the [Repology packaging status badge](https://repology.org/project/spot-client/badges) to the README to make it easier for users to install spot.

```md
![Packaging status](https://repology.org/badge/vertical-allrepos/spot-client.svg)](https://repology.org/project/spot-client/versions)
```

**Comment by Diegovsky** [comment]
Thank you, this is a good idea :)

**Comment by Diegovsky** [comment]
Done in maintenance branch!
