### ISSUE TITLE
Login doesn't allow user to tab between inputs

### ISSUE THREAD

**Issue by Douile** [xou816/spot#70]
**Describe the bug**
Login doesn't allow tabbing between fields

**To Reproduce**
1. Go to login screen
2. Select username
3. Active element doesn't change

**Expected behavior**
Tab switches user selection between username, password and login fields

**General information:**
 - Distribution: Arch
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.7

**Comment by xou816** [comment]
Good catch, thanks! I don't how to implement proper tab navigation with gtk, if anyone knows why it breaks here I'm all ears! 

I'll investigate on my end as well when I have some time.

**Comment by Douile** [comment]
It looks like you use `ContainerExt::set_focus_chain` from a quick search https://gtk-rs.org/docs/gtk/trait.ContainerExt.html#tymethod.set_focus_chain

**Comment by Douile** [comment]
Never mind, that is deprecated.

**Comment by Douile** [comment]
On the same topic, the enter key doesn't login the form when username or password entry is selected. Not sure whether that should be a different issue.

**Comment by xou816** [comment]
I'm fine with keeping it here! There's something I'm missing about how focus works in dialogs... hmm..

**Comment by Douile** [comment]
It's weird because keyboard navigation works on every other window (except for the shuffle missing can-focus).

**Comment by Douile** [comment]
Oh, I might have fixed the tab navigation but screwing around with glade.
```
diff --git a/src/window.ui b/src/window.ui
index bb4a71c..ea528d7 100644
--- a/src/window.ui
+++ b/src/window.ui
@@ -512,7 +512,7 @@ Douile</property>
     </child>
   </object>
   <object class="GtkDialog" id="login">
-    <property name="can-focus">True</property>
+    <property name="can-focus">False</property>
     <property name="title" translatable="yes">Spot</property>
     <property name="modal">True</property>
     <property name="window-position">center-on-parent</property>
@@ -522,7 +522,7 @@ Douile</property>
     <property name="transient-for">window</property>
     <child internal-child="vbox">
       <object class="GtkBox">
-        <property name="can-focus">True</property>
+        <property name="can-focus">False</property>
         <property name="margin-start">8</property>
         <property name="margin-end">8</property>
         <property name="margin-top">8</property>
```
By having the dialog and box have can-focus set to true it seems GTK switches focus to the wrong things.

**Comment by Douile** [comment]
This doesn't do the enter to submit though, it seems like that has to by connecting the key-press event manually

**Comment by xou816** [comment]
fantastic :o I did not even realize can-focus was true for these! I'll have a look at the PR!
