### ISSUE TITLE
Artist Page Error

### ISSUE THREAD

**Issue by idhelman** [xou816/spot#700]
**Describe the bug**
Cannot view an artists page.  Not sure if this is a new bug or not, but thanks for the help!  I have been enjoying using this UI.

**To Reproduce**
1. Launch spotd
2. Go to any artist page
3. Error

**Expected behavior**
View an Artists Page

**Screenshots**
![Screenshot from 2024-01-31 10-37-40](https://github.com/xou816/spot/assets/54872834/4f10f7f5-e794-4967-93b3-37fdecaad9c7)

**General information:**
 - Distribution: Ubuntu 22.04
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]:
 - Device used [e. g. desktop, phone...]:

**Stack trace:**
130 idhelman@precision3480a:~$ flatpak run dev.alextren.Spot

(process:2): Adwaita-CRITICAL **: 10:35:32.743: adw_leaflet_set_visible_child: assertion 'contains_child' failed
[src/api/cached_client.rs:222] &cache_key = "artist_5QdyldG4Fl4TPiOIeMNpBZ.json"
[src/api/cached_client.rs:222] e = Error("invalid type: floating point `640`, expected u32", line: 1, column: 428)
[2024-01-31T15:35:57Z ERROR spot::app::components] Spotify API error: invalid type: floating point `640`, expected u32 at line 1 column 428

```

**Additional context**
N/A

**Comment by chromosome** [comment]
I have the same issue. Installed it from AUR.

OS: Arch Linux x86_64 
Kernel: 6.7.2-arch1-1 
DE: GNOME 45.3
DS: Wayland
WM: Mutter 
CPU: AMD Ryzen 7 1700 (16) @ 3.000GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 9703MiB / 15941MiB

**Comment by valerierx** [comment]
https://github.com/QPixel/spot/tree/qpixel/fix/artists-page

**Comment by idhelman** [comment]
Hi @VxlerieUwU thanks for the link!  I previously installed this application from FlatPak.  How would I go about utilizing the new fork you updated?  Thanks for your assistance.

**Comment by idhelman** [comment]
Closing this issue!  It's working for me now.  Thanks so much :)
