### ISSUE TITLE
Sign/Log-in does not work

### ISSUE THREAD

**Issue by busterbeam** [xou816/spot#709]
I opened a fresh Flatpak install of Spot and entered my account details but clicking "Log-in" did nothing even after a wait period (no progress bar).

**To Reproduce**
1. Open New Install of Spot
2. Enter Account details
3. Click Log In
4. See nothing happen

**Expected behavior**
I expected to have access to my spotify

**Screenshots**
There really isn't much to see, but I would be willing to provide images if needs be

**General information:**
 - Linux _ 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux
 - Installation method: GNOME software center as a flatpak
 - Version [e.g. 0.1.0]: 0.4.0 (according to the software center
 - Device used [e. g. desktop, phone...]: Thinkpad X2xx

**Stack trace:**
```
[2024-03-12T13:40:20Z ERROR spot::app::batch_loader] Spotify API error: No token
```
Quick google search. Your application ID/token has expired?  Some admin guy needs to set this up again?

**Additional context**
I hate Spotify's Account management system as well, but I guess there is not much you can do about that

**Comment by maxgreene123** [comment]
Im also having this same issue

**Comment by busterbeam** [comment]
> Im also having this same issue

If you can, do provide your logs in details. As it may show its not the same issue. Also is this for the same device or different?

**Comment by maxgreene123** [comment]
I actually fixed the issue it was something on my end with my network firewall and not the spot client.

**Comment by busterbeam** [comment]
> I actually fixed the issue it was something on my end with my network firewall and not the spot client.

hmm, yeah tried to sign again today, it worked.  would be great to know what the specific issue was, I have not changed my network firewalls at all since (as far as I'm aware)
