### ISSUE TITLE
About window doesn't close with close button

### ISSUE THREAD

**Issue by Douile** [xou816/spot#71]
**Describe the bug**
Close button doesn't close the about tab

**To Reproduce**
1. Go to about tab (burger menu -> about)
2. Press the close button
3. See error

**Expected behavior**
The about window closes

**General information:**
 - Distribution: Arch
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.7
 - Device used [e. g. desktop, phone...]: qtile

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
No errors outputted

**Comment by xou816** [comment]
Hi! Thanks for the report.
I am not familiar with qtile, but perhaps it draws its own window decorations for modals as well? In which case I might be mishandling some signal. I'll have a look!

**Comment by Douile** [comment]
@xou816 wow quick response, its a tiling WM so there are no window decorations: that might be what is causing the issue. The keybinding to close windows works with closing it.

**Comment by Douile** [comment]
@xou816 
https://github.com/xou816/spot/commit/d383eb555bf69c430a32e3c7e40c69bc68c2db6b didn't fix, however I tested with the following and it fixed.

```rust
        about.connect_response(
            clone!(@weak about => @default-return (), move |_, _| {
                about.hide();
            }),
        );
```

This does require adding DialogExt to imports
```rust
use gtk::{AboutDialogExt, DialogExt, MenuButtonExt, WidgetExt};
```

Should I PR?

**Comment by xou816** [comment]
Ah, thank you for testing! :) Yes please, your PR is welcome :)
