### ISSUE TITLE
Build Issue: Error compiling zvariant

### ISSUE THREAD

**Issue by jakehubbard** [xou816/spot#72]
**Describe the bug**
Error compiling zvariant v2.5.0 during the build

**To Reproduce**
Perform step provided in the README

**General information:**
 - Distribution: Arch Linux
 - Installation method: Manual Build
 - Version: 0.1.7
 - Device used: Desktop

**Stack trace:**
Compiling zvariant v2.5.0
     Running `rustc --crate-name zvariant --edition=2018 /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="enumflags2"' --cfg 'feature="gvariant"' -C metadata=6f0698eebe4c860f -C extra-filename=-6f0698eebe4c860f --out-dir /home/jake/build/build_dir/target/debug/deps -L dependency=/home/jake/build/build_dir/target/debug/deps --extern byteorder=/home/jake/build/build_dir/target/debug/deps/libbyteorder-dcc601046b163967.rmeta --extern enumflags2=/home/jake/build/build_dir/target/debug/deps/libenumflags2-5398423020f18af4.rmeta --extern serde=/home/jake/build/build_dir/target/debug/deps/libserde-222356bde02ec4c1.rmeta --extern zvariant_derive=/home/jake/build/build_dir/target/debug/deps/libzvariant_derive-9e206d956df11ffd.so --cap-lints allow`
error: unexpected token: `0.`
  --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
   |
52 |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
   |             -----^^
   |             |    |
   |             |    unexpected token
   |             help: try parenthesizing the first index: `(self.0).`
...
73 |     serialize_basic!(serialize_bool(bool) write_u32(u32));
   |     ------------------------------------------------------ in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
  --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
   |
52 |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
   |             -----^^
   |             |    |
   |             |    unexpected token
   |             help: try parenthesizing the first index: `(self.0).`
...
75 |     serialize_basic!(serialize_i8(i8) write_i16(i16));
   |     -------------------------------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
  --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
   |
52 |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
   |             -----^^
   |             |    |
   |             |    unexpected token
   |             help: try parenthesizing the first index: `(self.0).`
...
76 |     serialize_basic!(serialize_i16(i16) write_i16);
   |     ----------------------------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
  --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
   |
52 |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
   |             -----^^
   |             |    |
   |             |    unexpected token
   |             help: try parenthesizing the first index: `(self.0).`
...
77 |     serialize_basic!(serialize_i64(i64) write_i64);
   |     ----------------------------------------------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
   --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
    |
52  |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
    |             -----^^
    |             |    |
    |             |    unexpected token
    |             help: try parenthesizing the first index: `(self.0).`
...
100 |     serialize_basic!(serialize_u16(u16) write_u16);
    |     ----------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
   --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
    |
52  |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
    |             -----^^
    |             |    |
    |             |    unexpected token
    |             help: try parenthesizing the first index: `(self.0).`
...
101 |     serialize_basic!(serialize_u32(u32) write_u32);
    |     ----------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
   --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
    |
52  |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
    |             -----^^
    |             |    |
    |             |    unexpected token
    |             help: try parenthesizing the first index: `(self.0).`
...
102 |     serialize_basic!(serialize_u64(u64) write_u64);
    |     ----------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
   --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
    |
52  |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
    |             -----^^
    |             |    |
    |             |    unexpected token
    |             help: try parenthesizing the first index: `(self.0).`
...
104 |     serialize_basic!(serialize_f32(f32) write_f64(f64));
    |     ---------------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: unexpected token: `0.`
   --> /home/jake/.cargo/registry/src/github.com-1ecc6299db9ec823/zvariant-2.5.0/src/dbus/ser.rs:52:18
    |
52  |             self.0.$write_method::<B>(v as $as).map_err(Error::Io)
    |             -----^^
    |             |    |
    |             |    unexpected token
    |             help: try parenthesizing the first index: `(self.0).`
...
105 |     serialize_basic!(serialize_f64(f64) write_f64);
    |     ----------------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by xou816** [comment]
Hi! I can't reproduce this issue. What version of the rust toolchain are you using?

**Comment by jakehubbard** [comment]
That was the issue. I had a native Rust installation from the Arch repository. I installed the rust toolchain from https://www.rustup.rs/ and was able to build.

Thank you
