### ISSUE TITLE
Cannot Log Back In

### ISSUE THREAD

**Issue by LSeelig** [xou816/spot#728]
**Describe the bug**
I opened Spot today. Playback didn't work. Reopened it, and it logged me out. I can't log back in. I can only reproduce what happens when I open it now (since it logged me out).

**To Reproduce**
1. Open Spot
2. Enter email (or username) and password
3. See error

**Expected behavior**
I am logged in.

**Screenshots**
![image](https://github.com/user-attachments/assets/51effb71-2fb5-41d9-90d3-d4f9534a4fb4)

**General information:**
 - Distribution: Fedora Linux 40 (Workstation Edition)
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.4.1
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
flatpak run --env=RUST_BACKTRACE=full dev.alextren.Spot
```

**Additional context**
Add any other context about the problem here._

**Comment by sgbx** [comment]
Same here. Could this be related to https://github.com/librespot-org/librespot/issues/1308 ?

**Comment by joaocandre** [comment]
I'm also facing this issue once again, probably #726 should be re-opened?

**Comment by LSeelig** [comment]
> I'm also facing this issue once again, probably #726 should be re-opened?

If I had seen that issue, I would've just commented there instead of making a new issue, but I didn't search closed issues.

**Comment by kinau12** [comment]
Same problem here, both on my pc (Ubuntu 22.04) and phone (postmarketos). Using flatpak version of the app on both devices.

**Comment by Tamaforgi** [comment]
Hi!
Unfortunately I have the same problem. Songs were no longer played, so I had to log out and log in again. Logging in was aborted with an error message saying that the account and password did not match, which is not true. I then uninstalled and reinstalled Spot, problem persists. According to Spotify, no changes have been made.
Raspi 400 with Ubuntu 22.04, installing via Flathub.

**Comment by pabaptista** [comment]
Same issue here. First time using the app and got this error message when trying to login.
Compiled from source.

**Comment by ccnmxns** [comment]
Same problem here. Tried to get creds from the very Spotify app:

https://github.com/dspearson/librespot-auth

Still no luck, but that's a good start tbh

Also, why not using OAuth?

**Comment by idhelman** [comment]
Same problem here.  :(

**Comment by TheSilverFoxes** [comment]
Experiencing the same problem.

**Comment by apposada** [comment]
Hi! I am also experiencing the same problem. This is probably the same as issue https://github.com/xou816/spot/issues/726 .

**Comment by antrmn** [comment]
Same issue here.

**Comment by heyeddi** [comment]
It seems it is a headers issue: https://github.com/librespot-org/librespot/issues/1308#issuecomment-2323112845

**Comment by aleksrutins** [comment]
It seems like librespot has fixed this issue upstream - any chance of a dependency bump?

**Comment by b1zzu** [comment]
Same issue here

**Comment by ihrke** [comment]
same

**Comment by schooldanlp6** [comment]
Currently compiling dev for testing #731

**Comment by schooldanlp6** [comment]
magnificent thanks a lot @[stevenleadbeater](https://github.com/stevenleadbeater) it works now gg on you 

Issue can be closed and to build use
git clone https://github.com/stevenleadbeater/spot -b development

than sudo for installing as root / the entire OS
sudo meson target -Dbuildtype=debug -Doffline=false
sudo ninja install -C target

**Comment by TheSilverFoxes** [comment]
Worked! ( but please remove/fix the first "Log In" button and fields because it doesn't work :) )
EDIT: Logging in DID work, but the actual "playing music part" didn't work lol, cannot search for songs and when I click on the ones on the Library tab it shows nothing.
(excluding "Saved songs" as that did work, the music played)

**Comment by stevenleadbeater** [comment]
> Worked! ( but please remove/fix the first "Log In" button and fields because it doesn't work :) ) EDIT: Logging in DID work, but the actual "playing music part" didn't work lol, cannot search for songs and when I click on the ones on the Library tab it shows nothing. (excluding "Saved songs" as that did work, the music played)

Hi @TheSilverFoxes I'm glad the fix has at least made the app partially usable. Can we please try and practice a little issue hygiene here. This bug was specifically about login and while I do want to get all the issues fixed, it's going to make it hard for me to track if everyone raises new faults on the threads of other issues. 

You are asking for:
1/ Feature request: remove login button as it doesn't work
2/ Bug: Song search not working
3/ Bug: Only saved songs play

Please don't make me do the issue admin for you, it's enough of a task to try and pick up a large and unfamiliar codebase in my spare time to make it work again without that overhead too

**Comment by schooldanlp6** [comment]
> > Worked! ( but please remove/fix the first "Log In" button and fields because it doesn't work :) ) EDIT: Logging in DID work, but the actual "playing music part" didn't work lol, cannot search for songs and when I click on the ones on the Library tab it shows nothing. (excluding "Saved songs" as that did work, the music played)
> 
> Hi @TheSilverFoxes I'm glad the fix has at least made the app partially usable. Can we please try and practice a little issue hygiene here. This bug was specifically about login and while I do want to get all the issues fixed, it's going to make it hard for me to track if everyone raises new faults on the threads of other issues.
> 
> You are asking for: 1/ Feature request: remove login button as it doesn't work 2/ Bug: Song search not working -3/ Bug: Only saved songs play-
> 
> Please don't make me do the issue admin for you, it's enough of a task to try and pick up a large and unfamiliar codebase in my spare time to make it work again without that overhead too

I could help you and we maintaining this together ... also 3rd issue can't confirm
Also this issue is closed as the issue has been resolved
