### ISSUE TITLE
Password reset by Spotify, and logged out of devices, after suspicious activity

### ISSUE THREAD

**Issue by bryce-carson** [xou816/spot#732]
I used this Flatpak today and was unable to log in, depsite using the correct username and password.

Hours later I was logged out of a browser session of the official Spotify web client and Spotify forced me to reset my password.

There could be a chain of custody issue and the Flatpak or this repository could be compromised.

**Comment by ondras12345** [comment]
I think the Spotify detector for "suspicious activity" is just too sensitive.
I no longer actively use Spot, but I had the same issue with mopidy-spotify: see e.g. https://github.com/mopidy/mopidy-spotify/issues/394#issuecomment-2363648572
I cannot say for sure, but I'd be surprised if the flatpak build was actually compromised.

**Comment by xou816** [comment]
Id be surprised too, but Ill have  a look at the sources for the latest release, I havent participated in its release

I guess Spotify is trying to phase out password login for its products, and projects such as spot/librespot/etc are affected (password login has been working hit or miss for the last few weeks/months). they probably have stoppedusing password auth on official products, and what remains is flagged as suspcious -- even before that, spot users would often mention receiving a warning email from spotify

anyway, the good news is that thanks to @stevenleadbeater 's last MR we will use oauth for auth so there shouldnt be any more issues! next release should be good

**Comment by bryce-carson** [comment]
> Id be surprised too, but Ill have  a look at the sources for the latest release, I havent participated in its release
> 
> I guess Spotify is trying to phase out password login for its products, and projects such as spot/librespot/etc are affected (password login has been working hit or miss for the last few weeks/months). they probably have stoppedusing password auth on official products, and what remains is flagged as suspcious -- even before that, spot users would often mention receiving a warning email from spotify
> 
> anyway, the good news is that thanks to @stevenleadbeater 's last MR we will use oauth for auth so there shouldnt be any more issues! next release should be good

Great, sounds good! I've enjoyed using Spot in the past so I was concerned. Spot is a lovely alternative to the bloat of the official application or the Flatpakked form thereof.

**Comment by xou816** [comment]
should be fixed by #731
