### ISSUE TITLE
incorrect login credentials

### ISSUE THREAD

**Issue by sezcl** [xou816/spot#733]
**Describe the bug**
No way to login. Password reset but still no login: " incorrect login credentials " message.
Double checked with the web browser stored credentials, also, restored the password. Same result.

**General information:**
 - Distribution: Debian 12
 - Installation method : Flatpak from Gnome Software ( now, the gnome outdated dependencies warning has gone btw)
 - Version : 0.4.1
 - Device used: laptop

![2024-11-24_23-27](https://github.com/user-attachments/assets/9d92311e-1912-4da4-aa57-b105d41d85c9)

** Yes, Im using premium account **

Thank you for any help/tip. Really need this no-electron version.

Regards.

**Comment by xou816** [comment]
Will be fixed shortly, oauth support is almost complete!

**Comment by adityamwagh** [comment]
Could you please elaborate on "shortly"? 😄

**Comment by vhespanha** [comment]
@adityamwagh

you could check [this](https://www.merriam-webster.com/dictionary/shortly) out, hope it helps.

**Comment by sezcl** [comment]
> Will be fixed shortly, oauth support is almost complete!

Thank you very much for the answer and information.

**Comment by adityamwagh** [comment]
@vhespanha LOL! I just wanted to know if it's going to take days or weeks.

**Comment by xou816** [comment]
someone contributed a MR very recently, i want to iron out a few things and make sure token refresh works properly, then ill make a release with that alone

aiming to do that before ~december 3rd as i wont be available much by them

**Comment by vhespanha** [comment]
not that good at rust, but if any help is needed, i'll be sure to try and contribute. thx.

**Comment by xou816** [comment]
a new release should be up on flathub, if you  want to try it out

**Comment by xou816** [comment]
closing for now, feel free to reopen if you find issues with oauth
