### ISSUE TITLE
Crash immediately after authenticating

### ISSUE THREAD

**Issue by sloshyyy** [xou816/spot#76]
**Describe the bug**
After running on a fresh install without config files, I am prompted to login, after which point the program crashes, and will no longer open.  I do receive an email that there was a login to my spotify account.

**To Reproduce**
1. Install from flathub on a fresh system
2. Run the program
3. Login

**Expected behavior**
The program runs.

**Screenshots**
N/A

**General information:**
 - Distribution: Ubuntu 20.04
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: Flatpak reports the version as 0.1.7 (flatpak commit fd8ac20da582cc1ee4858f971e8c8ecf2bf666457d3f704932bfa208459e8257)
 - Device used [e. g. desktop, phone...]: Desktop

**Stack trace:**
If applicable, run the application from a terminal and paste relevant log output.
```
Gtk-Message: 20:39:16.107: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:39:16.108: Failed to load module "canberra-gtk-module"
home
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/app/backend/api_models.rs:329:50
stack backtrace:
   0:     0x55d6a3b48230 - <unknown>
   1:     0x55d6a3b6bcdc - <unknown>
   2:     0x55d6a3b40e12 - <unknown>
   3:     0x55d6a3b4a4d5 - <unknown>
   4:     0x55d6a3b4a02a - <unknown>
   5:     0x55d6a3b4ac71 - <unknown>
   6:     0x55d6a3b4a787 - <unknown>
   7:     0x55d6a3b486ec - <unknown>
   8:     0x55d6a3b4a719 - <unknown>
   9:     0x55d6a3b694f1 - <unknown>
  10:     0x55d6a3b6943d - <unknown>
  11:     0x55d6a335943e - <unknown>
  12:     0x55d6a33aa8f7 - <unknown>
  13:     0x55d6a3389b73 - <unknown>
  14:     0x55d6a340c371 - <unknown>
  15:     0x55d6a340387e - <unknown>
  16:     0x55d6a33f490c - <unknown>
  17:     0x55d6a33e5bae - <unknown>
  18:     0x55d6a3346d64 - <unknown>
  19:     0x55d6a3b1b785 - <unknown>
  20:     0x55d6a3b1d09a - <unknown>
  21:     0x7f790103b53b - g_main_context_dispatch
  22:     0x7f790103b7e8 - <unknown>
  23:     0x7f790103b8b3 - g_main_context_iteration
  24:     0x7f790126158d - g_application_run
  25:     0x55d6a33b585e - <unknown>
  26:     0x55d6a3369408 - <unknown>
  27:     0x7f790103c665 - g_main_context_invoke_full
  28:     0x55d6a3438589 - <unknown>
  29:     0x55d6a3362873 - <unknown>
  30:     0x55d6a332b919 - <unknown>
  31:     0x55d6a3b4b097 - <unknown>
  32:     0x55d6a34389c2 - main
  33:     0x7f7900ca2062 - __libc_start_main
  34:     0x55d6a32fb13e - <unknown>
  35:                0x0 - <unknown>

```

**Additional context**

I can't seem to find all of the config files, so I can't delete them to get back to a login screen and continue troubleshooting, other than looking at terminal output.  I logged in using an email and password.  I had reinstalled recently for unrelated reasons, and this crash happens on both installs.

**Comment by sloshyyy** [comment]
It runs when building from source with gnome builder.

**Comment by xou816** [comment]
Looks like you've run into https://github.com/xou816/spot/issues/54 which is fixed on master but not yet on flathub! This will be released soon :)
