### ISSUE TITLE
Cargo.toml libhandy git

### ISSUE THREAD

**Issue by svdm-gentoo** [xou816/spot#79]
Currently the Cargo.toml tries to fetch libhandy from the internet. The portage package manager (gentoo) doesn't allow this, I presume because of security. It would be really appreciated if this line:
libhandy = { git = "https://gitlab.gnome.org/World/Rust/libhandy-rs" }
Could be changed into, for example:
libhandy = "^1.0.3"

Thanks for reading!

**Comment by svdm-gentoo** [comment]
Also, sorry for labeling this as a bug. I'm kind of new to github and should have labeled it as enhancement.

**Comment by xou816** [comment]
Hi! No worries! I'll update the labels accordingly :)

Actually, the flatpak build system has the same kind of requirement, and goes even further: you're not even allowed to download crates from crates.io at build time. 

Long story short, there's a file (cargo-sources.json) that lists all the urls for all dependencies and downloads all that before the build, then cargo can be set to run in offline mode and works with these pre-downloaded dependencies (including libhandy).
 
I don't know how gentoo's buildsystem works, but surely something similar could be done? Or does it only trust a limited set of domains? (I'd be surprised if it allowed crates.io but not Gnome's gitlab)

**Comment by xou816** [comment]
(by the way, libhandy-rs is not yet? on crates.io so I can't do that)

**Comment by svdm-gentoo** [comment]
In gentoo there's a network sandbox, the only way to be able to download files is to download them using SRC_URI="https://filename" or using [eclasses](https://devmanual.gentoo.org/eclass-reference/cargo.eclass/index.html). This one allows you to download files from crates.io. There is actually another [issue](https://dpaste.com/DZLFDS3LZ) I've come across, but I suspect it has something to do with the network sandbox.

**Comment by xou816** [comment]
Oh, interesting!

Apparently I was wrong, I don't know why I thought it necessary to use libhandy-rs from gitlab :thinking: I'll try switch to the crates.io version and will report back :)

As for your second error: is there no other output? If it's network related, it might be that cargo needs to be run offline, its dependencies having been downloaded using your cargo eclass. Have you configured the build with -Doffline=true?
