### ISSUE TITLE
Support for offline playlist

### ISSUE THREAD

**Issue by dbadura** [xou816/spot#81]
**Describe the feature**
Is it possible to use offline playlist

**General information:**
 - Distribution: Ubuntu
 - Installation method [e. g. built from source, installed from Flathub...]: Flathub
 - Version [e.g. 0.1.0]: 0.1.7
 - Device used [e. g. desktop, phone...]: Desktop

**Comment by xou816** [comment]
Not sure what you mean, sorry! Offline playback? (not possible with librespot, for good reasons) Local tracks? (quite complicated)

**Comment by dbadura** [comment]
Yes I mean offline playback.

Ok, I found the issue in librespot: https://github.com/librespot-org/librespot/issues/598

Thanks for fast response. I can close the issue ;)
