### ISSUE TITLE
Clicking on the notification area box does not open or focus the app

### ISSUE THREAD

**Issue by echosa** [xou816/spot#82]
**Describe the bug**
When running Spot (or any media player in GNOME), a "notification" box shows up in the notifications area that allows easy access and control of music from anywhere. Screenshot:
![image](https://user-images.githubusercontent.com/133786/108562789-05b87d80-72c6-11eb-8ea3-432753a707a4.png)

The controls in this box work fine: play, pause, next, and previous. However, if I click anywhere else in the box (not on the controls) as I would a "normal" notification, I expect Spot to open, raise, or take focus. This does not happen.

**To Reproduce**
1. Open Spot
2. Start playing a song
3. Focus another window and/or minimize Spot
4. Open the GNOME activities area
5. Click on the notification box for Spot (but not the playback controls)

**Expected behavior**
Spot should come forward and/or be focused.

**General information:**
 - Distribution: Pop!_OS 20.10
 - Installation method [e. g. built from source, installed from Flathub...]: Flatpak through Flathub
 - Version [e.g. 0.1.0]: 0.1.7
 - Device used [e. g. desktop, phone...]: laptop

**Comment by echosa** [comment]
I just tried this with the actual Spotify client, and it also does not raise when clicked, so I thought this might be a GNOME issue. However, when I try with [Lollypop](https://wiki.gnome.org/Apps/Lollypop), it does work.

**Comment by xou816** [comment]
It's definitely an issue with spot, I am not properly implementing the MPRIS specification (I've been lazy!), specifically this : https://specifications.freedesktop.org/mpris-spec/latest/Media_Player.html#Method:Raise

Thank you for the report! :)

**Comment by xou816** [comment]
fixed by 97ec540812193a0891e43c93fe5df91b56173aeb :)
