### ISSUE TITLE
Shuffling long playlists causes UI to freeze

### ISSUE THREAD

**Issue by Douile** [xou816/spot#87]
**Describe the bug**
When toggling shuffle on a long playlist (e.g. 50+ songs) the UI freezes.

**To Reproduce**
1. Play long playlist
2. Press shuffle button (maybe a few times)
3. UI unresponsive while shuffling

**Expected behavior**
UI remains responsive during shuffle. And also maybe button is disabled while it is shuffling. 

**General information:**
 - Distribution: N/A
 - Installation method [e. g. built from source, installed from Flathub...]: source
 - Version [e.g. 0.1.0]: 0.1.8
 - Device used [e. g. desktop, phone...]: Desktop

**Additional context**
If possible shuffling should be done on a separate thread as it is quite intensive/time consuming.

**Comment by xou816** [comment]
I don't think it is the shuffling that's to blame here, I might be wrong though! 

I think it is either of two things:
- we've run into the limits of listboxes/flowboxes;
- or (more likely) my poor implementation of playlists is showing :p

More on the second point: playlists are stored in a Vec, which implies O(n) lookup at worst, and I'm looking up tracks this way to create the menus for each song... which leads to O(n²) complexity :D I've been lazy... if you don't mind, I'd like to take some time to fix this, I've been putting it off for too long!

**Comment by xou816** [comment]
So, I timed the shuffling: it's very fast, no issues there!

The slowness if when filling the store (`Playlist::reset_list`), I tried using [splice](https://gtk-rs.org/docs/gio/trait.ListStoreExt.html#tymethod.splice) but it did not change much :/ I also spent some time removing that O(n²) thingy.

What's weird is that if I toggle shuffle a couple times in a row for a long playlist, it takes more and more time to update the store (durations are in ms, I am measuring the splice func):
```
playlist_12WVIxcVFwfTrCSOIxk6UP
464 (100 items)
586 (100 items)
814 (100 items)
916 (100 items)
1042 (100 items)
1199 (100 items)
1577 (100 items)
2073 (100 items)
1690 (100 items)
1795 (100 items)
```

Something is leaking, and I can't figure out what :(

**Comment by xou816** [comment]
Oh okay, got it... I am calling screen_add_css_provider() way too often... also using builders is kind of slow

**Comment by xou816** [comment]
Closing this for now, it's improved a lot in 85afa110e1b57ab0cdaa87a8e7e0eb08faec0dde feel free to reopen if you notice something else on master!

**Comment by Douile** [comment]
Very nice work :+1:
