### ISSUE TITLE
MPRIS/rescrobbled: track position and end of playlist are not properly implemented

### ISSUE THREAD

**Issue by raaffaaeell** [xou816/spot#97]
Hello there, first of all, really nice project, and I'm looking forward  for the development.

When using rescrobbled I noticed it was not scrobbling the songs, it did recognize the track but when I debugged rescrobbled I noticed that it was always getting 0 from the track length, I dont know the specifics of the crate (mpris = "2.0.0-rc2") but getting the length_as_micro works. Any idea why ?

When using the official spotify client it seems to get correctly the track length, but with spot only that other method works

**Comment by xou816** [comment]
Hi! The current MPRIS implementation is fairly incomplete, so thank you for your report, it helps me to known which elements to prioritize in the implementation :) I assume rescrobbled expects a proper implementation of the track duration and current position, but [the position is hardcoded right now](https://github.com/xou816/spot/blob/master/src/app/dbus/mpris.rs#L214). The track duration should be fine however!

**Comment by raaffaaeell** [comment]
I didnt notice that code you posted, what's really funny, is that despite that, rescrobbled is working because it's doing it's own thing to calculate the amount of time played for the current song lmao

Another minor thing I noticed, when an album ends, the playback doesnt stop (no pause or stop signal is sent),  wouldnt be an issue if it didnt matter that much for this particular scrobbler because when I checked my lastfm, it had like 15+ scrobbles of the same song lol

If you want I can create another issue so you might be able to track it better

**Comment by xou816** [comment]
Oh, good catch! I don't mind using this one issue to track both things. I'll have a look when possible!

**Comment by xou816** [comment]
Hi again @raaffaaeell , would you mind trying this build to see if it helps with your issues? https://github.com/xou816/spot/suites/2125492563/artifacts/43370055

**Comment by raaffaaeell** [comment]
Hello there, I'll see if I can test it later, at most tomorrow night hehe, thank you very much

**Comment by xou816** [comment]
Sure no worries :) thanks!

**Comment by raaffaaeell** [comment]
Hello there, I was a bit idle here and got around installing from that flatpak (I'm not that familiar with it), but now both cases seems to be working fine.

Thank you for your time and quick responses, keep up the good work

**Comment by xou816** [comment]
Ahah that was fast, great then, thanks for testing! This will be in the next release :)
