### ISSUE TITLE
Attempting to start multiple instances of the app corrupts the primary instance

### ISSUE THREAD

**Issue by Genora51** [xou816/spot#98]
**Describe the bug**
When I press the close button, Spot stays running in the background; this causes performance issues when repeatedly opening and closing spot.

Quitting spot from the system tray does properly close the app, however.

**To Reproduce**
1. Open spot
2. Close spot
3. Run `ps aux | grep spot`
4. See that the process is still running

**Expected behavior**
The spot process should end on close.

**General information:**
 - Distribution: Ubuntu 20.04
 - Installation method: Snap package
 - Version: 0.1.8
 - Device used: Desktop

**Stack trace:**
N/A

**Additional context**
N/A

**Comment by xou816** [comment]
Hi! Thanks for the report.
The fact that it does not close is intentional (to allow playback to continue when the window is hidden, similarly to other music players). However, the performance issue is definitely a bug, I'll have a look!

**Comment by xou816** [comment]
Should be fixed on master!
